### ISSUE TITLE
[Feature request] 为gRPC添加指定alpn选项

### ISSUE THREAD

**Issue by LitCcc** [yichya/luci-app-xray#104]
[类似issue](https://github.com/xiaorouji/openwrt-passwall/issues/1303)

部分一键脚本搭建的xray服务在使用grpc时需要手动指定`alpn`为`h2`，不知道开发者能否给grpc加上指定alpn的选项呢？

**Comment by yichya** [comment]
过几天搞吧。

**Comment by yichya** [comment]
试一试 #105 吧。没问题就合并

**Comment by LitCcc** [comment]
通过新增的alpn选项指定alpn后可以正常使用
