### ISSUE TITLE
功能需求：可否增加“黑洞”Reject的分流

### ISSUE THREAD

**Issue by SasamiMasakiJurai** [yichya/luci-app-xray#106]
目前在dns设置里面已有根据site的分流，

可否增加“黑洞”Reject的分流，

在 https://github.com/Loyalsoldier/v2ray-rules-dat 中可以看到，

已有 geosite:category-ads-all、geosite:win-spy等标注，

如果增加该功能，

则可以省去与adbolck或者adguard home等的适配，

目前这类屏蔽插件很容易与dns解析或者端口引发冲突。

**Comment by yichya** [comment]
这个要做的话 DNS 那部分可能就得大改一波了，后续考虑

**Comment by SasamiMasakiJurai** [comment]
嗯，
理解，
目前貌似就win端的看到有这样的功能，
路由端目前没看到过。

**Comment by yichya** [comment]
#154 暂时做了一个比较简单的，够用
