### ISSUE TITLE
进service-xray出现如图状况

### ISSUE THREAD

**Issue by 3xpert** [yichya/luci-app-xray#111]
![image](https://user-images.githubusercontent.com/8335065/143017135-2c45b99d-c873-4435-8130-89c9f325f61f.png)
syslog里没有相应的错误信息，xray是issue #108 后编译的

**Comment by yichya** [comment]
f12 console 贴一下看看

**Comment by 3xpert** [comment]
![image](https://user-images.githubusercontent.com/8335065/143018743-cfa1228d-b74d-4b50-b391-3acd8e379b7d.png)

**Comment by 3xpert** [comment]
用firefox没问题，又是chrome？

**Comment by LitCcc** [comment]
我这里openwrt 21.02+chrome 96显示正常

**Comment by yichya** [comment]
看代码位置，这个应该是 hosthints 里面有的 mac 没有对应上 ip，但很难理解为什么会有这种问题，回头补个判空

**Comment by 3xpert** [comment]
> 我这里openwrt 21.02+chrome 96显示正常

确实，在我新建的openwrt 21.02.1里是正常的

**Comment by 3xpert** [comment]
firefox升级后，也出现了同样的issue了
![image](https://user-images.githubusercontent.com/8335065/143975589-ee528e0a-bfff-4413-97fc-980facf56e0c.png)

**Comment by 3xpert** [comment]
> 我这里openwrt 21.02+chrome 96显示正常

我这里ESXI下openwrt主路由+openwrt19.07（网关+DNS）网速正常，如果网关设在openwrt20.02上，网速只剩百兆了。
@LitCcc 你的openwrt20.02下的网速正常吗？

**Comment by LitCcc** [comment]
我这里主路由openwrt 21.02+AP正常

**Comment by yichya** [comment]
抄了一下 luci-app-wol 的代码应该能避免这个问题了。

**Comment by 3xpert** [comment]
是的，可以了
