### ISSUE TITLE
功能需求：是否有让BT流量直连的设置

### ISSUE THREAD

**Issue by SasamiMasakiJurai** [yichya/luci-app-xray#112]
今天下载BT，
发现国外的流量全部走服务器了，
服务器流量一下子暴涨，
然后发现

https://github.com/Loyalsoldier/v2ray-rules-dat

“BT 流量统统直连（实测依然会有部分 BT 流量走代理，如果服务商禁止 BT 下载，请不要为下载软件设置代理）”

        "type": "field",
        "outboundTag": "Direct",
        "protocol": ["bittorrent"]

请问，
现在办法可以设置吗？

**Comment by yichya** [comment]
建议先用 Custom Configurations 处理。

**Comment by SasamiMasakiJurai** [comment]
试了下，
单独把这段放入routing类里面不起任何效果，
但是如果把自己写的config贴入自定义里面，
整个网络就断了
