### ISSUE TITLE
Compatible with official OpenWrt packages/xray-core

### ISSUE THREAD

**Issue by yichya** [yichya/luci-app-xray#119]
因为配置文件和 init 脚本的命名都跟 [https://github.com/openwrt/packages/tree/master/net/xray-core](https://github.com/openwrt/packages/tree/master/net/xray-core) 重复了，所以目前 luci-app-xray 没有办法跟它共存。

要解决这一问题的话可能有两个办法

* 推动上游 xray-core 主程序和 init 文件分离（可能会比较困难）
* luci-app-xray 自身做一些比较大的改动适应上游 xray-core 的 init 脚本（无法保证平滑升级，需要重新填配置）

这个 issue 算是一个意见收集，如果有比较强烈的需求的话会考虑通过上述方式之一解决这个问题。

觉得有必要解决这个问题的话可以在这条 issue 上点一个 +1（👍），没有必要的话可以点一个 -1（👎）

**Comment by SasamiMasakiJurai** [comment]
个人认为一劳永逸的办法是2，
无法平滑升级应该不是大问题，
只需要重新填写一次即可，
而且后续可以在官方源进行自动更新。

**Comment by yichya** [comment]
> 个人认为一劳永逸的办法是2，
> 
> 无法平滑升级应该不是大问题，
> 
> 只需要重新填写一次即可，
> 
> 而且后续可以在官方源进行自动更新。

同意这种做法的可以在这里点 +1

**Comment by yichya** [comment]
另外考虑了一种夺舍的方式来做（#128）。大概能实现不需要重新填配置，不过可能会出现某些情况下配置文件不能替换掉的情况。
