### ISSUE TITLE
xray 服务器

### ISSUE THREAD

**Issue by lwk523** [yichya/luci-app-xray#120]
有谁知道哪里有 IPk file ? 我需要用树莓派来做 Xray ， Vless 服务器呢 。 

谢谢

**Comment by yukeiyang** [comment]
需要自己编译

**Comment by Mitsuhaxy** [comment]
xray-openwrt可以当作服务器端文件，xray二进制文件既是服务器又是客户端

**Comment by lwk523** [comment]
> xray-openwrt可以当作服务器端文件，xray二进制文件既是服务器又是客户端

谢谢你的回复， 我去了解下 什么是 xray二进制文件。。如你有很好的教学网站， 希望你可以分下给我呢。。

**Comment by Mitsuhaxy** [comment]
> > xray-openwrt可以当作服务器端文件，xray二进制文件既是服务器又是客户端
> 
> 
> 
> 谢谢你的回复， 我去了解下 什么是 xray二进制文件。。如你有很好的教学网站， 希望你可以分下给我呢。。 
> 
> 

https://xtls.github.io/document/level-0/
可以参考一下这个，作为一个全新安装就好了
