### ISSUE TITLE
编译安装成功 luci没找到菜单入口

### ISSUE THREAD

**Issue by v03413** [yichya/luci-app-xray#126]
基于lean 最新的源码编译，都安装成功了，但却luci却找不到菜单入口，是我操作方法不对吗？

<img width="841" alt="WX20211220-171316@2x" src="https://user-images.githubusercontent.com/49953737/146742762-3fb7d506-d191-4c71-a8dc-a9ac5f760eea.png">
<img width="693" alt="WX20211220-170339@2x" src="https://user-images.githubusercontent.com/49953737/146742763-4d8e38e0-7bcb-4422-8028-bedfccb09ab9.png">

**Comment by v03413** [comment]
重启了一下，系统日志现实，貌似是没拉起来
![image](https://user-images.githubusercontent.com/49953737/146743897-e4fb840b-5de3-47e0-9a6c-374c0838c726.png)

**Comment by yichya** [comment]
#96 有说过没有办法兼容 lean 那一套，那个 luci 太老了没办法兼容

**Comment by v03413** [comment]
> #96 有说过没有办法兼容 lean 那一套，那个 luci 太老了没办法兼容

好吧，感谢解答，谢谢～
