### ISSUE TITLE
LAN Hosts Access Control

### ISSUE THREAD

**Issue by xcyll** [yichya/luci-app-xray#150]
Hello，there is only “Will not enable transparent proxy for these MAC addresses” option (Allow all except listed) in access control.
Can you add an Allow listed only option so that i can only proxy specific devices and all others will be directly connected.
Thank you in advance.

**Comment by yichya** [comment]
Maybe I'll add that feature in the coming weeks

**Comment by yichya** [comment]
This feature is added in v3.1.0 (like after 100 weeks
