### ISSUE TITLE
Is it possible to have a something like step to step installation guide?

### ISSUE THREAD

**Issue by lidfgab** [yichya/luci-app-xray#157]
As a openWRT newber, I searched the installation guides for serval days,I found a installation document for expert, but I cannot find a step to step installation guide for this luci-app.
Is it possible to have a step-to-step guide?

**Comment by Mitsuhaxy** [comment]
Have you compiled this ipk file?

**Comment by lidfgab** [comment]
> Have you compiled this ipk file?

Tried, but failed

**Comment by Mitsuhaxy** [comment]
> > Have you compiled this ipk file?
> 
> 
> 
> Tried, but failed

Try using the openwrt official sdk container to match the surprise tag and your architecture or chip.

**Comment by Mitsuhaxy** [comment]
> > Have you compiled this ipk file?
> 
> 
> 
> Tried, but failed

Try using the openwrt official sdk container to match the docker image tag and your architecture or chip.

**Comment by lidfgab** [comment]
I'm compiling this project in Centos 9, SDK openwrt-sdk-21.02.0-x86-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz 
with this guide below
https://github.com/honwen/luci-app-xray
but when I make && sudo make install
it told me error below
"
 make[3] -C feeds/packages/utils/zstd compile
 make[3] -C package/luci-app-xray compile
 make[2] package/index
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/tmp/openwrt-sdk-21.02.0-x86-generic_gcc-8.4.0_musl.Linux-x86_64/include/toplevel.mk:223: world] Error 1
"
what's wrong with me?

**Comment by Mitsuhaxy** [comment]
> I'm compiling this project in Centos 9, SDK openwrt-sdk-21.02.0-x86-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz with this guide below https://github.com/honwen/luci-app-xray but when I make && sudo make install it told me error below " make[3] -C feeds/packages/utils/zstd compile make[3] -C package/luci-app-xray compile make[2] package/index make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on make: *** [/tmp/openwrt-sdk-21.02.0-x86-generic_gcc-8.4.0_musl.Linux-x86_64/include/toplevel.mk:223: world] Error 1 " what's wrong with me?

If you need to compile it yourself, please google "how to compile the openwrt single package", there are already compiled IPK files available.
https://blog.mitsuha.me/post/56

**Comment by Mitsuhaxy** [comment]
> I'm compiling this project in Centos 9, SDK openwrt-sdk-21.02.0-x86-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz with this guide below https://github.com/honwen/luci-app-xray but when I make && sudo make install it told me error below " make[3] -C feeds/packages/utils/zstd compile make[3] -C package/luci-app-xray compile make[2] package/index make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on make: *** [/tmp/openwrt-sdk-21.02.0-x86-generic_gcc-8.4.0_musl.Linux-x86_64/include/toplevel.mk:223: world] Error 1 " what's wrong with me?

Compilation process:
1. Go to the SDK package folder
2. Pull the project
3. Execute the command `./script/feeds update luci-app-xray && ./script/feeds/install luci-app-xray`
4. Execute the command `make package/luci-app-xray/compile`

**Comment by lidfgab** [comment]
1. install CentOS 9 on the outside, or some package may cannnot download
2. dnf install -y wget git gcc gcc-c++ perl-Thread-Queue
3. cd /tmp/
4. wget https://downloads.openwrt.org/releases/21.02.1/targets/x86/generic/openwrt-sdk-21.02.1-x86-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz
5. tar -xJf openwrt-sdk-21.02.1-x86-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz
6. cd openwrt-sdk-21.02.1-x86-generic_gcc-8.4.0_musl.Linux-x86
7. git clone https://github.com/yichya/luci-app-v2ray.git package/luci-app-v2ray
8. you may need to install po2lmo which didn't inculding in this package
9. ./scripts/feeds update -a
10. ./scripts/feeds install eip197-mini-firmware r8169-firmware e100-firmware bnx2-firmware bnx2x-firmware ar3k-firmware mwifiex-sdio-firmware kmod-phy-bcm-ns-usb2 edgeport-firmware kmod-phy-bcm-ns-usb3 amdgpu-firmware radeon-firmware prism54-firmware rtl8192su-firmware luci-base xray-core dnsmasq ipset firewall iptables iptables-mod-tproxy ca-bundle 
11. make menuconfig 
12. make package/luci-app-v2ray/compile V=99

**Comment by lidfgab** [comment]
when I try to compile the newest version, it told me 
"
bash: line 1: proxychains: command not found
"
where can I got this?

**Comment by Mitsuhaxy** [comment]
> when I try to compile the newest version, it told me 
> 
> "
> 
> bash: line 1: proxychains: command not found
> 
> "
> 
> where can I got this?

Try to use openwrt official SDK Docker image , they have full toolchain and compile env

**Comment by yichya** [comment]
> bash: line 1: proxychains: command not found

just don't select "Fetch data files using proxychains" when compiling [yichya/openwrt-xray](https://github.com/yichya/openwrt-xray) as it is not recommended in most cases, or use official [packages/xray-core](https://github.com/openwrt/packages/tree/master/net/xray-core) instead of [yichya/openwrt-xray](https://github.com/yichya/openwrt-xray).

> Try to use openwrt official SDK Docker image

This tool is not included in OpenWrt SDK and the version on your host machine is being used so if you know what that tool is, use apt (or similar package management tools according to your distribution) to install proxychains / proxychains-ng and configure it to use a valid proxy to accelerate some geodata fetching process.

**Comment by BK8000L** [comment]
> If you need to compile it yourself, please google "how to compile the openwrt single package", there are already compiled IPK files available. https://blog.mitsuha.me/post/56

@Mitsuhaxy, can you please re-upload the file?

**Comment by Mitsuhaxy** [comment]
> > If you need to compile it yourself, please google "how to compile the openwrt single package", there are already compiled IPK files available. https://blog.mitsuha.me/post/56
> 
> @Mitsuhaxy, can you please re-upload the file?

OK,right here.
https://mitsuha.me/luci-app-xray_1.14.0-1_all.ipk
Please manually install `ipset` and`iptables-mod-tproxy`
If your Openwrt version is 22, please install `kmod-nft-tproxy`

**Comment by Tualua** [comment]
@Mitsuhaxy could you please re-upload files? It's 404 now

**Comment by malikshi** [comment]
> > > If you need to compile it yourself, please google "how to compile the openwrt single package", there are already compiled IPK files available. https://blog.mitsuha.me/post/56
> > 
> > 
> > @Mitsuhaxy, can you please re-upload the file?
> 
> OK,right here. fw3:https://mitsuha.me/luci-app-xray_1.14.0-1_all_fw3.ipk fw4:https://mitsuha.me/luci-app-xray_1.14.0-1_all_fw4.ipk 21.x:FW3;22.x:FW4.

website not online.
can someone create GA to automatically compile luci-app-xray?
