### ISSUE TITLE
请问geoip_list.pb 的作用是什么？

### ISSUE THREAD

**Issue by AAPING** [yichya/luci-app-xray#158]
作者你好，我阅读代码的时候发现 https://github.com/yichya/luci-app-xray/blob/master/root/usr/share/xray/geoip_list.pb 这个二进制文件似乎没有在代码任何一处被引用，请问这个文件是起什么作用的呢？如果是 protobuf 格式的geoip 的清单，我该怎样定制这个的清单呢？（比如，可以 run 个什么脚本来生成呢？）我看你有另一个 repo 是 lua-protbuf， 是用那个repo吗？
谢谢！

**Comment by yichya** [comment]
geoip.dat 和 geosite.dat 本身就是 protobuf 格式的，geoip_list.pb 是这两个文件的格式定义，计划在 #153 中使用。

如果有定制 geoip.dat 和 geosite.dat 的需求，可以看看
* [https://github.com/Loyalsoldier/geoip](https://github.com/Loyalsoldier/geoip)
* [https://github.com/Loyalsoldier/domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom)
* [https://github.com/yichya/openwrt-xray-geodata-cut](https://github.com/yichya/openwrt-xray-geodata-cut)

**Comment by AAPING** [comment]
> geoip.dat 和 geosite.dat 本身就是 protobuf 格式的，geoip_list.pb 是这两个文件的格式定义，计划在 #153 中使用。
> 
> 如果有定制 geoip.dat 和 geosite.dat 的需求，可以看看
> 
> * https://github.com/Loyalsoldier/geoip
> * https://github.com/Loyalsoldier/domain-list-custom
> * https://github.com/yichya/openwrt-xray-geodata-cut

明白了，非常感谢解答！
