### ISSUE TITLE
openwrt 21.2.1官方源碼不識別luci-app-xray

### ISSUE THREAD

**Issue by Tonkercke** [yichya/luci-app-xray#159]
我將下載好的luci-app-xray放到openwrt源碼下的feeds/luci/applications目錄下，運行./scripts/feeds update -a ;./scripts/feeds install -a之後，運行make menuconfig，但是在打開的luci->applications菜單中找不到luci-app-xray。按照上述步驟放入其他任何luci源代碼都是可以識別的，唯獨不顯示luci-app-xray。另外，當退出menuconfig之後會顯示以下報錯：
tmp/.config-package.in:5937:error: recursive dependency detected!
tmp/.config-package.in:5937:	symbol PACKAGE_luci-app-xray depends on PACKAGE_luci-app-xray
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
上述問題該如何解決，望指點。

**Comment by yichya** [comment]
> 但是在打開的luci->applications菜單中找不到luci-app-xray

在 Extra packages 里面呢。
