### ISSUE TITLE
是否考虑把tools/po2lmo增加到仓库中？

### ISSUE THREAD

**Issue by Zieng** [yichya/luci-app-xray#172]
看到仓库https://github.com/yichya/luci-app-v2ray 中是包含这个子文件夹的，并且下面的编译步骤中也需要这个。另外在https://github.com/honwen/luci-app-xray 这个仓库中看到也是需要这个文件的。

**Comment by yichya** [comment]
没精力整多语言。。。建议看看 https://github.com/Mitsuhaxy/luci-i18n-xray-zh-cn
