### ISSUE TITLE
After installing on OpenWrt 20.02.1 no service menu available

### ISSUE THREAD

**Issue by rolders** [yichya/luci-app-xray#177]
xray & this Luci app both installed successfully, but nothing is visible via the Luci UI. I was expecting to see a services menu appear in Luci. The steps I followed were as below, and both completed successfully:

1. Install xray:
`opkg install xray-core xray-geodata`
2. followed by install luci-app-xray
`opkg install luci-app-xray_1.5.2-1_all.ipk`

Is there any troubleshooting that can be done to find the problem, or any additional steps I should follow?

**Comment by yichya** [comment]
Please take a screenshot of your luci overview page with firmware version shown

![image](https://user-images.githubusercontent.com/3683052/165026628-0448c9b0-5fc5-4abe-8b28-b970da7f4002.png)

**Comment by rolders** [comment]
Thanks, here you go!

<img width="900" alt="image" src="https://user-images.githubusercontent.com/3395757/165028409-05a6bd15-afe5-47c3-af0b-5d1dd1193455.png">

**Comment by yichya** [comment]
try 

* `rm /tmp/luci-indexcache*`
* if it didn't work, `reboot`

**Comment by rolders** [comment]
I tried both, but still no services menu. I didn't mention, but the xray &
luci packages were installed to a usb drive mounted at /mnt/sda/packages/
and using the opkg -d option.

**Comment by rolders** [comment]
I tried both, but still no services menu. I didn't mention, but the xray & luci packages were installed to a usb drive mounted at /mnt/sda/packages/ and using the opkg -d option.

**Comment by rolders** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/3395757/165038096-c6bea050-682e-4aec-8710-35b6d66dc68c.png">

**Comment by rolders** [comment]
This path is empty though:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/3395757/165038359-8a8d299a-a86f-42b7-99d4-03016ef4312b.png">

**Comment by yichya** [comment]
> I tried both, but still no services menu. I didn't mention, but the xray & luci packages were installed to a usb drive mounted at /mnt/sda/packages/ and using the opkg -d option.

I've never tried that kind of installation method and this project relies on files referenced by absolute path (especially `/usr/share/xray`) so if you install these packages to some different path it may not work well.

If you are trying to expand root partition size maybe try [extroot](https://openwrt.org/docs/guide-user/additional-software/extroot_configuration) instead.

> <img alt="image" width="482" src="https://user-images.githubusercontent.com/3395757/165038096-c6bea050-682e-4aec-8710-35b6d66dc68c.png">

These files are apparently in wrong path.

> This path is empty though:
> 
> <img alt="image" width="437" src="https://user-images.githubusercontent.com/3395757/165038359-8a8d299a-a86f-42b7-99d4-03016ef4312b.png">

This path is expected to be empty if you are not using `HTTPS Server` function.

**Comment by yichya** [comment]
> As you mention the project references files by absolute path, so if I can move the relevant file paths to the usb you think it could work?

That would be much too complicated.

Maybe try:

* install `xray-core` and `xray-geodata` to your alternative destination on `/mnt/sda`
* install `luci-app-xray` directly to `/`
* make several symbolic links for these big files
    * `/usr/bin/xray`
    * `/usr/share/xray/geosite.dat`
    * `/usr/share/xray/geoip.dat`
