### ISSUE TITLE
请问是否暂不支持openwrt 22.03.0-rc1

### ISSUE THREAD

**Issue by jaesony** [yichya/luci-app-xray#178]
root@OpenWrt:~# opkg install /tmp/luci-app-xray_1.10.1-1_all.ipk
Installing luci-app-xray (1.10.1-1) to root...
Installing firewall (2022-01-10-0f16ea5f-2) to root...
Collected errors:
 * check_conflicts_for: The following packages conflict with firewall:
 * check_conflicts_for:         firewall4 *
 * opkg_install_cmd: Cannot install package luci-app-xray.

**Comment by yichya** [comment]
目前还没做 firewall4 的支持，近期会开始搞

**Comment by jaesony** [comment]
好的

**Comment by SasamiMasakiJurai** [comment]
那么是否可以在首页注明下当前支持版本或者不支持版本
方便其他人知晓呢？

**Comment by yichya** [comment]
> 那么是否可以在首页注明下当前支持版本或者不支持版本 方便其他人知晓呢？

* 22.03 本身也在 rc，用的人确实很少
* 即使用 22.03，也可以通过不装 fw4 改用 fw3 的情况下使用
* fw4 支持在做了在做了（咕咕咕），最近太忙

**Comment by SasamiMasakiJurai** [comment]
> > 那么是否可以在首页注明下当前支持版本或者不支持版本 方便其他人知晓呢？
> 
> * 22.03 本身也在 rc，用的人确实很少
> * 即使用 22.03，也可以通过不装 fw4 改用 fw3 的情况下使用
> * fw4 支持在做了在做了（咕咕咕），最近太忙

嗯 嗯 
理解
