### ISSUE TITLE
关于汉化及规则配置的问题

### ISSUE THREAD

**Issue by hululu1068** [yichya/luci-app-xray#188]
OpenWrt-x86_64-Official21.02.3

试了几个主题，似乎汉化还有些问题
<img width="1018" alt="2022-06-12_14-23-14" src="https://user-images.githubusercontent.com/68652362/173220756-fea5cca8-8c09-43db-b3de-c4be21f3aa52.png">

规则可否用2x3的形式，或者导入规则的形式
<img width="877" alt="2022-06-12_14-38-28" src="https://user-images.githubusercontent.com/68652362/173220819-53757382-b59e-4290-95a6-4fa2c4eebdac.png">

**Comment by yichya** [comment]
> 试了几个主题，似乎汉化还有些问题

从截图上看这个怕是相当久远的代码了，建议更新一下



> 规则可否用2x3的形式，或者导入规则的形式

域名已经是这样的了，IP 的部分最近应该会做调整支持这三种

**Comment by yichya** [comment]
> 这个有带中文吗？我用官方22.03编译是英文的。

个人精力有限，试试 [Mitsuhaxy/luci-i18n-xray-zh-cn](https://github.com/Mitsuhaxy/luci-i18n-xray-zh-cn)
