### ISSUE TITLE
最近编译的固件TPROXY是不是有问题？

### ISSUE THREAD

**Issue by dfldylan** [yichya/luci-app-xray#196]
大体情况就是PREROUTING表中最后一步TPROXY虽然有记录流量，但是在xray日志中好像并没有接收到这些流量。
但是在OUTPUT表中的TPROXY是正常的，xray日志中也体现出来这一点。
[https://github.com/immortalwrt/immortalwrt/issues/737](url)

**Comment by yichya** [comment]
具体你的版本（OpenWrt / luci-app-xray, 最好是 commit id）是用的哪个？我这边没发现这种情况

**Comment by dfldylan** [comment]
就是最新的commit[53b49746d9f88faa25d40ff4624ab02a6a5be7f6]，奇怪的是我一周之前也是这个commit是好用的，就是这几天编译的固件透明代理有问题

**Comment by dfldylan** [comment]
看看是不是有其他人最近编译固件有同样的问题

**Comment by yichya** [comment]
> 就是最新的commit[[53b4974](https://github.com/yichya/luci-app-xray/commit/53b49746d9f88faa25d40ff4624ab02a6a5be7f6)]，奇怪的是我一周之前也是这个commit是好用的，就是这几天编译的固件透明代理有问题

OpenWrt 呢

**Comment by dfldylan** [comment]
immortalwrt的最新commit[a4669fa7c3ebf10dd82c49ddcf8ff7811abc8d44]，勾选ipv6helper，软件包只添加luci-app-xray 和隔壁issue里的luci-i18n-xray-zh-cn

**Comment by yichya** [comment]
> [immortalwrt](https://github.com/immortalwrt/immortalwrt)的最新commit[a4669fa7c3ebf10dd82c49ddcf8ff7811abc8d44]，勾选ipv6helper

emmm，这得找 immortalwrt 那边，我这边官方 OpenWrt 是没问题的

**Comment by dfldylan** [comment]
可是我最近编译的[R4S](https://github.com/friendlyarm/friendlywrt)也是突然出现同样的问题。您说的官方openwrt没问题是最近编译的吗？

**Comment by yichya** [comment]
> 上面说的是x86虚拟机上的，另外我最近编译的[R4S](https://github.com/friendlyarm/friendlywrt)也是突然出现同样的问题。您说的官方openwrt没问题是最近编译的吗？

是啊。。。我自己用的 x86 软路由天天更新的

**Comment by dfldylan** [comment]
ok我去试试openwrt官方，回来再说

**Comment by dfldylan** [comment]
官方的依然有同样的问题，这次用的是GL-INET的AXT1800 ，就是官方的openwrt。同样的配置，7.13之前编译的固件就能透明代理，今天编译的固件就不行。
