### ISSUE TITLE
安装最新版后，无法上网。

### ISSUE THREAD

**Issue by jlzsss** [yichya/luci-app-xray#20]
安装完最新版后，无法上网。

**Comment by yichya** [comment]
system log 里面有报错吗，贴一下

**Comment by jlzsss** [comment]
安装时，报如下信息：
Installing luci-app-xray (8fc2d3b61fce1d7393910fe08873daef31e139e0-6) to root...
Configuring luci-app-xray.
/etc/rc.common: /etc/init.d/xray: line 8: extra_command: not found
/etc/rc.common: /etc/init.d/xray: line 8: extra_command: not found
transparent-proxy-rules[3743]: flush_rules firewall_include_file /var/etc/xray.include
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such process
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such process
transparent-proxy-rules[3743]: ipset_init
transparent-proxy-rules[3743]: gen_lan_host_ipset_entry
transparent-proxy-rules[3743]: default gateway check 10.14.248.1
transparent-proxy-rules[3743]: ipt_mangle tcp_local_port 1080 udp_local_port 1081
transparent-proxy-rules[3743]: gen_prerouting_rules
transparent-proxy-rules[3743]: ipt_mangle_output mark_number 255
transparent-proxy-rules[3743]: export_ipt_rules firewall_include_file /var/etc/xray.include
/usr/bin/lua: /usr/share/xray/gen_config.lua:5: attempt to call method 'get_first' (a nil value)
stack traceback:
        /usr/share/xray/gen_config.lua:5: in main chunk
        [C]: ?
system log 显示如下信息：
Mon Jan  4 13:50:41 2021 user.info transparent-proxy-rules[3743]: flush_rules firewall_include_file /var/etc/xray.include
Mon Jan  4 13:50:41 2021 user.info transparent-proxy-rules[3743]: ipset_init
Mon Jan  4 13:50:41 2021 user.info transparent-proxy-rules[3743]: gen_lan_host_ipset_entry
Mon Jan  4 13:50:41 2021 user.info transparent-proxy-rules[3743]: default gateway check 10.14.248.1
Mon Jan  4 13:50:41 2021 user.info transparent-proxy-rules[3743]: ipt_mangle tcp_local_port 1080 udp_local_port 1081
Mon Jan  4 13:50:41 2021 user.info transparent-proxy-rules[3743]: gen_prerouting_rules
Mon Jan  4 13:50:41 2021 user.info transparent-proxy-rules[3743]: ipt_mangle_output mark_number 255
Mon Jan  4 13:50:41 2021 user.info transparent-proxy-rules[3743]: export_ipt_rules firewall_include_file /var/etc/xray.include
Mon Jan  4 13:50:41 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Mon Jan  4 13:50:41 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Mon Jan  4 13:50:41 2021 daemon.notice procd: /etc/init.d/xray: /etc/rc.common: /etc/init.d/xray: line 8: extra_command: not found
Mon Jan  4 13:50:41 2021 daemon.info xray[3906]: Xray 1.2.0 (Xray, Penetrates Everything.) Custom (go1.15.5 linux/amd64)
Mon Jan  4 13:50:41 2021 daemon.info xray[3906]: A unified platform for anti-censorship.
Mon Jan  4 13:50:41 2021 daemon.info xray[3906]: Failed to start: main: failed to load config files: [/var/etc/xray.cfg024a8f.json] > main/json: failed to decode config: /var/etc/xray.cfg024a8f.json > infra/conf/serial: failed to read config file > EOF
Mon Jan  4 13:50:41 2021 daemon.info dnsmasq[3897]: Connected to system UBus

**Comment by yichya** [comment]
看起来是配置文件不对，luci 里面有界面了嘛

**Comment by jlzsss** [comment]
没有

**Comment by yichya** [comment]
https://github.com/yichya/luci-app-xray/blob/master/root/etc/config/xray 你把这个文件覆盖上去然后重启试试看？

**Comment by jlzsss** [comment]
我试过重启软路由，可是还是上不了网，而且打开openwrt界面没有配置界面，只有卸载luci-app-xray才能上网。

**Comment by yichya** [comment]
这个有可能是配置文件有些问题，方便的话把你的 /etc/config/xray 贴一下？如果是空的或者没有改过的话，把上面那个链接的内容填进去，然后重启，应该能看到配置界面

**Comment by jlzsss** [comment]
root@OpenWrt:/tmp/tmp# opkg install *.ipk --force-depends --force-overwrite
Installing luci-app-xray (8fc2d3b61fce1d7393910fe08873daef31e139e0-6) to root...
Configuring luci-app-xray.
/etc/rc.common: /etc/init.d/xray: line 8: extra_command: not found
/etc/rc.common: /etc/init.d/xray: line 8: extra_command: not found
transparent-proxy-rules[12580]: flush_rules firewall_include_file /var/etc/xray.include
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such process
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such process
transparent-proxy-rules[12580]: ipset_init
transparent-proxy-rules[12580]: gen_lan_host_ipset_entry
transparent-proxy-rules[12580]: default gateway check 10.76.32.1
transparent-proxy-rules[12580]: ipt_mangle tcp_local_port 1080 udp_local_port 1081
transparent-proxy-rules[12580]: gen_prerouting_rules
transparent-proxy-rules[12580]: ipt_mangle_output mark_number 255
transparent-proxy-rules[12580]: export_ipt_rules firewall_include_file /var/etc/xray.include
/usr/bin/lua: /usr/share/xray/gen_config.lua:5: attempt to call method 'get_first' (a nil value)
stack traceback:
        /usr/share/xray/gen_config.lua:5: in main chunk
        [C]: ?
root@OpenWrt:/tmp/tmp# /etc/init.d/xray stop
/etc/rc.common: /etc/init.d/xray: line 8: extra_command: not found
root@OpenWrt:/tmp/tmp# opkg remove luci-app-xray
Removing package luci-app-xray from root...
/etc/rc.common: /etc/init.d/xray: line 8: extra_command: not found
/etc/rc.common: /etc/init.d/xray: line 8: extra_command: not found
rm: can't remove '/tmp/dnsmasq.d/xray.conf': No such file or directory
Command failed: Not found
我重新安装过luci-app-xray，在 [/etc/config/xray里面的内容就是你发的链接上的内容，可是装上后，无法上网，在openwrt网页端也看不到配置界面。你前面说用的是最新的api，后来我编译用最新的api和19.07的api还有18.06的都看不到配置界面。
下面是 /etc/config/xray里的内容：
config general
	option xray_bin '/usr/bin/xray'
	option mark '255'
	option tproxy_port_tcp '1080'
	option tproxy_port_udp '1081'
	option socks_port '1082'
	option http_port '1083'
	option dns_port '5353'
	option fast_dns '114.114.114.114'
	option secure_dns '8.8.8.8'
	option default_dns '1.1.1.1'
	option transparent_proxy_enable '1'
	option wan_bp_list '/dev/null'
	option lan_target 'TP_SPEC_WAN_AC'
	option lan_ifaces 'br-lan'
	list wan_bp_ips '114.114.114.114'
	list wan_bp_ips '104.16.0.0/12'
	option xray_api '1'
	option main_server 'cfg024a8f'
	option tproxy_udp_server 'cfg034a8f'

config servers
	option security 'auto'
	option transport 'tcp'
	option tcp_guise 'none'
	option tls '0'
	option tests_enabled 'none'
	option protocol 'vless'
	option server_port '443'
	option password '00000000-0000-0000-0000-000000000000'
	option vless_security 'none'
	option vless_encryption 'none'
	option server 'example.org'
	option alias 'VLESS XTLS Splice Example'
	option vless_flow 'xtls-rprx-splice'
	option vless_tls 'xtls'
	option vless_xtls_host 'example.org'
	option vless_xtls_insecure '0'

config servers
	option password 'supersecret'
	option transport 'tcp'
	option tcp_guise 'none'
	option server 'example.org'
	option server_port '443'
	option protocol 'trojan'
	option alias 'Trojan Example'
	option trojan_flow 'none'
	option trojan_tls 'tls'
	option trojan_tls_host 'example.org'
	option trojan_tls_insecure '0'

**Comment by yichya** [comment]
配置看起来没问题，装上之后重启一下或者删掉 /tmp/luci-indexcache.*.json 之后能看到界面嘛

**Comment by jlzsss** [comment]
删除/tmp/luci-indexcache.json之后，好像还是不显示界面，正在编译最新版

**Comment by jlzsss** [comment]
好像还是不显示界面，这个链接 https://github.com/jlzsss/Custom-OpenWrt/releases/tag/2021.01.05-1455 是我编译的固件，您能否看下我编译的是否正确？

**Comment by yichya** [comment]
woc 这么大。。。我看看

**Comment by capxax** [comment]
我也有同样的问题
安装之后
没有luci界面
也不能上网
必须删除luci-app-xray之后 重启才能上网

**Comment by ttimasdf** [comment]
我编译了下好像没有问题，我是用SDK编译出ipk包，然后传进官方预编译的固件运行的，没啥问题。不建议自己编译完整固件。费时间、依赖不好更新、系统包含的依赖版本不可控。

不过我这运行也有一些小问题，原因还需要排查，xray一启动，从公网发起的连接就全断掉了，包括ssh，但内部向外访问，没问题。说不定和本issue一样都是iptables的问题。

**Comment by yichya** [comment]
> 不过我这运行也有一些小问题，原因还需要排查，xray一启动，从公网发起的连接就全断掉了，包括ssh，但内部向外访问，没问题。说不定和本issue一样都是iptables的问题。

这确实是个已知问题了，iptables tproxy 规则写的好像有些问题。。。大概一年多前我尝试换到 tproxy 的时候就这样了，也一直没时间查为啥

**Comment by tournet** [comment]
刚编译了OPENWRT官网21.02最新版+Luci-app-xray最新版，一样不能上外网，可以ping 通114.114.114.114，但连国内网站都无法访问。

**Comment by keyuxing** [comment]
> 刚编译了OPENWRT官网21.02最新版+Luci-app-xray最新版，一样不能上外网，可以ping 通114.114.114.114，但连国内网站都无法访问。

我也一样

**Comment by leizgt** [comment]
上传geosite.dat就好了

**Comment by yichya** [comment]
> 上传geosite.dat就好了

#80 增加了一些针对 geoip.dat geosite.dat 不存在的提示和启动脚本兼容，可以尝试一下
