### ISSUE TITLE
[Feature Request] proxySettings支持

### ISSUE THREAD

**Issue by iusearch** [yichya/luci-app-xray#200]
希望增加出口的proxySettings支持

**Comment by yichya** [comment]
近期会做。

**Comment by yichya** [comment]
#223 改动比之前预期的略大，不过大概没啥问题，可以先试试看

**Comment by iusearch** [comment]
看起来不错，就是我之前按用`luci-app-v2ray`比较喜欢自定义Routing，就是那个规则的gui化，然后逐个往下匹配，这个功能有打算复刻一下么？如果成了我可以加一个bounty给这个项目。

**Comment by yichya** [comment]
> 就是我之前按用`luci-app-v2ray`比较喜欢自定义Routing，就是那个规则的gui化，然后逐个往下匹配，这个功能有打算复刻一下么？

目前没有把 routing 搞得太复杂的打算，如果有这种需求的话考虑一下 v2raya 吧。
