### ISSUE TITLE
找不到kmod-nft-tproxy依赖

### ISSUE THREAD

**Issue by Tonkercke** [yichya/luci-app-xray#208]
找不到kmod-nft-tproxy依赖，不知在哪获取。

**Comment by yichya** [comment]
kmod-nft-tproxy 只在使用 firewall4 的时候需要。

如果你是 OpenWrt 21.02 或者更早版本的话，本身只能用 firewall3，可以忽略这个提示，不影响使用。

**Comment by Tonkercke** [comment]
也就是说可以在makefile文件中删除这个依赖项吧！我先试试。
