### ISSUE TITLE
请问luci-app-xray怎样设置才能让它支持ipv6?

### ISSUE THREAD

**Issue by mand-byte** [yichya/luci-app-xray#210]
昨天编译了22.03的正式版+luci-app-xray的master版
第一次用luci-app-xray不知道怎么设置
现在我在test-ipv6和ipv6-test上测,ipv4是vps的,而ipv6都是我本地的,
我希望都能显示vps的ip.
我的vps装了cf warp.
之前用passwall2 在test-ipv6上是可以正常显示warp 的ipv6
自定义设置里 加了UseIP也没用.不知道请问如何设置

**Comment by yichya** [comment]
目前还不支持 ipv6 透明代理，后续会做

**Comment by mand-byte** [comment]
> 目前还不支持 ipv6 透明代理，后续会做

希望早日实现。
另外能否把dns和inbound及outbound做成list node
用户自己添加并填参数，并用toggle来标记是否启用，save apply的时候再整合。虽然也能在自定义里重写，我觉得体验会更好。

**Comment by mand-byte** [comment]
当前版本还有个问题 防火墙设置的端口转发失效
关掉后才能开放端口
22.03的正式版+luci-app-xray的master版

**Comment by yichya** [comment]
> 另外能否把dns和inbound及outbound做成list node 用户自己添加并填参数，并用toggle来标记是否启用，save apply的时候再整合。虽然也能在自定义里重写，我觉得体验会更好。

这个整起来感觉太复杂了，会提高很多普通用户的使用成本，绝大多数用户没有那么多节点要做很复杂的逻辑

**Comment by yichya** [comment]
> 当前版本还有个问题 防火墙设置的端口转发失效 关掉后才能开放端口 22.03的正式版+luci-app-xray的master版

#194 现在只有 iptables 的，之后用 nftables 再做一下

**Comment by fuokgfw** [comment]
现在基本都是V2RAY XRAY之类的内核了，官网固件都是22.10.03了，开发者辛苦啦，希望能适配

**Comment by yukeiyang** [comment]
使用 luci-app-xray 到软路由，体验极致丝滑。

不过，IPv6 到目前似乎已经是一个实际的需求。

当不能透明代理 IPv6 时，复杂环境下某些开启了 IPv6 访问的网站的连接会变慢，因为目前主流协议似乎是优先解析 IPv6。

开发者辛苦了。

**Comment by yichya** [comment]
> 不过，IPv6 到目前似乎已经是一个实际的需求。

确实，所以会考虑，只是近期比较忙。。。可能就只做 nftables，不做 iptables 或者晚一些再做 nftables 的了。

> 当不能透明代理 IPv6 时，复杂环境下某些开启了 IPv6 访问的网站的连接会变慢，因为目前主流协议似乎是优先解析 IPv6。

这个如果用 Xray 的 DNS 的话倒是不重要，可以搞成不解析 AAAA 的

**Comment by yichya** [comment]
> 目前还不支持 ipv6 透明代理，后续会做

假期大概会整一下（希望有时间

**Comment by ttimasdf** [comment]
> 使用 luci-app-xray 到软路由，体验极致丝滑。
> 
> 不过，IPv6 到目前似乎已经是一个实际的需求。
> 
> 当不能透明代理 IPv6 时，复杂环境下某些开启了 IPv6 访问的网站的连接会变慢，因为目前主流协议似乎是优先解析 IPv6。
> 
> 开发者辛苦了。

目前 IPv6 好像没有解决啥实际问题，没有哪个网站开了 IPv6 会更快。所以我选择关了。
至少联通电信的宽带是这样。如果是校园网的话我就不清楚了。

除此之外，Windows 有 ipv4 优先于 ipv6 的选项 [Configure IPv6 for advanced users - Windows Server | Microsoft Learn](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows)
