### ISSUE TITLE
Provide prebuilt packages

### ISSUE THREAD

**Issue by poscat0x04** [yichya/luci-app-xray#212]
It would be nice if you could provide prebuilt .ipk packages for us to download.

**Comment by yuanjie1853** [comment]
https://github.com/yuanjie1853/luci-app-xray_build

**Comment by yichya** [comment]
I'll make changes on `Makefile` to support that in the following week

**Comment by WuTr3YZd** [comment]
I changed my username to protect privacy. This is the new link.

https://github.com/WuTr3YZd/luci-app-xray_build

**Comment by yichya** [comment]
> I changed my username to protect privacy. This is the new link.

I've deleted your previous comment

**Comment by WuTr3YZd** [comment]
https://github.com/WuTr3YZd/luci-app-xray_build

**Comment by ttimasdf** [comment]
[luci-app-xray/build.yml at custom · ttimasdf/luci-app-xray](https://github.com/ttimasdf/luci-app-xray/blob/custom/.github/workflows/build.yml)

**Comment by science2468** [comment]
我在本地编译完成，已经出包。我使用的环境是openwrt v22.03.3 平台x86-64。我安装成功，也正确显示中文，没有具体上节点测试。链接如下：[https://github.com/science2468/luci-i18n-xray-zh-cn/releases/tag/2.0-1](url) luci-app-xray出处：[https://github.com/yichya/luci-app-xray](url)；luci-i18n-xray-zh-cn出处：[https://github.com/xiechangan123/luci-i18n-xray-zh-cn](url)
