### ISSUE TITLE
请问 xray-geodata 的原始 github package 在哪里？

### ISSUE THREAD

**Issue by yukeiyang** [yichya/luci-app-xray#218]
xray-geodata 可在编译固件时打包并一同编译，未打包亦可在路由器上 opkg install xray-geodata 手工安装。我的问题是:

xray-geodata 之 domain list 的 github 原始维护源在哪里？

我希望加入到该维护团队中做些工作，偶尔可帮助更新域名 list 以帮助修复某些个站点无法加载的问题。

我知道 https://github.com/v2fly/domain-list-community ，但不知  xray-geodata 的原始出处是不是这个？

感谢开发者 @yichaya 在 luci-app-xray 上的付出。

**Comment by yichya** [comment]
[https://github.com/openwrt/packages/blob/master/net/v2ray-geodata/Makefile](https://github.com/openwrt/packages/blob/master/net/v2ray-geodata/Makefile)

**Comment by yukeiyang** [comment]
> https://github.com/openwrt/packages/blob/master/net/v2ray-geodata/Makefile

In this link, the  source code including this:

`define Download/geosite
  URL:=https://github.com/v2fly/domain-list-community/releases/download/$(GEOSITE_VER)/
  URL_FILE:=dlc.dat
  FILE:=$(GEOSITE_FILE)
  HASH:=8a69b68f02d422ab05f351772c871f367bf387fa78dc37c4f8c1e421a13540a6`

**so, the end is:**
https://github.com/v2fly/domain-list-community

**Comment by yukeiyang** [comment]
thank you.
