### ISSUE TITLE
 Failed to start: main: failed to load config files: [/var/etc/xray/config.json] > infra/conf/serial: failed to decode config: /var/etc/xray/config.json > infra/conf/serial: failed to read config file at line 1 char 1 > infra/conf: invalid DNS hosts > json: cannot unmarshal array into Go value of type map[string]*conf.HostAddress

### ISSUE THREAD

**Issue by hutozh** [yichya/luci-app-xray#233]
日志显示 Failed to start: main: failed to load config files: [/var/etc/xray/config.json] > infra/conf/serial: failed to decode config: /var/etc/xray/config.json > infra/conf/serial: failed to read config file at line 1 char 1 > infra/conf: invalid DNS hosts > json: cannot unmarshal array into Go value of type map[string]*conf.HostAddress
默认配置也不行，请问怎么排查问题？

**Comment by yichya** [comment]
贴一下 /etc/config/xray 并且注意去掉敏感信息

**Comment by hutozh** [comment]
config general
	option xray_bin '/usr/bin/xray'
	option mark '255'
	option tproxy_port_tcp '1080'
	option tproxy_port_udp '1081'
	option socks_port '1082'
	option http_port '1083'
	option dns_port '5300'
	option dns_count '3'
	option fast_dns '114.114.114.114'
	option secure_dns '8.8.8.8'
	option default_dns '1.1.1.1'
	list bypassed_domain_rules 'geosite:cn'
	list forwarded_domain_rules 'geosite:geolocation-!cn'
	list blocked_domain_rules 'geosite:category-ads'
	option wan_bp_list '/dev/null'
	option lan_target 'TP_SPEC_WAN_AC'
	option lan_ifaces 'br-lan'
	list wan_bp_ips '114.114.114.114'
	option xray_api '1'
	option main_server 'cfg024a8f'
	option tproxy_udp_server 'cfg034a8f'
	option routing_domain_strategy 'AsIs'
	option conn_idle '300'
	option loglevel 'warning'
	option handshake '4'
	option uplink_only '2'
	option downlink_only '5'
	option buffer_size '512'

config servers
	option security 'auto'
	option tls '0'
	option tests_enabled 'none'
	option protocol 'vless'
	option vless_security 'none'
	option vless_encryption 'none'
	option alias 'VLESS XTLS Splice Example'
	option server '******'
	option domain_strategy 'UseIP'
	option server_port '****'
	option password '*******'
	option vless_tls 'tls'
	option vless_tls_insecure '0'
	option transport 'ws'
	option ws_path '******'
	option dialer_proxy 'disabled'

config servers
	option password 'supersecret'
	option transport 'tcp'
	option tcp_guise 'none'
	option server 'example.org'
	option server_port '443'
	option protocol 'trojan'
	option alias 'Trojan Example'
	option trojan_flow 'none'
	option trojan_tls 'tls'
	option trojan_tls_host 'example.org'
	option trojan_tls_insecure '0'

**Comment by hutozh** [comment]
> 贴一下 /etc/config/xray 并且注意去掉敏感信息
看了一下，好像是缺一个geosite.dat文件，我是用imagebuilder做固件时直接添加的xray-geodata，不知道为什么会少一个文件。

**Comment by yichya** [comment]
看你贴的这个配置不应该有这个错误啊。

> 看了一下，好像是缺一个geosite.dat文件，我是用imagebuilder做固件时直接添加的xray-geodata，不知道为什么会少一个文件。

这个就更不应该了，你是哪个版本的 imagebuilder

**Comment by hutozh** [comment]
> 看你贴的这个配置不应该有这个错误啊。
> 
> > 看了一下，好像是缺一个geosite.dat文件，我是用imagebuilder做固件时直接添加的xray-geodata，不知道为什么会少一个文件。
> 
> 这个就更不应该了，你是哪个版本的 imagebuilder

openwrt 22.03，安装完是在v2ray文件夹里面，xray里面做了一个链接。我在官方软件源里面也没找到xray-geodata，只找到v2ray-geosite.dat和v2ray-geoip.dat

**Comment by yichya** [comment]
> openwrt 22.03，安装完是在v2ray文件夹里面，xray里面做了一个链接。我在官方软件源里面也没找到xray-geodata，只找到v2ray-geosite.dat和v2ray-geoip.dat

= = 这就很让人心烦了，我看看他们现在怎么整的

**Comment by hutozh** [comment]
> > openwrt 22.03，安装完是在v2ray文件夹里面，xray里面做了一个链接。我在官方软件源里面也没找到xray-geodata，只找到v2ray-geosite.dat和v2ray-geoip.dat
> 
> = = 这就很让人心烦了，我看看他们现在怎么整的

我刚才又看了一下，22.03.2是有xray-geodata的，是在
https://archive.openwrt.org/releases/22.03.2/packages/arm_cortex-a9_vfpv3-d16/packages/
官方软件源配置的是
https://downloads.openwrt.org/releases/22.03.2/packages/arm_cortex-a9_vfpv3-d16/packages/
不知道这两个有什么区别。
