### ISSUE TITLE
IPv6现在支持了吗？怎么设置？

### ISSUE THREAD

**Issue by 3xpert** [yichya/luci-app-xray#234]
下图的设置连不通呢
![IPv6的设置](https://user-images.githubusercontent.com/8335065/198755251-0d643174-35dd-4a03-9e0d-a969758e0e38.png)

**Comment by yichya** [comment]
还没做完。。。刚搬家，网络环境还没稳定下来，大概得下个月抽时间弄

**Comment by yichya** [comment]
This feature is added in v3.0.0
