### ISSUE TITLE
关于xray-core v1.6.2新增流控xtls-rprx-vision的设置

### ISSUE THREAD

**Issue by 3xpert** [yichya/luci-app-xray#236]
新发布的[Xray-core v1.6.2](https://github.com/XTLS/Xray-core/releases/tag/v1.6.2)中新增的流控xtls-rprx-vision，在[贴子](https://github.com/XTLS/Xray-core/pull/1235)中说是要客户、服务两端都要设，但在本项目中当stream security设成tls时，没有流控选项。

**Comment by yichya** [comment]
今天 1.6.2 才发布。。。别急，明天做

**Comment by 3xpert** [comment]
😄

**Comment by 3xpert** [comment]
👍

**Comment by hutozh** [comment]
> 今天 1.6.2 才发布。。。别急，明天做

能不能增加一个自定义选项，这样有新功能，可以临时用用。

**Comment by yichya** [comment]
> 能不能增加一个自定义选项，这样有新功能，可以临时用用。

有 Custom Configurations 的呀

**Comment by hutozh** [comment]
> > 能不能增加一个自定义选项，这样有新功能，可以临时用用。
> 
> 有 Custom Configurations 的呀

这个好像和我说的不一样。我随便写了一个效果是option custom_config 'ss=aa'，我想要的效果应该是option ss 'aa'。比如1.6.2新加的功能，我可以通过自定义配置填入"flow": "xtls-rprx-vision"来使用。这个自定义键，如果和已有的冲突，以自定优先。

还有，我重新编译了1.23，没有找到新增加的设置项在哪。

**Comment by 3xpert** [comment]
把stream security设成tls就有了

**Comment by hutozh** [comment]
> 把stream security设成tls就有了

我的还是没有，版本1.23.0-1

**Comment by yichya** [comment]
> 我的还是没有，版本1.23.0-1

自己清理一下前端缓存看看

**Comment by yichya** [comment]
> 这个好像和我说的不一样。我随便写了一个效果是option custom_config 'ss=aa'，我想要的效果应该是option ss 'aa'。比如1.6.2新加的功能，我可以通过自定义配置填入"flow": "xtls-rprx-vision"来使用。这个自定义键，如果和已有的冲突，以自定优先。

uci 没法描述复杂的嵌套，这个怕是真不好做

**Comment by hutozh** [comment]
> > > 能不能增加一个自定义选项，这样有新功能，可以临时用用。
> > 
> > 
> > 有 Custom Configurations 的呀
> 
> 这个好像和我说的不一样。我随便写了一个效果是option custom_config 'ss=aa'，我想要的效果应该是option ss 'aa'。比如1.6.2新加的功能，我可以通过自定义配置填入"flow": "xtls-rprx-vision"来使用。这个自定义键，如果和已有的冲突，以自定优先。
> 
> 还有，我重新编译了1.23，没有找到新增加的设置项在哪。



> > 这个好像和我说的不一样。我随便写了一个效果是option custom_config 'ss=aa'，我想要的效果应该是option ss 'aa'。比如1.6.2新加的功能，我可以通过自定义配置填入"flow": "xtls-rprx-vision"来使用。这个自定义键，如果和已有的冲突，以自定优先。
> 
> uci 没法描述复杂的嵌套，这个怕是真不好做

我看了那个说明，自定义这么写的，好像不行。
{
"outbounds": [
        {
            "settings": {
                "vnext": [
                    {
                         "users": [
                            {
                                "flow": "xtls-rprx-vision"
                            }
                        ]
                    }
                ]
            }
        }
    ]
}

**Comment by yichya** [comment]
显然不是这样用的。。。

自定义配置应该也是没办法满足【在某一个 outbound 里面加一个属性】这种需求的，还是等更新吧，一般不会太慢
