### ISSUE TITLE
问个关于imagebuilder编译的问题，可能不太相关，希望能够得到解答。

### ISSUE THREAD

**Issue by hutozh** [yichya/luci-app-xray#240]
我在编译最后的阶段，有个报错，好像不影响固件使用。

Finalizing root filesystem...
work/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/root-mvebu/etc/init.d/xray: line 8: /usr/share/xray/init.firewall: No such file or directory
.
.
.
.
./etc/init.d/xray: line 8: /usr/share/xray/init.firewall: No such file or directory
Enabling xray

**Comment by yichya** [comment]
这个大概是在编译的时候执行了 /etc/init.d/xray 但是因为里面 source 了一些特定文件，在编译的系统里面肯定没有这些文件，所以会有个提示，不碍事
