### ISSUE TITLE
萌新求教，编译报错

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [yichya/luci-app-xray#243]
下载好openwrt环境了，
git clone https://github.com/yichya/luci-app-xray 
把luci-app-xray克隆到openwrt/package/luci-app-xray
然后makemenu config，前两项选择x86-64，然后第三项选择generic
然后make package/luci-app-xray/compile V=s
太长了，只截取最后几行带有错误的地方。
求教大佬指点指点。

```
make[3]: Leaving directory '/workdir/openwrt/feeds/luci/modules/luci-base/src'
touch /workdir/openwrt/build_dir/hostpkg/luasrcdiet-1.0.0/.built
install -d -m0755 /workdir/openwrt/staging_dir/hostpkg/bin
install -d -m0755 /workdir/openwrt/staging_dir/hostpkg/lib/lua/5.1
install -m0755 src/po2lmo /workdir/openwrt/staging_dir/hostpkg/bin/po2lmo
install -m0755 src/jsmin /workdir/openwrt/staging_dir/hostpkg/bin/jsmin
install -m0755 /workdir/openwrt/build_dir/hostpkg/luasrcdiet-1.0.0/bin/luasrcdiet /workdir/openwrt/staging_dir/hostpkg/bin/luasrcdiet
cp -fpR /workdir/openwrt/build_dir/hostpkg/luasrcdiet-1.0.0/luasrcdiet /workdir/openwrt/staging_dir/hostpkg/lib/lua/5.1/
mkdir -p /workdir/openwrt/staging_dir/hostpkg/stamp
touch /workdir/openwrt/build_dir/hostpkg/luasrcdiet-1.0.0/.built
touch /workdir/openwrt/staging_dir/hostpkg/stamp/.luci-base_installed
make[2]: Leaving directory '/workdir/openwrt/feeds/luci/modules/luci-base'
time: package/feeds/luci/luci-base/host-compile#1.92#0.69#2.43
make[2]: Entering directory '/workdir/openwrt/package/libs/toolchain'
rm -rf /workdir/openwrt/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed /workdir/openwrt/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
mkdir -p /workdir/openwrt/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
install -d -m0755 /workdir/openwrt/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib /workdir/openwrt/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/usr/bin
cp -fpR /workdir/openwrt/staging_dir/toolchain-x86_64_gcc-7.5.0_musl/lib/ld-musl-*.so* /workdir/openwrt/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib/
cp: cannot stat '/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-7.5.0_musl/lib/ld-musl-*.so*': No such file or directory
make[2]: *** [Makefile:624: /workdir/openwrt/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory '/workdir/openwrt/package/libs/toolchain'
time: package/libs/toolchain/compile#0.12#0.03#0.15
make[1]: *** [package/Makefile:113: package/libs/toolchain/compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:227: package/luci-app-xray/compile] Error 2
```

**Comment by yukeiyang** [comment]
容易出错的地方：
1. 注意不要用 root 编译
2. 注意是否有安装完整依赖

sudo apt-get install git-core build-essential libssl-dev libncurses5-dev unzip gawk asciidoc binutils bzip2  gettext git libz-dev patch python3.5 unzip subversion mercurial ccache sudo rsync screen -y

**Comment by AP0rPi7uQ9** [comment]
> 

@yukeiyang 
你好，帅哥，想问一下，luci-app-xray需要xray-core依赖的话，我可以不安装xray-core先编译luci-app-xray吗？我想到时候分开编译成xray-core.ipk和luci-app-xray.ipk安装。

**Comment by yukeiyang** [comment]
1. 我过去都是一同编译，没试过分开。
2. 再说，luci-app-xray 需要 xraycore 依赖，也不应该分开。
3. 至于你说想分别取得 Xraycore 和 luci-app-xray 各自的 ipk, 一同编译时都会生成各自的 ipk 到目录中。你选出来就好了。

**Comment by yichya** [comment]
> 把luci-app-xray克隆到openwrt/package/luci-app-xray

clone 的位置建议是在 package/extra（如果没有的话就 mkdir -p），主要是因为其他的地方我没试过行不行

> ```
> cp: cannot stat '/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-7.5.0_musl/lib/ld-musl-*.so*': No such file or directory
> make[2]: *** [Makefile:624: /workdir/openwrt/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed] Error 1
> make[2]: Leaving directory '/workdir/openwrt/package/libs/toolchain'
> time: package/libs/toolchain/compile#0.12#0.03#0.15
> make[1]: *** [package/Makefile:113: package/libs/toolchain/compile] Error 2
> ```

这个报错完全都还没到 luci-app-xray 上面，是在 toolchain 的地方就报错了，这说明环境很可能有问题（比如上面这位大佬说的是不是用 root 编译了）

分开编译的事情上面这位大佬的描述是没问题的。

**Comment by AP0rPi7uQ9** [comment]
我用的是云编译，失败了好几次，我再研究研究

**Comment by AP0rPi7uQ9** [comment]
不过非常感谢两位大佬的赐教

**Comment by yukeiyang** [comment]
anyway, I can paste my proccess for compiling this below, you can referrence it.
just wait 3 mins.

**Comment by yukeiyang** [comment]
- 安装依赖
$ apt update && apt upgrade -y
$ sudo apt-get install git-core build-essential libssl-dev libncurses5-dev unzip gawk asciidoc binutils bzip2  gettext git libz-dev patch python3.5 unzip subversion mercurial ccache sudo rsync screen -y\

- 新建普通用户用以编译 (譬如新建 plus 用户)
$ sudo adduser plus
$ adduser plus sudo
$ chmod 0440 /etc/sudoers
$ reboot

- x86-64 固件环境准备
$ su - plus		//切换到普通用户用以编译
$ wget https://downloads.openwrt.org/releases/22.03.2/targets/x86/64/openwrt-sdk-22.03.2-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
$ tar -xf openwrt-sdk-*-x86_64.tar.xz
$ sudo apt-get update

- 编译 luci-app-xray
$ cd openwrt-sdk-*Linux-x86_64
$ git clone https://github.com/yichya/luci-app-xray.git package/luci-app-xray
$ ./scripts/feeds update -a && ./scripts/feeds install -a
$ make menuconfig
// 过程中选择要编译的包 Extra -> 
// M 选中; * 代表编译中 include
// 然后 Save， 命名保持默认 .config 名称； Exit 退出

-- $ make package/luci-app-xray/compile -j1 V=s 
// 生成 ipk 文件目录 | /home/plus/openwrt-sdk-*/bin/packages/x86_64/base

**Comment by yukeiyang** [comment]
It's very simple. If you compile it on Ubuntu 22.04.
Just only these steps.

**Comment by yukeiyang** [comment]
or, you can use the firmware that compiled by me.
Integrated luci-app-xray, can be used for xray. If you are using x86-64 router, you can find the firmware in this project.
It's clean, and only integrates these more 6 pakakges: luci, irqbalance, xray-core, geoip, geosite, luci-app-xray.
Already tested on x86-64 router, and works fine.

**Comment by AP0rPi7uQ9** [comment]
成功了！非常感谢。有时间我做成github action，到时候与各位一起分享。
不过还有两个疑问：
1.个人感觉编译最难的是依赖，大佬您这个依赖是一个个试出来的？还是哪里有相关说明需要安装哪些依赖呢？
2.再问个小白问题，make menuconfig的时候，默认是全选的，我新建一个.config文件，只有如下内容，编译之后好像又会报错。如果默认全选包，倒是编译通过了。
```
CONFIG_PACKAGE_luci-app-xray=m

#
# luci-app-xray Configuration
#
CONFIG_PACKAGE_XRAY_INCLUDE_CLOUDFLARE_ORIGIN_ROOT_CA=y
CONFIG_PACKAGE_XRAY_INFINITE_RETRY_ON_STARTUP=y
CONFIG_PACKAGE_XRAY_RLIMIT_NOFILE_LARGE=y
CONFIG_PACKAGE_XRAY_RLIMIT_DATA_UNLIMITED=y
```
是否有其他更好的方式来取消没必要的包？

**Comment by yukeiyang** [comment]
> 1.个人感觉编译最难的是依赖，大佬您这个依赖是一个个试出来的？还是哪里有相关说明需要安装哪些依赖呢？

如果没记错的话，部分依赖的确是编译报错以后，一一添加的。
