### ISSUE TITLE
需求： fw的透明代理规则中，配置需转发流量的端口

### ISSUE THREAD

**Issue by lialosiu** [yichya/luci-app-xray#244]
看了下现在的防火墙规则好像是会将所有端口的流量都转发给了xray，但实际使用上很多时候只需要转发基本的80、443等常用端口，远程桌面的3389之类的极少会走转发，感觉这里还是需要个配置项的

虽然也能写custom options在xray上给直接freedom出来凑合，但是感觉端口判定还是走fw好点吧（

**Comment by yukeiyang** [comment]
Same issue in my end. 3389 port by Remote Desktop Protocol, if pass by xray, Will very very slow.

**Comment by yichya** [comment]
这个其实最简单的办法是在 firewall 的配置里面提前在 mangle 表上把不需要转发的端口排除掉，之前 fw3 的时候可以直接在 luci 里面写自定义防火墙配置，但 fw4 就需要自己写一个 include 文件了。

这个我考虑一下如何支持比较简单

**Comment by keyuxing** [comment]
> 这个其实最简单的办法是在 firewall 的配置里面提前在 mangle 表上把不需要转发的端口排除掉

可以给个example吗，比如只代理某个端口或者不代理某个端口。不太会写firewall配置🥹

**Comment by hqvv** [comment]
> > 这个其实最简单的办法是在 firewall 的配置里面提前在 mangle 表上把不需要转发的端口排除掉
> 
> 可以给个fw4的example吗，比如只代理某个端口或者不代理某个端口。不太会写firewall配置🥹

我也有这个需求，需要一个例子，具体如何操作

**Comment by lialosiu** [comment]
> > > 这个其实最简单的办法是在 firewall 的配置里面提前在 mangle 表上把不需要转发的端口排除掉
> > 
> > 
> > 可以给个fw4的example吗，比如只代理某个端口或者不代理某个端口。不太会写firewall配置🥹
> 
> 我也有这个需求，需要一个例子，具体如何操作

#299 我提交了个PR，我自己本地使用正常，可以参考下

**Comment by lialosiu** [comment]
Closed: #299
