### ISSUE TITLE
x ray seems online but local ip seen 

### ISSUE THREAD

**Issue by padima2** [yichya/luci-app-xray#248]
hi @yichya 
i was able to compile an ipk then build a firmware integrated with the ipk and successfully installed it
unfortunately i was having this continously:
`Sun Nov 27 20:16:52 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: mozilla.cloudflare-dns.com

Sun Nov 27 20:16:55 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: reserve-5a846.firebaseio.com

Sun Nov 27 20:16:57 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: dns.google.com

Sun Nov 27 20:16:59 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: mozilla.cloudflare-dns.com

Sun Nov 27 20:16:59 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: td.telegram.org

Sun Nov 27 20:17:04 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: reserve-5a846.firebaseio.com

Sun Nov 27 20:17:06 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: dns.google.com

Sun Nov 27 20:17:08 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: mozilla.cloudflare-dns.com

Sun Nov 27 20:17:11 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: reserve-5a846.firebaseio.com

Sun Nov 27 20:17:14 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: dns.google.com

Sun Nov 27 20:17:16 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: mozilla.cloudflare-dns.com

Sun Nov 27 20:17:19 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: reserve-5a846.firebaseio.com

Sun Nov 27 20:17:19 2022 daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: td.telegram.org`

so i have unchecked the binding thing in dnsmasq

then there is no errors in the log but still my local ip is visible and my traffic is not going thru.
so what is wrong with my setting?
i ve noticed this as well:
`Sun Nov 27 20:45:45 2022 user.info transparent-proxy-ipset[16385]: default gateway available at 192.168.14.5`

i have never added this ip in my config ,where is that coming from?

**Comment by yichya** [comment]
it seems your DNS settings for Xray is incorrect. Try setting them according to your location.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/3683052/204879390-ef8520a3-01ca-4ffc-b584-d3bb01faa959.png">

> i have never added this ip in my config ,where is that coming from?

As it said this IP is your default gateway which means all outgoing traffic go through there.
