### ISSUE TITLE
how to config routing via domain:cn

### ISSUE THREAD

**Issue by aminmazi** [yichya/luci-app-xray#250]
Hello guys
first of all, thank you for such a great tool!

I have a problem to config routing to bypass special domains.
here is my config object that works locally, but when I want to config my openwrt to bypass `*.ir` domains, it seems `luci-app-xray` doesn't support it 🤔 

```
{
                "type": "field",
                "outboundTag": "direct",
                "domain": [
                    "domain:ir",
                    "geosite:private"
                ]
}
```
is there any way I can use the above config for openwrt?

**Comment by yichya** [comment]
First, enable sniffing

<img width="923" alt="image" src="https://user-images.githubusercontent.com/3683052/204878686-a08452c5-5629-4ae8-a2fd-6362c6780ee2.png">


Then add your domain rules under "Bypassed domain rules"

<img width="809" alt="image" src="https://user-images.githubusercontent.com/3683052/204878602-d5d69469-c1cc-4112-a24a-792ff676a820.png">

**Comment by aminmazi** [comment]
Yeah that worked !
Thanks a lot 🙏
