### ISSUE TITLE
功能需求：DNS 设置中可否设置多个dns

### ISSUE THREAD

**Issue by SasamiMasakiJurai** [yichya/luci-app-xray#251]
主要是近期使用中发现，

默认使用8888时候，

经常会被阻断，

报错如下：

app/dns: UDP:8.8.8.8:53 cannot find the pending request

而更换其他dns后情况会在一段时间内改善。

但较长时间后，

又会被阻断。

因此，

可否设置多个dns，

在一个被报错后，

自动替换为第二个乃至第三个等，

实现轮换使用。

**Comment by yukeiyang** [comment]
公共 dns 始终各种各样的问题，我长期试验的结果是，最好自配一台专门的私有 DNS over https 服务器自用。

**Comment by yukeiyang** [comment]
Windows 平台已支持配置 dns over https, Chrome 也支持。Android 及 IOS 及 Apple TV 也都有方法配置 DoH

**Comment by SasamiMasakiJurai** [comment]
> 公共 dns 始终各种各样的问题，我长期试验的结果是，最好自配一台专门的私有 dns over https 服务器自用。

不能直接在dns那列直接填入DOH的DNS吗？

例如

https://dns.google/dns-query

https://cloudflare-dns.com/dns-query

**Comment by yukeiyang** [comment]
As I know, 作者似乎已经把支持 dns over https 加入到了开发日程，目前还不支持在 luci-app-xray 中填入 DoH address.

**Comment by yukeiyang** [comment]
当然，你这个需求是真实存在的。一般而言，DNS 有 failover 会更可靠。

但就我使用自配私有 DoH Server 来看，2 年几乎没遇到需要 failover 备援的时候。

原因在于，我自配的 DoH Server 选用了 Google Cloud 香港节点，Google Cloud 出问题的几率无限接近与零。

所以，对 DoH 而言，靠谱是最最重要的。

**Comment by SasamiMasakiJurai** [comment]
> 当然，你这个需求是真实存在的。一般而言，DNS 有 failover 会更可靠。
> 
> 但就我使用自配私有 DoH Server 来看，2 年多压根没遇到需要 failover 备援的时候。
> 
> 原因在于，我自配的 DoH Server 选用了 Google Cloud 香港节点，Google Cloud 出问题的几率，无限接近于零。

嗯，

有跳板确实方便，

不过个人还是觉得链路越短越好。

目前先在浏览器里面设置了doh，

后续看官方更新进度吧，

我先把话题关了。
