### ISSUE TITLE
Not working when transparent proxy is turned on.

### ISSUE THREAD

**Issue by hawshemi** [yichya/luci-app-xray#253]
I have a 4G dongle connected to the USB of AR750S running OpenWRT 22.03.
I installed xraycore and luci-app-xray latest version.

When the transparent proxy is turned off, the system works with the 4G IP address (Iran). But when I turn on the TProxy, no webpage will open; nothing is connected. See these screenshots.

![router](https://user-images.githubusercontent.com/16742123/208250772-fc36bce2-e23a-4bde-8cc9-a25214157e79.jpg)
![log](https://user-images.githubusercontent.com/16742123/208250775-ca5f1345-8718-48c3-ac1d-71e1bc9e31f3.jpg)
![1](https://user-images.githubusercontent.com/16742123/208250818-c8f8334a-00bf-4f55-828f-4172ea1b6d93.jpg)
![2](https://user-images.githubusercontent.com/16742123/208250822-7aff6dc3-75c9-45f5-8fd0-3160995c1b26.jpg)

I dunno what is wrong. I followed all the docs, and my vLess server is connecting on other devices.

**Comment by hawshemi** [comment]
I saw this : https://github.com/yichya/luci-app-xray/issues/248

But nothing is changed.
I change the CN to IR but no chance.

I think there is something wrong.
could it be the CPU or RAM bottlenecking?

**Comment by yichya** [comment]
According to the log you've posted, Xray seems not starting at all. That could be due to hardware bottlenecks and / or incorrect Xray binary file. 

Please first paste the output of `ps` command (LuCI status - processes is also okay)

<img width="974" alt="image" src="https://user-images.githubusercontent.com/3683052/208253989-1e9dabf2-c3b5-46b0-93db-9c40334de61d.png">

Then try manually run Xray itself from command line for further diagnostic:

1. save configuration files from `/var/etc/xray`, for example put to `/root/xray`
2. stop luci-app-xray by using command `service xray stop`
3. start Xray itself with the configuration file backed up above, by using command `xray run -confdir /root/xray`
4. wait for about a minute and post output here

**Comment by hawshemi** [comment]
This is the `ps` : 

![ps](https://user-images.githubusercontent.com/16742123/208254517-95d39826-bca4-47c2-acd8-3f90b323f678.jpg)


Tried the steps, but when it says core: x-ray started, it's kinda stuck and not doing anything for about 10 mins.

![ps2](https://user-images.githubusercontent.com/16742123/208255587-599acf2f-f8f3-4f83-bee5-d8707d9e54ea.jpg)

**Comment by yichya** [comment]
> This is the `ps` :
> 
> ![ps](https://user-images.githubusercontent.com/16742123/208254517-95d39826-bca4-47c2-acd8-3f90b323f678.jpg)

Try the SOCKS5 or HTTP proxy provided by luci-app-xray then. Do they work when you start luci-app-xray normally?

![image](https://user-images.githubusercontent.com/3683052/208364453-6c51e56d-e749-4fe0-b18b-10e825eeff1d.png)

**Comment by hawshemi** [comment]
How can I check or use that?

<img width="738" alt="px" src="https://user-images.githubusercontent.com/16742123/208373515-6b7abcbc-d2e4-4e5e-8f0e-dee543b0bd73.png">

**Comment by yichya** [comment]
> How can I check or use that?

Use something like curl and check the IP address returned

`env http_proxy=socks5://192.168.13.2:1082 curl --verbose checkip.dyndns.com`

**Comment by hawshemi** [comment]
ok I changed it to `br-lan`.

I ran the `curl` with `env,` but it returned with error `(28) Failed to connect to 192.168.13.2 port 1082 after 133355 ms: Error
`. 

When I run it without `env` and just `curl --verbose checkip.dyndns.com`, I get back my real IP.


Let me clarify a bit:
I have a 4G dongle attached to the USB with the Ip address: 192.168.13.1
The AR750S has 192.168.21.1
I changed their IP for conflicting reasons.

**Comment by yichya** [comment]
> I ran the `curl` with `env`, but it returned with error `(28) Failed to connect to 192.168.13.2 port 1082 after 133355 ms: Error `.

That may seem like some firewall problem but I'm not 100% sure so please help with more details:

1. You're using latest version of luci-app-xray with firewall4 but there seems to be something wrong. Paste complete output of `nft list ruleset` here.
2. Try running the previous `curl` command on your router and change IP address to `127.0.0.1`
3. Try increasing loglevel of Xray and see if there are anything in system log.

![image](https://user-images.githubusercontent.com/3683052/208399066-88696a8a-ded4-450d-a6ba-2dea2e199893.png)

**Comment by hawshemi** [comment]
`nft list ruleset` :

`
root@OpenWrt:~# nft list ruleset
table inet fw4 {
        set tp_spec_def_gw {
                type ipv4_addr
                elements = { 192.168.13.2 }
        }

        chain input {
                type filter hook input priority filter; policy accept;
                iifname "lo" accept comment "!fw4: Accept traffic from loopback"
                ct state established,related accept comment "!fw4: Allow inbound established and related flows"
                tcp flags syn / fin,syn,rst,ack jump syn_flood comment "!fw4: Rate limit TCP syn packets"
                iifname "br-lan" jump input_lan comment "!fw4: Handle lan IPv4/IPv6 input traffic"
                iifname { "eth0.2", "usb0" } jump input_wan comment "!fw4: Handle wan IPv4/IPv6 input traffic"
        }

        chain forward {
                type filter hook forward priority filter; policy drop;
                ct state established,related accept comment "!fw4: Allow forwarded established and related flows"
                iifname "br-lan" jump forward_lan comment "!fw4: Handle lan IPv4/IPv6 forward traffic"
                iifname { "eth0.2", "usb0" } jump forward_wan comment "!fw4: Handle wan IPv4/IPv6 forward traffic"
                jump handle_reject
        }

        chain output {
                type filter hook output priority filter; policy accept;
                oifname "lo" accept comment "!fw4: Accept traffic towards loopback"
                ct state established,related accept comment "!fw4: Allow outbound established and related flows"
                oifname "br-lan" jump output_lan comment "!fw4: Handle lan IPv4/IPv6 output traffic"
                oifname { "eth0.2", "usb0" } jump output_wan comment "!fw4: Handle wan IPv4/IPv6 output traffic"
        }

        chain prerouting {
                type filter hook prerouting priority filter; policy accept;
                iifname "br-lan" jump helper_lan comment "!fw4: Handle lan IPv4/IPv6 helper assignment"
        }

        chain handle_reject {
                meta l4proto tcp reject with tcp reset comment "!fw4: Reject TCP traffic"
                reject comment "!fw4: Reject any other traffic"
        }

        chain syn_flood {
                limit rate 25/second burst 50 packets return comment "!fw4: Accept SYN packets below rate-limit"
                drop comment "!fw4: Drop excess packets"
        }

        chain input_lan {
                jump accept_from_lan
        }

        chain output_lan {
                jump accept_to_lan
        }

        chain forward_lan {
                jump accept_to_wan comment "!fw4: Accept lan to wan forwarding"
                jump accept_to_lan
        }

        chain helper_lan {
        }

        chain accept_from_lan {
                iifname "br-lan" counter packets 156 bytes 11840 accept comment "!fw4: accept lan IPv4/IPv6 traffic"
        }

        chain accept_to_lan {
                oifname "br-lan" counter packets 3 bytes 1044 accept comment "!fw4: accept lan IPv4/IPv6 traffic"
        }

        chain input_wan {
                meta nfproto ipv4 udp dport 68 counter packets 0 bytes 0 accept comment "!fw4: Allow-DHCP-Renew"
                icmp type echo-request counter packets 0 bytes 0 accept comment "!fw4: Allow-Ping"
                meta nfproto ipv4 meta l4proto igmp counter packets 0 bytes 0 accept comment "!fw4: Allow-IGMP"
                meta nfproto ipv6 udp dport 546 counter packets 0 bytes 0 accept comment "!fw4: Allow-DHCPv6"
                ip6 saddr fe80::/10 icmpv6 type . icmpv6 code { mld-listener-query . no-route, mld-listener-report . no-route, mld-listener-done . no-route, mld2-listener-report . no-route } counter packets 0 bytes 0 accept comment "!fw4: Allow-MLD"
                icmpv6 type { destination-unreachable, time-exceeded, echo-request, echo-reply, nd-router-solicit, nd-router-advert } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Input"
                icmpv6 type . icmpv6 code { packet-too-big . no-route, parameter-problem . no-route, parameter-problem . admin-prohibited, nd-neighbor-solicit . no-route, nd-neighbor-advert . no-route } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Input"
                jump reject_from_wan
        }

        chain output_wan {
                jump accept_to_wan
        }

        chain forward_wan {
                icmpv6 type { destination-unreachable, time-exceeded, echo-request, echo-reply } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Forward"
                icmpv6 type . icmpv6 code { packet-too-big . no-route, parameter-problem . no-route, parameter-problem . admin-prohibited } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Forward"
                meta l4proto esp counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Allow-IPSec-ESP"
                udp dport 500 counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Allow-ISAKMP"
                jump reject_to_wan
        }

        chain accept_to_wan {
                oifname { "eth0.2", "usb0" } counter packets 490 bytes 48252 accept comment "!fw4: accept wan IPv4/IPv6 traffic"
        }

        chain reject_from_wan {
                iifname { "eth0.2", "usb0" } counter packets 0 bytes 0 jump handle_reject comment "!fw4: reject wan IPv4/IPv6 traffic"
        }

        chain reject_to_wan {
                oifname { "eth0.2", "usb0" } counter packets 0 bytes 0 jump handle_reject comment "!fw4: reject wan IPv4/IPv6 traffic"
        }

        chain dstnat {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain srcnat {
                type nat hook postrouting priority srcnat; policy accept;
                oifname { "eth0.2", "usb0" } jump srcnat_wan comment "!fw4: Handle wan IPv4/IPv6 srcnat traffic"
        }

        chain srcnat_wan {
                meta nfproto ipv4 masquerade comment "!fw4: Masquerade IPv4 wan traffic"
        }

        chain raw_prerouting {
                type filter hook prerouting priority raw; policy accept;
        }

        chain raw_output {
                type filter hook output priority raw; policy accept;
        }

        chain mangle_prerouting {
                type filter hook prerouting priority mangle; policy accept;
        }

        chain mangle_postrouting {
                type filter hook postrouting priority mangle; policy accept;
        }

        chain mangle_input {
                type filter hook input priority mangle; policy accept;
        }

        chain mangle_output {
                type route hook output priority mangle; policy accept;
        }

        chain mangle_forward {
                type filter hook forward priority mangle; policy accept;
                iifname { "eth0.2", "usb0" } tcp flags syn tcp option maxseg size set rt mtu comment "!fw4: Zone wan IPv4/IPv6 ingress MTU fixing"
                oifname { "eth0.2", "usb0" } tcp flags syn tcp option maxseg size set rt mtu comment "!fw4: Zone wan IPv4/IPv6 egress MTU fixing"
        }
}
`

I restarted the router, and the command `env http_proxy=socks5://192.168.13.2:1082 curl --verbose checkip.dyndns.com` returned the proxied IP after 5 seconds.

**Comment by ttimasdf** [comment]
seems that nftables rules are not added to your firewall. You could diagnose by executing the followings

```
/etc/init.d/xray stop
/etc/init.d/xray start
fw4 check
```

check whether `/var/etc/xray/firewall_include.nft` file exist after service started. if so, `fw4 check` will show the actual cause. You can start from here.

**Comment by hawshemi** [comment]
<img width="540" alt="fw" src="https://user-images.githubusercontent.com/16742123/209434178-084f5b46-0c41-4bdf-aa48-f6dc94efa45b.png">

No. in the /var/etc/xray/ directory there is only config.json file and nothing else.

**Comment by yichya** [comment]
Please check if these 2 files exist in /usr/share/xray. You may have installed incorrect version of luci-app-xray. 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/3683052/209463577-89eb914f-6d2c-42d2-8b6c-cc6218eb7119.png">

**Comment by hawshemi** [comment]
`/usr/share/xray/`

![image](https://user-images.githubusercontent.com/16742123/209463948-57607c23-4ae5-40eb-8dca-31bd872d8739.png)

**Comment by yichya** [comment]
Try running `utpl /usr/share/xray/firewall_include.ut` and post output here

**Comment by hawshemi** [comment]
```
BusyBox v1.35.0 (2022-12-22 12:20:39 UTC) built-in shell (ash)
OpenWrt 22.03.2, r19803-9a599fee93
 -----------------------------------------------------
root@OpenWrt:~# utpl /usr/share/xray/firewall_include.ut
    set tp_spec_src_ac {
        type ether_addr
        size 65536
    }

    set tp_spec_src_bp {
        type ether_addr
        size 65536
    }

    set tp_spec_src_fw {
        type ether_addr
        size 65536
    }

    set tp_spec_dst_sp {
        type ipv4_addr
        size 65536
        flags interval
        elements = { 0.0.0.0/8, 10.0.0.0/8,
                 100.64.0.0/10, 127.0.0.0/8,
                 169.254.0.0/16, 172.16.0.0/12,
                 192.0.0.0/24, 192.31.196.0/24,
                 192.52.193.0/24, 192.88.99.0/24,
                 192.168.0.0/16, 192.175.48.0/24,
                 224.0.0.0-255.255.255.255 }
    }

    set tp_spec_dst_bp {
        type ipv4_addr
        size 65536
        flags interval
        elements = { 114.114.114.114 }
    }

    set tp_spec_dst_fw {
        type ipv4_addr
        size 65536
        flags interval
        elements = { 8.8.8.8 }
    }

    set tp_spec_def_gw {
        type ipv4_addr
        size 65536
        flags interval
    }

    chain xray_prerouting {
        type filter hook prerouting priority filter; policy accept;
        meta mark 0x000000fc goto tp_spec_wan_ac
        iifname "br-lan" goto tp_spec_lan_dg
    }

    chain xray_output {
        type route hook output priority filter; policy accept;
        goto tp_spec_wan_dg
    }

    chain tp_spec_lan_ac {
        ether saddr @tp_spec_src_bp return
        ether saddr @tp_spec_src_fw goto tp_spec_wan_fw
        ether saddr @tp_spec_src_ac goto tp_spec_wan_ac
        goto tp_spec_wan_ac
    }

    chain tp_spec_lan_dg {
        ip daddr @tp_spec_dst_fw goto tp_spec_lan_re
        ip daddr @tp_spec_dst_sp return
        ip daddr @tp_spec_dst_bp return
        ip daddr @tp_spec_def_gw return
        goto tp_spec_lan_re
    }

    chain tp_spec_lan_re {
        meta l4proto { tcp, udp } goto tp_spec_lan_ac
    }

    chain tp_spec_wan_ac {
        ip daddr @tp_spec_dst_fw goto tp_spec_wan_fw
        ip daddr @tp_spec_dst_bp return
        goto tp_spec_wan_fw
    }

    chain tp_spec_wan_dg {
        meta mark 0x000000ff return
        ip daddr @tp_spec_dst_fw goto tp_spec_wan_re
        ip daddr @tp_spec_dst_sp return
        ip daddr @tp_spec_dst_bp return
        ip daddr @tp_spec_def_gw return
        goto tp_spec_wan_re
    }

    chain tp_spec_wan_re {
        meta l4proto { tcp, udp } meta mark set 0x000000fc
    }

    chain tp_spec_wan_fw {
        meta l4proto tcp meta mark set 0x000000fb tproxy ip to 0.0.0.0:1080 accept
        meta l4proto udp meta mark set 0x000000fb tproxy ip to 0.0.0.0:1081 accept
    }
root@OpenWrt:~#
```

**Comment by yichya** [comment]
That seems nothing wrong there...

Try `service xray restart` and post `nft list ruleset` again

**Comment by hawshemi** [comment]
<img width="595" alt="restart" src="https://user-images.githubusercontent.com/16742123/209471428-0cda6dba-f557-41a2-8224-e8ef0bd562e2.png">

```

root@OpenWrt:~# nft list ruleset
table inet fw4 {
        set tp_spec_def_gw {
                type ipv4_addr
                elements = { 192.168.13.2 }
        }

        chain input {
                type filter hook input priority filter; policy accept;
                iifname "lo" accept comment "!fw4: Accept traffic from loopback"
                ct state established,related accept comment "!fw4: Allow inbound established and related flows"
                tcp flags syn / fin,syn,rst,ack jump syn_flood comment "!fw4: Rate limit TCP syn packets"
                iifname "br-lan" jump input_lan comment "!fw4: Handle lan IPv4/IPv6 input traffic"
                iifname { "eth0.2", "usb0" } jump input_wan comment "!fw4: Handle wan IPv4/IPv6 input traffic"
        }

        chain forward {
                type filter hook forward priority filter; policy drop;
                ct state established,related accept comment "!fw4: Allow forwarded established and related flows"
                iifname "br-lan" jump forward_lan comment "!fw4: Handle lan IPv4/IPv6 forward traffic"
                iifname { "eth0.2", "usb0" } jump forward_wan comment "!fw4: Handle wan IPv4/IPv6 forward traffic"
                jump handle_reject
        }

        chain output {
                type filter hook output priority filter; policy accept;
                oifname "lo" accept comment "!fw4: Accept traffic towards loopback"
                ct state established,related accept comment "!fw4: Allow outbound established and related flows"
                oifname "br-lan" jump output_lan comment "!fw4: Handle lan IPv4/IPv6 output traffic"
                oifname { "eth0.2", "usb0" } jump output_wan comment "!fw4: Handle wan IPv4/IPv6 output traffic"
        }

        chain prerouting {
                type filter hook prerouting priority filter; policy accept;
                iifname "br-lan" jump helper_lan comment "!fw4: Handle lan IPv4/IPv6 helper assignment"
        }

        chain handle_reject {
                meta l4proto tcp reject with tcp reset comment "!fw4: Reject TCP traffic"
                reject comment "!fw4: Reject any other traffic"
        }

        chain syn_flood {
                limit rate 25/second burst 50 packets return comment "!fw4: Accept SYN packets below rate-limit"
                drop comment "!fw4: Drop excess packets"
        }

        chain input_lan {
                jump accept_from_lan
        }

        chain output_lan {
                jump accept_to_lan
        }

        chain forward_lan {
                jump accept_to_wan comment "!fw4: Accept lan to wan forwarding"
                jump accept_to_lan
        }

        chain helper_lan {
        }

        chain accept_from_lan {
                iifname "br-lan" counter packets 12 bytes 792 accept comment "!fw4: accept lan IPv4/IPv6 traffic"
        }

        chain accept_to_lan {
                oifname "br-lan" counter packets 0 bytes 0 accept comment "!fw4: accept lan IPv4/IPv6 traffic"
        }

        chain input_wan {
                meta nfproto ipv4 udp dport 68 counter packets 0 bytes 0 accept comment "!fw4: Allow-DHCP-Renew"
                icmp type echo-request counter packets 0 bytes 0 accept comment "!fw4: Allow-Ping"
                meta nfproto ipv4 meta l4proto igmp counter packets 0 bytes 0 accept comment "!fw4: Allow-IGMP"
                meta nfproto ipv6 udp dport 546 counter packets 0 bytes 0 accept comment "!fw4: Allow-DHCPv6"
                ip6 saddr fe80::/10 icmpv6 type . icmpv6 code { mld-listener-query . no-route, mld-listener-report . no-route, mld-listener-done . no-route, mld2-listener-report . no-route } counter packets 0 bytes 0 accept comment "!fw4: Allow-MLD"
                icmpv6 type { destination-unreachable, time-exceeded, echo-request, echo-reply, nd-router-solicit, nd-router-advert } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Input"
                icmpv6 type . icmpv6 code { packet-too-big . no-route, parameter-problem . no-route, parameter-problem . admin-prohibited, nd-neighbor-solicit . no-route, nd-neighbor-advert . no-route } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Input"
                jump reject_from_wan
        }

        chain output_wan {
                jump accept_to_wan
        }

        chain forward_wan {
                icmpv6 type { destination-unreachable, time-exceeded, echo-request, echo-reply } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Forward"
                icmpv6 type . icmpv6 code { packet-too-big . no-route, parameter-problem . no-route, parameter-problem . admin-prohibited } limit rate 1000/second counter packets 0 bytes 0 accept comment "!fw4: Allow-ICMPv6-Forward"
                meta l4proto esp counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Allow-IPSec-ESP"
                udp dport 500 counter packets 0 bytes 0 jump accept_to_lan comment "!fw4: Allow-ISAKMP"
                jump reject_to_wan
        }

        chain accept_to_wan {
                oifname { "eth0.2", "usb0" } counter packets 180 bytes 9546 accept comment "!fw4: accept wan IPv4/IPv6 traffic"
        }

        chain reject_from_wan {
                iifname { "eth0.2", "usb0" } counter packets 0 bytes 0 jump handle_reject comment "!fw4: reject wan IPv4/IPv6 traffic"
        }

        chain reject_to_wan {
                oifname { "eth0.2", "usb0" } counter packets 0 bytes 0 jump handle_reject comment "!fw4: reject wan IPv4/IPv6 traffic"
        }

        chain dstnat {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain srcnat {
                type nat hook postrouting priority srcnat; policy accept;
                oifname { "eth0.2", "usb0" } jump srcnat_wan comment "!fw4: Handle wan IPv4/IPv6 srcnat traffic"
        }

        chain srcnat_wan {
                meta nfproto ipv4 masquerade comment "!fw4: Masquerade IPv4 wan traffic"
        }

        chain raw_prerouting {
                type filter hook prerouting priority raw; policy accept;
        }

        chain raw_output {
                type filter hook output priority raw; policy accept;
        }

        chain mangle_prerouting {
                type filter hook prerouting priority mangle; policy accept;
        }

        chain mangle_postrouting {
                type filter hook postrouting priority mangle; policy accept;
        }

        chain mangle_input {
                type filter hook input priority mangle; policy accept;
        }

        chain mangle_output {
                type route hook output priority mangle; policy accept;
        }

        chain mangle_forward {
                type filter hook forward priority mangle; policy accept;
                iifname { "eth0.2", "usb0" } tcp flags syn tcp option maxseg size set rt mtu comment "!fw4: Zone wan IPv4/IPv6 ingress MTU fixing"
                oifname { "eth0.2", "usb0" } tcp flags syn tcp option maxseg size set rt mtu comment "!fw4: Zone wan IPv4/IPv6 egress MTU fixing"
        }
}
```

**Comment by yichya** [comment]
Weird. Check if this file exists and, if not try `ln -s /var/etc/xray/firewall_include.nft /etc/nftables.d/99-xray.nft`

![image](https://user-images.githubusercontent.com/3683052/209473478-fd2109a4-2f3d-4414-a123-67c18427f4dd.png)

**Comment by yichya** [comment]
> Weird. Check if this file exists and, if not try `ln -s /var/etc/xray/firewall_include.nft /etc/nftables.d/99-xray.nft`
> 
> ![image](https://user-images.githubusercontent.com/3683052/209473478-fd2109a4-2f3d-4414-a123-67c18427f4dd.png)

And if `/var/etc/xray/firewall_include.nft` not exists, try `utpl /usr/share/xray/firewall_include.ut > /var/etc/xray/firewall_include.nft`

**Comment by hawshemi** [comment]
The file is named `include.nft`.

<img width="644" alt="nftables" src="https://user-images.githubusercontent.com/16742123/209479825-ff21e2ea-1f56-423f-af8e-d562d5d0610b.png">

**Comment by yichya** [comment]
> The file is named `include.nft`.

That seems wrong. Try replacing the file with `ln -s /var/etc/xray/firewall_include.nft /etc/nftables.d/99-xray.nft`

**Comment by hawshemi** [comment]
I ran the command `ln -s /var/etc/xray/firewall_include.nft /etc/nftables.d/99-xray.nft` But it says `ln: /etc/nftables.d/99-xray.nft: File exists` And the file include.nft won't replaced.
<img width="552" alt="nf" src="https://user-images.githubusercontent.com/16742123/209500588-2f1f9cf5-e975-4243-b70d-ec277a3c5147.png">

**Comment by yichya** [comment]
> I ran the command `ln -s /var/etc/xray/firewall_include.nft /etc/nftables.d/99-xray.nft` But it says `ln: /etc/nftables.d/99-xray.nft: File exists` And the file include.nft won't replaced.

I checked that again and the file you have seems to work as well so you don't need to change that.

> And when I enable TProxy and sniffing: 

From that log it seems that luci-app-xray is working as expected (together with firewall settings) but your outbound seems getting `connection reset` error. You may need to figure that out first.

**Comment by hawshemi** [comment]
So the config is ok?
But my router cannot connect to the VPN server. (I use VLESS+gRPC and/or VLESS+TCP+XTLS)
None of them would work. They will connect with apps like v2rayng, but it's not working in the router.

**Comment by yichya** [comment]
> So the config is ok? But my router cannot connect to the VPN server. (I use VLESS+gRPC and/or VLESS+TCP+XTLS) None of them would work. They will connect with apps like v2rayng, but it's not working in the router. 

I read the log you have posted again and only found DNS requests so there may still be something wrong with firewall settings. Maybe just try `utpl /usr/share/xray/firewall_include.ut > /etc/nftables.d/99-firewall_include.nft` and `service firewall restart`.

> Can I completely turn off the tproxy so all of the requests will rout to xray?

If you turn off tproxy, all requests will be routed directly (which means no requests will be forwarded to your VPN server).

One more thing: the log you've posted above leaked your server address. You should delete that as soon as possible.

**Comment by hawshemi** [comment]
Ow. Thanks.

Is it possible for the RAM bottlenecking?

<img width="1633" alt="restart" src="https://user-images.githubusercontent.com/16742123/209545674-fe7fa2bc-821b-4f1f-b088-38ed67f0ffda.png">


In this log the deleted parts is my VPN host address. Is everything ok when the log returned ` domain XXX.XXX.XXX:xxx matches following rules: gesosite:geolocation-!cn` ?

**Comment by yichya** [comment]
> Is it possible for the RAM bottlenecking? Sometimes the memory becomes full, like 0.11 / 0.12 ( router has 128 MB ram). But not always.

If you see this oom-kill log this does mean that you are running out of memory.

> In this log, the deleted parts is my VPN host address. Is everything ok when the log returned ` domain XXX.XXX.XXX:xxx matches following rules: gesosite:geolocation-!cn` ? <img alt="2" width="1205" src="https://user-images.githubusercontent.com/16742123/209547548-9cc4cf2e-4147-451b-8a68-ba33cba8ec86.png">
> 

That should not happen (seems like I have to figure out some priority related things in DNS module) and it will cause problems... 

You may change it to something like 'geosite:category-vpnservices' or just remove that.

And at the same time you should not use 114.114.114.114 there as your Fast DNS since that is a DNS service provider in China. Use 192.168.13.1 there instead.

> Also, If I want to change `cn` to Iran domains, can I just change the `cn` to `ir` ?

No. `gesosite:geolocation-!cn` is a special category in geosite.dat so you can't just replace `cn` there.

**Comment by hawshemi** [comment]
Should I set the UDP server to my VPN server when the protocol is vless+tcp+xtls ? or should I disable it?
<img width="746" alt="general" src="https://user-images.githubusercontent.com/16742123/209761182-b5e3670d-954e-4488-b970-a68e40342d92.png">

With these settings:
<img width="734" alt="dns" src="https://user-images.githubusercontent.com/16742123/209761221-d80628d0-f285-47aa-8d63-deeca7b46947.png">

<img width="750" alt="tproxy" src="https://user-images.githubusercontent.com/16742123/209761225-06ee2a9a-4c10-48a3-8cb0-2891ee410c33.png">

Internet is not being routed to the x-ray server. It'll return the real IP.

_btw, thank you so much for answering and tinkering. I appreciate it._

**Comment by yichya** [comment]
> Should I set the UDP server to my VPN server when the protocol is vless+tcp+xtls ? or should I disable it? 

UDP server has nothing to do with outbound protocol. It only determines whether UDP traffic will be forwarded through Xray.

> With these settings

Oh. I forgot that enabling sniffing on your device may greatly impact performance or even lead to frequent crashes. Try disabling sniffing and try again.

**Comment by hawshemi** [comment]
I disabled Sniffing, and it's partially(!) working.

After disabling sniffing, when I check myip via google, it'll return the proxied IP via the x-ray. But when I enter, for example, youtube, it will not go to xray and it's still blocked.

Here is the log:
<img width="1106" alt="error2" src="https://user-images.githubusercontent.com/16742123/209791857-3dcbe723-48a8-421b-91cd-6286631effc7.png">

**Comment by yichya** [comment]
> I disabled Sniffing, and it's partially(!) working.
> 
> After disabling sniffing, when I check myip via google, it'll return the proxied IP via the x-ray. But when I enter, for example, youtube, it will not go to xray and it's still blocked.
> 

According to the log this is definitely DNS settings problem. 

Try a simple setting like filling `geosite:gfw` in "Forwarded domains rules" and `geosite:private` in "Bypassed domain rules".

**Comment by hawshemi** [comment]
<img width="1628" alt="error" src="https://user-images.githubusercontent.com/16742123/209835605-970c25b0-9338-439d-bd7f-ddd8dbbc9739.png">

**Comment by yichya** [comment]
Try this geosite.dat: [https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat](https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat)

**Comment by hawshemi** [comment]
Replaced the file now the situation got better. it'll open (almost) all websites. but again, some won't open with the error:
`DNS_PROBE_FINISHED_NXDOMAIN`
And in the logread:
`daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: XXXXX.com`

And I think the device is bottlenecking on the CPU :)) After xray starts:
![image](https://user-images.githubusercontent.com/16742123/209849143-1aef29a8-ff1d-4600-9940-7b76f07fc71e.png)

Is there a way I can resource manage the CPU better?

**Comment by yichya** [comment]
> Replaced the file now the situation got better. it'll open (almost) all websites. but again, some won't open with the error: `DNS_PROBE_FINISHED_NXDOMAIN` And in the logread: `daemon.warn dnsmasq[1]: possible DNS-rebind attack detected: XXXXX.com`

Try adding those websites to "Forwarded domain rules". 

> Is there a way I can resolve the CPU bottlenecking? The xray package is so heavy...

Try adding your location to `GeoIP Direct Code List`. This may help.

**Comment by hawshemi** [comment]
After playing with `Bypassed domain rules` and `Forwarded domain rules` I realised the problem is in these setting and the .dat files and settings.
I have a iran.dat including ir domains. I want to use this file to bypass the xray server.

What is the best setting for these conditions: 
Forward all domains to xray server except the iran.dat
the iran.dat file is alongside geoip.dat and geosite.dat files in `/usr/share/xray`

**Comment by yichya** [comment]
> After playing with `Bypassed domain rules` and `Forwarded domain rules`, I realized the problem is in these settings and the .dat files and settings. I have an iran.dat, including ir domains. I want to use this file to bypass the xray server.
> 
> What is the best setting for this condition: Forward Everything to xray server except the iran.dat The iran.dat file is alongside geoip.dat and geosite.dat files in `/usr/share/xray`
> 
> What should I put in `Bypassed domain rules` and `Forwarded domain rules` ?

Fill `ext:iran.dat:<your category>` in "Bypassed domain rules". Keep `geosite:gfw` in "Forwarded domain rules" as there must be something there.

**Comment by hawshemi** [comment]
Is there a more general config for `geosite:gfw`? In Iran, more websites are blocked in the GFW.

**Comment by yichya** [comment]
> Is there a more general config for `geosite:gfw`? In Iran, more websites are blocked in the GFW.

Just make sure there is something. 

Domain names not in "Bypassed domain rules" or "Forwarded domain rules" should be resolved by "Default DNS" (if it does not work as expected, please report here). In your case you should make sure that "Default DNS" is working so replace default `1.1.1.1` with something you have tried.

**Comment by hawshemi** [comment]
Yes, now it's working fine when I configured the iran.dat at the Bypassed rules.

So there is no regex or command for `Forwarded domain rules` which indicate "Everything" (and not just GFW)?

**Comment by yichya** [comment]
> So there is no regex or command for `Forwarded domain rules` which indicate "Everything" (and not just GFW)?

Actually I'm working on a major refactor of DNS related things with more functions in consideration but I'm quite busy recently and I can't say for sure when it'll be ready.

**Comment by hawshemi** [comment]
Thanks.
Hope we'll hear from you soon with more updates and features. Btw, this is an astonishing work.
Good Job.
