### ISSUE TITLE
建议：黑名单Blocked domain rules可以一次性填入，而不是一条条填进去

### ISSUE THREAD

**Issue by xiechangan123** [yichya/luci-app-xray#254]
如题，我只需要屏蔽小米电视的广告域名，一条条填进去太麻烦费时间了，同时也不美观（网页都好长），可以搞成直接把所有域名一起输入进去么？
如果不愿意搞，麻烦告诉我下，怎么硬编码进去这些广告域名，我直接fork你的源码，以后我自己修修补补。再次感谢

![image](https://user-images.githubusercontent.com/9552275/209372521-994c31c1-70dd-4ff0-8a4c-22d134d6cb70.png)

**Comment by yichya** [comment]
可以贡献到 geosite.dat 或者自己准备一个额外的资源文件（放在 /usr/share/xray 里面）

<img width="849" alt="image" src="https://user-images.githubusercontent.com/3683052/209415150-6387c22d-d99c-4c39-850b-cfad9080cb2d.png">

**Comment by yichya** [comment]
我看 [https://github.com/Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat) 有这个 category 了，你可以直接给这个仓库提 pr 或者 fork 它把你需要的域名加进去

<img width="912" alt="image" src="https://user-images.githubusercontent.com/3683052/209415447-6e74de52-e5b3-4537-91d6-63c5ace28d49.png">
