### ISSUE TITLE
移动宽带老是更换IP导致xray挂起无反应

### ISSUE THREAD

**Issue by xiechangan123** [yichya/luci-app-xray#255]
如题，之前我用此软件就觉得奇怪，怎么隔段时间xray+grpc+cdn模式挂起没速度，家庭使用极为不便。今天在宿舍，偶然看到光猫灯闪了一下，突然想到是不是移动后台刷新ip了？一查果然是更换了，到openwrt启动项重启xray，立马就满速跑起来了。所以作者是不是可以增加个定时（10/60/24×60/48×60min）检测ip地址是否更换，之后重启xray的选项（写死在代码也行），方便没有固定IP的移动/电信/联通宽带。。。虽然搞了个渣渣的定时脚本，但是还是希望软件能内置此功能，而且真的很有需求性

**Comment by yichya** [comment]
两个问题需要确认下：

1. 在【移动后台刷新 IP】的时候，OpenWrt 拿到的 WAN IP 是否会发生变化？
2. 是否开启了 GRPC 的健康检查，或者使用其他非 GRPC 的时候是否有相似现象？

**Comment by xiechangan123** [comment]
1、家里是openwrt桥接拨号，宿舍是openwrt dhcp，二者wan ip没变，都是动态ip变了（ip查询网站明显看出来变了）
2、没开启健康检查（也没在意这个小小设置会影响grpc），vless+websocket+cdn也有类似现象，只不过是减速，不至于断流。其他协议目前杀鸡太严重，我也没尝试，就不清楚了

**Comment by yichya** [comment]
建议先开 GRPC 健康检查试试。定时重启这个，直接用 cron 自己做就好了，暂时没有支持的想法。
