### ISSUE TITLE
Xray service stopped after xray 1.7.0 update.

### ISSUE THREAD

**Issue by hawshemi** [yichya/luci-app-xray#257]
Did the update break the xray?
It was recently updated to xray v1.7.0 and in the luci app, it says Xray stopped.
I ran `service xray start` and `service xray restart` but won't start.

The `logread` just return ` daemon.warn dnsmasq[1]: possible DNS-rebind attack detected:`

And all the traffic does not go to the proxy server and the real IP is shown on the web.

**Comment by yichya** [comment]
My setup is working fine with latest Xray v1.7.2.

Try running `xray -version` and paste output here.

**Comment by hawshemi** [comment]
`
root@OpenWrt:~# xray -version
Xray 1.7.0 (Xray, Penetrates Everything.) OpenWrt (go1.19.4 linux/mips)
A unified platform for anti-censorship.
`

**Comment by yichya** [comment]
If you're using `xray-core` package from official OpenWrt/Packages repository, reinstalling that package will overwrite startup script (`/etc/init.d/xray`) from luci-app-xray. In this case reinstall luci-app-xray will help.

**Comment by hawshemi** [comment]
I install the `openwrt-1.7.2`. But now the `Service/Xray` is just disappeared :))
I tried to install `luci-app-xray_1.22.0-1_all` but this error comes up:

<img width="450" alt="luci-app-xray" src="https://user-images.githubusercontent.com/16742123/212491429-dd3d542e-4a84-4ad7-8b65-d85aefb2a0f4.png">

**Comment by yichya** [comment]
> I installed the `openwrt-1.7.2`, But now the `Service/Xray` is just disappeared in the UI :)) 

Just reboot to let LuCI rebuild its module cache

**Comment by hawshemi** [comment]
Rebooted many times. But nothing.

**Comment by yichya** [comment]
Remove luci-app-xray and reinstall it then

**Comment by hawshemi** [comment]
I did that two times. but every time this error is shown:
https://user-images.githubusercontent.com/16742123/212491429-dd3d542e-4a84-4ad7-8b65-d85aefb2a0f4.png

**Comment by yichya** [comment]
Let me see if this uci error implies anything. I thought that could be simply ignored

**Comment by hawshemi** [comment]
I updated to xray 1.7.2.
And built the .ipk myself from the repo and SDK.
all is well now.
