### ISSUE TITLE
xray can't start with empty HTTP Host value

### ISSUE THREAD

**Issue by Soberia** [yichya/luci-app-xray#258]
For TCP Transport Settings, if `Fake Header Type` sets to `HTTP` and `Host` is not to set anything, xray can't start with following error:

```
Mon Jan 16 16:14:23 2023 daemon.info xray[12721]: Failed to start: main: failed to load config files: [/var/etc/xray/config.json] > infra/conf: Failed to build TCP config. > infra/conf: invalid TCP header config > infra/conf: empty HTTP header value: Host
```

However, if `list http_host ''` manually added to config file `/etc/config/xray`, the error will be gone.

**Comment by yichya** [comment]
Marked this option as required.
