### ISSUE TITLE
Feature request: Initialize xray with (only) custom config.

### ISSUE THREAD

**Issue by alcatraz-zz** [yichya/luci-app-xray#263]
Hey!

This is a fantastic tool for xray. I've had some luck and some problems. I'd like to try and change basic config settings but it's not possible since lucy-app-xray replaces it upon start with its own generated.

I see there's a tab at the end called Custom. Is this config just added to the other config, or is it the only config used?

Thanks!

**Comment by alcatraz-zz** [comment]
Wait. I'm not entirely sure. It seems that when using the Custom tab, the normal config isn't used. Am I right?

I had some success when copying a config off my linux server and pasting it into luci-app-xray custom. Just had to edit the cert/key paths. 

But it's not working the way I got it to work once on another router. What am I doing wrong. Hmm...

**Comment by yichya** [comment]
> It seems that when using the Custom tab, the normal config isn't used. Am I right?

No. Custom config follows the rule of [https://xtls.github.io/config/features/multiple.html](https://xtls.github.io/config/features/multiple.html) where the config you filled there acts as another configuration file besides of the generated configuration file.

**Comment by himekifee** [comment]
It would be really appreciated if custom only config can be implemented. There are some advanced config logic that simply cannot be dealt with manually tricking the generated config. There should be an option for complete manual config override, with some hint asking user defining some necessary inbound for tproxy. I'd like to donate some if this functionality can be implemented.

**Comment by yichya** [comment]
> There should be an option for complete manual config override, with some hint asking user defining some necessary inbound for tproxy.

https://github.com/yichya/luci-app-xray/pull/358 gives users full control over configuration file. However luci-app-xray runs a lot of "necessary inbound" (it will listen more than 10 ports just for inbounds and DNS) and other components to work correctly, so it is only intended for some small tuning. Using that feature for a complete manual config override may not be a good option but anyone could try.
