### ISSUE TITLE
Request update prebuilt package

### ISSUE THREAD

**Issue by alcatraz-zz** [yichya/luci-app-xray#264]
Hi 

Could I trouble someone to update the prebuilt package? It's 3 months old and there have been some interesting updates.

One day I would like to explore building and compiling, but right now it's wayy over my head. I'd like to build my own openwrt image and try some overclocking. In any case, I digress...  

Love the work you guys are doing. This is great stuff!

**Comment by hawshemi** [comment]
You need a linux vps (or vm), I build with Ubuntu 22.04:

You can build yourself using these commands:

# Install required packages
apt install -y build-essential wget xz-utils libncurses-dev gawk file rsync git unzip python3

# Download the SDK (find you device on https://downloads.openwrt.org/releases/22.03.3/targets/). the link is just for the ath79. you may need to change this.
wget https://downloads.openwrt.org/releases/22.03.3/targets/ath79/nand/openwrt-sdk-22.03.3-ath79-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz
tar -xf openwrt-sdk-22.03.3-ath79-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz
cd openwrt-sdk-22.03.3-ath79-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz
git clone https://github.com/yichya/luci-app-xray.git package/luci-app-xray

# Select the package from `Extra packages -> luci-app-xray`
make menuconfig

# Start the build, generated ipk will be located in the ./bin directory
make package/luci-app-xray/compile V=99

**Comment by alcatraz-zz** [comment]
Thank you so much! It's people like you who get others into the community. Cheers!

**Comment by hawshemi** [comment]
> Thank you so much! It's people like you who get others into the community. Cheers!

No problem.
Don't hesitate if you needed more help.

**Comment by Recoba86** [comment]
> You need a linux vps (or vm), I build with Ubuntu 22.04:
> 
> You can build yourself using these commands:
> 
> Install required packages `apt install -y build-essential wget xz-utils libncurses-dev gawk file rsync git unzip python3`
> 
> Download the SDK (find you device on https://downloads.openwrt.org/releases/22.03.3/targets/). the link is just for the ath79. you may need to change this. `wget https://downloads.openwrt.org/releases/22.03.3/targets/ath79/nand/openwrt-sdk-22.03.3-ath79-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz` `tar -xf openwrt-sdk-22.03.3-ath79-nand_gcc-11.2.0_musl.Linux-x86_64.tar.xz` `cd openwrt-sdk-22.03.3-ath79-nand_gcc-11.2.0_musl.Linux-x86_64` `git clone https://github.com/yichya/luci-app-xray.git package/luci-app-xray`
> 
> Select the package from `Extra packages -> luci-app-xray` `make menuconfig`
> 
> Start the build, generated ipk will be located in the ./bin directory `make package/luci-app-xray/compile V=99`

can you explain more about this part?
Select the package from Extra packages -> luci-app-xray
make menuconfig
when I run the command it shows a window but can't find extra packages
