### ISSUE TITLE
21.02.x is still "somewhat" supported - but no ipk will install 

### ISSUE THREAD

**Issue by alcatraz-zz** [yichya/luci-app-xray#265]
Hey!

I'm suspecting issues with v22 for my router so I'd like to test the latest v21 as a possible candidate for running xray 1.7.2 on multiple mips routers.

I can't get any of the prebuilt ipk packages to install. I tried adding "arch mipsel_24kc 100" in the opkg config. I tried all the opkg flags to force install regardless of dependencies.

Do you have any suggestion how I might install luci-app-xray on v21? I just want to run a server/portal and thus I don't need any tproxy stuff. 

I have the config.json basically done, so I need to initialize the openwrt-xray binary.

Errors with arch opkg config:
```
Unknown package 'luci-app-xray'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-xray found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-xray.
```

Errors without arch opkg config. 
```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-tproxy for luci-app-xray
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-xray found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-xray.
```

**Comment by yichya** [comment]
luci-app-xray depends on different firewall implementations on different versions of OpenWrt. When using OpenWrt 21.02 versions you need to manually build luci-app-xray with fw3 as its firewall implementation.

If you only need server role and does not need anything about transparent proxy, just install [https://github.com/openwrt/packages/tree/master/net/xray-core] and refer to its examples for a simple server setup.

**Comment by alcatraz-zz** [comment]
> If you only need server role and does not need anything about transparent proxy, just install https://github.com/openwrt/packages/tree/master/net/xray-core and refer to its examples for a simple server setup.

Very interesting. Wouldn't that require compiling the packages? I need to read up on how to do that.

Thanks for still putting up with my questions. I'm super curious about your work.

**Comment by alcatraz-zz** [comment]
Ok. I got it working with just xray-core. It seems that official package is complete.
