### ISSUE TITLE
Ubuntu系统编译小米AC2100不通过

### ISSUE THREAD

**Issue by wjp97** [yichya/luci-app-xray#268]
不懂go语言，查了一下也没找到解决方法。
# 错误代码
go: github.com/quic-go/qtls-go1-18@v0.2.0 requires
        golang.org/x/crypto@v0.0.0-20200221231518-2aa609cf4a9d: missing go.sum entry; to add it:
        go mod download golang.org/x/crypto
make[2]: *** [Makefile:69: /home/user1/build/openrt-sdk/build_dir/target-mipsel_24kc_musl/openwrt-xray-1.7.3/.built] Error 1
## 具体报错
touch /home/user1/build/openrt-sdk/build_dir/target-mipsel_24kc_musl/openwrt-xray-1.7.3/.built_check
cd /home/user1/build/openrt-sdk/build_dir/target-mipsel_24kc_musl/openwrt-xray-1.7.3; GOOS="linux" GOARCH="mipsle" GO386="" GOARM="" GOMIPS="softfloat" GOMIPS64="" CGO_ENABLED=1 CC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -ffile-prefix-map=/home/user1/build/openrt-sdk/build_dir/target-mipsel_24kc_musl/openwrt-xray-1.7.3=openwrt-xray-1.7.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/user1/build/openrt-sdk/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/include -I/home/user1/build/openrt-sdk/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/fortify -I/home/user1/build/openrt-sdk/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -ffile-prefix-map=/home/user1/build/openrt-sdk/build_dir/target-mipsel_24kc_musl/openwrt-xray-1.7.3=openwrt-xray-1.7.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/user1/build/openrt-sdk/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/user1/build/openrt-sdk/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/home/user1/build/openrt-sdk/build_dir/target-mipsel_24kc_musl/openwrt-xray-1.7.3/.go_work/build" GOCACHE="/home/user1/build/openrt-sdk/tmp/go-build" GOMODCACHE="/home/user1/build/openrt-sdk/dl/go-mod-cache" GOENV=off GOPROXY=https://goproxy.io,direct CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o /home/user1/build/openrt-sdk/build_dir/target-mipsel_24kc_musl/openwrt-xray-1.7.3/ipkg-install/bin/xray ./main;
go: github.com/quic-go/qtls-go1-18@v0.2.0 requires
        golang.org/x/crypto@v0.0.0-20200221231518-2aa609cf4a9d: missing go.sum entry; to add it:
        go mod download golang.org/x/crypto
make[2]: *** [Makefile:69: /home/user1/build/openrt-sdk/build_dir/target-mipsel_24kc_musl/openwrt-xray-1.7.3/.built] Error 1
make[2]: Leaving directory '/home/user1/build/openrt-sdk/package/extra/openwrt-xray'
time: package/extra/openwrt-xray/compile#0.24#0.04#0.25
    ERROR: package/extra/openwrt-xray failed to build.
make[1]: *** [package/Makefile:114: package/extra/openwrt-xray/compile] Error 1
make[1]: Leaving directory '/home/user1/build/openrt-sdk'
make: *** [/home/user1/build/openrt-sdk/include/toplevel.mk:223: package/luci-app-xray/compile] Error 2
# 环境
Ubuntu22，go语言是用apt install golang-go安装的
## go语言环境
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user1/.cache/go-build"
GOENV="/home/user1/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-mod=mod"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user1/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user1/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4129869269=/tmp/go-build -gno-record-gcc-switches"

**Comment by yichya** [comment]
等下一个版本吧，应该这两天就发了。

**Comment by yichya** [comment]
https://github.com/yichya/openwrt-xray/releases/tag/v1.7.5
