### ISSUE TITLE
Compile the package using the SDK

### ISSUE THREAD

**Issue by M33FT** [yichya/luci-app-xray#27]
Thanks for your very good program. It was really necessary.
Can you please tell me how I can with the official RaspberryPi 3B SDK (19.7.6)Compile this package?
I have already compiled other packages with SDK and I am familiar with it. 
But I do not know why this package is not added to the "make" menu? 
Please tell me the instructions I need to enter in the terminal so that other people like me can solve this problem.
Thanks ;-)

**Comment by yichya** [comment]
clone this repository under `package/extra` (mkdir -p if you don't have that) and you should see luci-app-xray under "Extra packages" submenu

**Comment by M33FT** [comment]
Thanks for the feedback, yes I did, but when compiling I use the following command:

make package/luci-app-xray/compile V=99

Gives me the following error.

![ScreenShot](https://user-images.githubusercontent.com/63062740/106195346-45a7ab80-61c5-11eb-9515-2d1a2509da9d.png)

make[2]: *** [Makefile:137: /home/m33ft/openwrt-sdk-19.07.6-brcm2708-bcm2710_gcc-7.5.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/luci-app-xray-7da97635b28bfa7296fe79bbe7cd804a684317d9/.built] Error 2
make[2]: Leaving directory '/home/m33ft/openwrt-sdk-19.07.6-brcm2708-bcm2710_gcc-7.5.0_musl.Linux-x86_64/package/extra/luci-app-xray'
time: package/extra/luci-app-xray/compile#0.49#0.29#0.58
make[1]: *** [package/Makefile:113: package/extra/luci-app-xray/compile] Error 2
make[1]: Leaving directory '/home/m33ft/openwrt-sdk-19.07.6-brcm2708-bcm2710_gcc-7.5.0_musl.Linux-x86_64'
make: *** [/home/m33ft/openwrt-sdk-19.07.6-brcm2708-bcm2710_gcc-7.5.0_musl.Linux-x86_64/include/toplevel.mk:220: package/extra/luci-app-xray/compile] Error 2



Is there something I did not do?

Thanks for guiding me

**Comment by yichya** [comment]
seems the ask you are using comes with a old version of go while xray requires go1.15+ to compile. this problem is a little bit hard to solve because you have to download prebuilt xray binaries...

**Comment by yichya** [comment]
i'll look into this later, maybe remove the process of building xray and just depend on [openwrt-xray](https://github.com/yichya/openwrt-xray) instead (so you can download ipks there to install xray and still use this luci app for configurations)

**Comment by M33FT** [comment]
Yes. It would be great to be able to compile the package more easily in the future.
Anyway, I'm using the latest official version of the openwrt SDK and I'm having this problem.
But now that I tested with the Snapshot version, I was able to compile it. 

Thanks
