### ISSUE TITLE
Feature request: Xray client listens on another openwrt interface

### ISSUE THREAD

**Issue by alcatraz-zz** [yichya/luci-app-xray#271]
Hey guys

How about this idea. An option to have tproxy listen on a separate openwrt interface (not brlan). That way the same router can simultaneously manage two local networks, in parallel.

That way we can assign a second wifi ssid or ethernet port to that interface.

I know that previously mac filtering is how it's commonly been done in the past, but the feature proposed is nice to leave the choice up to the client without having to configure the router for each mac. You could switch back and forth etc. Dns should remain unaffected on one interface. 
 
I think xray would be installed on more routers if there was no downside to installing it. The downside now (to me) is the complexity. If the proxy goes down, update failed, service crash, then it could put the network offline.

**Comment by yichya** [comment]
There's already a setting for that?

![image](https://user-images.githubusercontent.com/3683052/220721715-d57d3902-0d44-4601-ad3d-21c97179cfc5.png)

**Comment by alcatraz-zz** [comment]
Whattttt! How did I miss that. I'll report back after testing!

For the time being, I apologise.
