### ISSUE TITLE
能不能出一个可以兼容 dockerd 的版本？

### ISSUE THREAD

**Issue by dilllay** [yichya/luci-app-xray#275]
作者你好，openwrt 里面如果选装了 `dockerd` 的话会导致下游设备全部不能上网（设备作为旁路网关）。这时我查看了 level info 的日志，xray自身的转发貌似一切正常，下游设备使用  `dig www.youtube.com @[xray.device.ip] -p 5300 ` 获取 ip 也正常，从日志也可以看出能够正确分流国内外域名，但是之后的流量数据是不通的（网页打不开，应用打不开）
![image](https://user-images.githubusercontent.com/4126983/221691910-b04c8345-3d0d-4959-a76d-730f0ce909c8.png)
  看了你的 `README` 写道新版 openwrt使用了 `firewall 4` 作为默认防火墙，但 `dockerd` 默认使用的是 `iptables` 的，不知道是不是这个原因导致无法正常使用，两个防火墙之间产生冲突了。请问可不可以出一个 for `iptables` 的版本 ？？或者 可以兼容 `dockerd` 的版本？？
![image](https://user-images.githubusercontent.com/4126983/221693294-57e328cc-3f4a-4e63-8f75-3b0a0c2400db.png)

**Comment by yichya** [comment]
编译的时候去掉 fw4 选中 fw3，luci-app-xray 就会自动改用 fw3 的方式运行了。

不过即使是 fw3 的方式也不确定是不是能跟 docker 兼容，docker 的 iptables 相当复杂

**Comment by dilllay** [comment]
emmm....抱歉我对 fw 非常不熟悉，我以为 只需要把 `firewall_include.lua` 和 `init.fw3(fw4)` 转成 iptables 就好了，因为我最早用 `xray` 的时候，看他官方推荐透明网关的方法也是使用 `iptables` 作为案例，[比如这样](https://xtls.github.io/document/level-2/tproxy.html#netfilter-%E9%85%8D%E7%BD%AE)
![image](https://user-images.githubusercontent.com/4126983/221737832-1574a910-523f-4def-a79a-28d26a42b2f5.png)

不知道这样行不行得通？

**Comment by yichya** [comment]
> emmm....抱歉我对 fw 非常不熟悉，我以为 只需要把 `firewall_include.lua` 和 `init.fw3(fw4)` 转成 iptables 就好了

firewall_include.lua 就是用于支持 fw3（iptables）的实现，不用改，但是编译 OpenWrt 的时候需要选择使用 fw3 而不是默认的 fw4，luci-app-xray 会在编译的过程中自动适配

**Comment by yichya** [comment]
以及你有没有试过使用 podman 呢？

**Comment by dilllay** [comment]
> 以及你有没有试过使用 podman 呢？

被你提醒了，我都忘记了有这个东西存在，2年前看见他感觉是个很二流和各种商业吹捧以外，啥也不是的东西，现在想起来那东西好像是没有守护进程的，估计有可能可以。但我没在 openwrt 上用过或者编译过，晚点回去试试，谢谢你的提醒
