### ISSUE TITLE
请问用 ImmortalWrt 源码，增加插件编译的流程是什么？

### ISSUE THREAD

**Issue by chika0801** [yichya/luci-app-xray#276]
我的路由器是 **红米AX6000**，使用的源码仓库是 https://github.com/hanwckf/immortalwrt-mt798x 。

我使用VPS，输入以下命令

```
git clone -b openwrt-21.02 --single-branch https://github.com/hanwckf/immortalwrt-mt798x.git openwrt
cd openwrt
echo -e 'src-git luci_app_xray https://github.com/yichya/luci-app-xray' >> feeds.conf.default
./scripts/feeds update -a
./scripts/feeds install -a
cp -f defconfig/mt7986-ax6000.config .config
make menuconfig
```
在选择 luci app 的界面，没有找到 luci-app-xray，请问应该如何排错？
![1](https://user-images.githubusercontent.com/88967758/222092667-0efb9c1a-c8f1-4742-a670-fe433045cd1e.jpg)

**Comment by yichya** [comment]
clone 到 package/extra（没有这个目录就建一个）然后在 Extra Packages 里面找。

**Comment by chika0801** [comment]
> 

感谢帮助，操作后在  Extra Packages 里已经有了，我先尝试编译试试
