### ISSUE TITLE
luci-i18n-xray-zh-cn原作者删库了，有需要中文包的可以fork我的库

### ISSUE THREAD

**Issue by xiechangan123** [yichya/luci-app-xray#286]
如题，我的库地址：https://github.com/xiechangan123/luci-i18n-xray-zh-cn 今天编译一直错误，排查了下。原作者一直“摆烂”，很早就想自己更新了，这次删库正好是个契机，反正胆子大路子野。。。

**Comment by yichya** [comment]
十分感谢 ~~（其实我想说这个真的有中文的必要嘛~~
