### ISSUE TITLE
现成的ipk文件，下载食用，帮你快速体验有luci界面的xray。

### ISSUE THREAD

**Issue by science2468** [yichya/luci-app-xray#288]
我在本地编译完成，已经出包。我使用的环境是openwrt v22.03.3 平台x86-64。我安装成功，也正确显示中文，没有具体上节点测试。链接如下： https://github.com/science2468/luci-i18n-xray-zh-cn/releases/tag/2.0-1      luci-app-xray出处：https://github.com/yichya/luci-app-xray  ；luci-i18n-xray-zh-cn出处： https://github.com/xiechangan123/luci-i18n-xray-zh-cn

**Comment by firefoxOnFire** [comment]
> I have compiled it locally and the package has been released. The environment I use is openwrt v22.03.3 platform x86-64. I installed it successfully and displayed Chinese correctly, but did not test on the specific node. The link is as follows: [ https://github.com/science2468/luci-i18n-xray-zh-cn/releases/tag/2.0-1 ](https://github.com/science2468/luci-i18n-xray-zh-cn/releases/tag/2.0-1) source of luci-app-xray: [ https://github.com/yichya/luci-app -xray ](https://github.com/yichya/luci-app-xray) ; luci-i18n-xray-zh-cn Source: [ https://github.com/xiechangan123/luci-i18n-xray-zh-cn ](https://github.com/xiechangan123/luci-i18n-xray-zh-cn)

Hey, How much maximum space it will require?? I have less than 8 MB probably.

**Comment by science2468** [comment]
> > I have compiled it locally and the package has been released. The environment I use is openwrt v22.03.3 platform x86-64. I installed it successfully and displayed Chinese correctly, but did not test on the specific node. The link is as follows: [ https://github.com/science2468/luci-i18n-xray-zh-cn/releases/tag/2.0-1 ](https://github.com/science2468/luci-i18n-xray-zh-cn/releases/tag/2.0-1) source of luci-app-xray: [ https://github.com/yichya/luci-app -xray ](https://github.com/yichya/luci-app-xray) ; luci-i18n-xray-zh-cn Source: [ https://github.com/xiechangan123/luci-i18n-xray-zh-cn ](https://github.com/xiechangan123/luci-i18n-xray-zh-cn)
> 
> 嘿，它需要多少最大空间？？我可能只有不到 8 MB。

Installation is not recommended for devices smaller than 16MB
