### ISSUE TITLE
what maximum space it requires to be installed?

### ISSUE THREAD

**Issue by firefoxOnFire** [yichya/luci-app-xray#289]
I have less than 8MB space. Can I install this?? 

I want to install openwrt on my router to run this only. If I will be able to install, I will flash.

**Comment by yichya** [comment]
This project is only a GUI for Xray. Xray itself is very unlikely to run well on a device with only 8MB free space, even without geodata files.

**Comment by hawshemi** [comment]
@firefoxOnFire Minimum space for OpenWRT and Xray-Core installed is 128Mb and higher.
I had a router with 64Mb space and successfully installed OpenWrt on it but I couldn't install and run xray-core.

**Comment by firefoxOnFire** [comment]
Thanks I can understand.

**Comment by firefoxOnFire** [comment]
> This project is only a GUI for Xray. Xray itself is very unlikely to run well on a device with only 8MB free space, even without geodata files.

Is is possible to compile only VLESS REALITY to make it small? I only use this. And also only client, not server.

If possible, how hard will it be?

**Comment by yichya** [comment]
> Is is possible to compile only VLESS REALITY to make it small? I only use this. And also only client, not server.

It is possible but it won't be smaller enough to meet your needs.

**Comment by firefoxOnFire** [comment]
> > Is is possible to compile only VLESS REALITY to make it small? I only use this. And also only client, not server.
> 
> It is possible to make it smaller but it won't be small enough to meet your needs.

I just verified, I have 8.18MB. Anyway to make xray-core core package smaller. Package that support only vless.

**Comment by yichya** [comment]
> Anyway to make xray-core core package smaller. Package that support only vless.

It can be smaller but not that small to fit in this space...

**Comment by firefoxOnFire** [comment]
> > Anyway to make xray-core core package smaller. Package that support only vless.
> 
> It can be smaller but not that small to fit in this space...

Thanks 🙏
