### ISSUE TITLE
Is there a bug in  Official Docs https://github.com/yichya/luci-app-xray#installation ?

### ISSUE THREAD

**Issue by yukeiyang** [yichya/luci-app-xray#293]
**The Official Docs about Installation**
Choose one below:
Add src-git-full luci-app-xray https://github.com/yichya/luci-app-xray to feeds.conf.default   
and run ./scripts/feeds update -a; ./scripts/feeds install -a  

**There is one error displayed when run ./scripts/feeds update -a;** 
`$ cd openwrt-sdk-*Linux-x86_64 && sudo vi feeds.conf.default`  
`src-git-full luci-app-xray https://github.com/yichya/luci-app-xray`  
  
then, an error displayed.
`Syntax error in feeds.conf.default, line 6`

Seems  the  format of "src-git-full luci-app-xray" is not right. if change it to: "src-git-full luci_app_xray", it works fine.
But I don't know whether it will cause some other errors in the next steps for compiling ipk files or not.

plus, there is one issue displayed when make ipk.
`$ make package/luci-app-xray/compile -j1 V=s`
`make[1]: Entering directory '/home/plus/openwrt-sdk-22.03.4-x86-64_gcc-11.2.0_musl.Linux-x86_64' ` 
`make[1]: *** No rule to make target 'package/luci-app-xray/compile'. Stop.`

The previous version works fine, it happened only in this new version of luci-app-xray.

**Comment by yichya** [comment]
> Seems the format of "src-git-full luci-app-xray" is not right. if change it to: "src-git-full luci_app_xray", it works.
> But I don't know whether it will cause some error in the next steps for compiling ipk files or not.

I don't think that matters but I'll try that.

> plus, there is one issue displayed when make ipk. `$ make package/luci-app-xray/compile -j1 V=s` `make[1]: Entering directory '/home/plus/openwrt-sdk-22.03.4-x86-64_gcc-11.2.0_musl.Linux-x86_64' ` `make[1]: *** No rule to make target 'package/luci-app-xray/compile'. Stop.`

You have to specify variant (for example `make package/luci-app-xray/fw4/compile`).

**Comment by yichya** [comment]
Updated README.
