### ISSUE TITLE
when I put the domain address connection is not established!!!

### ISSUE THREAD

**Issue by rezconf** [yichya/luci-app-xray#295]
When I want to add a server in openwrt in the Server Hostname section, when I put the domain address, the connection is not established?  But when I put the IP address of the server, the connection is established.  what is the problem ?
Thanks alot

**Comment by malikshi** [comment]
Try with domain but set allowInsecure true.
Did you have normal connection? Try remote the dns? I don't know if it possible in xray. Worth to try.

**Comment by yukeiyang** [comment]
Seems inputting ip in address box is the standard usage if you are using reality version.  

![image](https://user-images.githubusercontent.com/6512594/235306866-a6d08742-f718-433c-aa1b-f85ae9c10002.jpeg)

**Comment by rezconf** [comment]
> Try with domain but set allowInsecure true.
> Did you have normal connection? Try remote the dns? I don't know if it possible in xray. Worth to try.

Well, the allowinsecure option is not available in the reality configuration.

**Comment by Soberia** [comment]
I have this error on my logs when trying to connect with domain name instead of an IP address:

```
Mon May  8 21:02:45 2023 daemon.info xray[9144]: 2023/05/08 16:32:45 [Warning] transport/internet: failed to resolve ip > app/dns: returning nil for domain my.***.io > multierr: context deadline exceeded | context deadline exceeded |
Mon May  8 21:02:45 2023 daemon.info xray[9144]: 2023/05/08 16:32:45 [Warning] transport/internet: failed to resolve ip > app/dns: returning nil for domain my.***.io > multierr: context deadline exceeded | context deadline exceeded |
```

This seems to be a DNS resolution problem. Setting the domain name in "DNS Settings -> Bypassed domain rules" are also not gonna help either.
I also have another problem with DNS. If `xray-core` couldn't establish the successful connection to the proxy server by whatever reason, DNS resolution also break on my other network interfaces so I have to manually stop the `xray` service.

**Comment by tarabrind** [comment]
> I have this error on my logs when trying to connect with a domain name instead of an IP address:
> 
> ```
> Mon May  8 21:02:45 2023 daemon.info xray[9144]: 2023/05/08 16:32:45 [Warning] transport/internet: failed to resolve ip > app/dns: returning nil for domain my.***.io > multierr: context deadline exceeded | context deadline exceeded |
> Mon May  8 21:02:45 2023 daemon.info xray[9144]: 2023/05/08 16:32:45 [Warning] transport/internet: failed to resolve ip > app/dns: returning nil for domain my.***.io > multierr: context deadline exceeded | context deadline exceeded |
> ```
> 
> This seems to be a DNS resolution problem. Setting the domain name in "DNS Settings -> Bypassed domain rules" are also not gonna help either. I also have another problem with DNS. If `xray-core` couldn't establish a successful connection to the proxy server for whatever reason, DNS resolution also breaks on my other network interfaces so I have to manually stop the `xray` service.

I have the same problem and the suggested RP helps solve it!

**Comment by yichya** [comment]
For anyone still encountering this issue, try following https://github.com/yichya/luci-app-xray/issues/389#issuecomment-1952849508
