### ISSUE TITLE
Frp client not response (offline) if xray server down

### ISSUE THREAD

**Issue by hqvv** [yichya/luci-app-xray#297]
Thank you for your great works.

I am using frpc and xray (fw4) in the same router and facing a problem that if xray server down, the frp client will get offline also.

it could be caused by the frp server is located at oversea vps, and the frp client can not connect to frp server through a bad xray configuration. 

I have tried to add frp server ip to Bypassed IP in Transparent Proxy Rules page 
and add its domain to Bypassed domain rules in DNS settings page.
But it does not work, the frp client still got offline once xray server down(or can not connected)

Please kindly help to give some guildance to fix this problem, thanks

**Comment by yichya** [comment]
Adding Frp server IP to `Bypassed IP` should be enough for your use case. 

If that doesn't work, run `nft list ruleset` when luci-app-xray is running, and find if your Frp server IP is in `set tp_spec_dst_bp`

**Comment by hqvv** [comment]
Thank you for your prompt support.
the issue was fixed by adding frp server ip to bypass list.

Not sure why it was not working before I submit this issue.
