### ISSUE TITLE
Errors occurred while installing version 2.0.0

### ISSUE THREAD

**Issue by kilofox** [yichya/luci-app-xray#298]
Environments:
- LuCI openwrt-22.03 branch (git-23.119.80898-65ef406) 
- openwrt-xray 1.8.1-1
- luci-app-xray-shared 2.0.0-1
- luci-app-xray-fw4 2.0.0-1

It seems there occurred some errors while installing luci-app-xray-fw4_2.0.0-1_all.ipk.

The submenu of Xray (firewall4) appeared after installation. But it shows an RPCError on the page /cgi-bin/luci/admin/services/xray_fw4:

> RPC call to uci/get failed with ubus code 6: 没有权限
>   at ClassConstructor.handleCallReply (http://192.168.1.1/luci-static/resources/rpc.js?v=git-23.119.80898-65ef406:15:3)

Here are the full installation logs:

Executing package manager
```
Installing luci-app-xray-fw4 (2.0.0-1) to root...
Installing kmod-nf-tproxy (5.10.161-1) to root...
Downloading https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/packages/kmod-nf-tproxy_5.10.161-1_mipsel_24kc.ipk
Installing kmod-nft-tproxy (5.10.161-1) to root...
Downloading https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/packages/kmod-nft-tproxy_5.10.161-1_mipsel_24kc.ipk
Configuring kmod-nf-tproxy.
Configuring kmod-nft-tproxy.
Configuring luci-app-xray-fw4.
```
Errors
```
xray[29214]: Generating Xray configuration files...
xray[29214]: Starting Xray from /usr/bin/xray
xray[29214]: Using procd_set_param limits nofile=8192 16384
xray[29214]: Setting dnsmasq and firewall for transparent proxy...
xray[29214]: # Generated dnsmasq configurations by luci-app-xray strict-order server=/#/127.0.0.1#5300 server=127.0.0.1#5300 server=127.0.0.1#5301 server=127.0.0.1#5302 server=127.0.0.1#5303
xray[29214]: Generating firewall4 rules...
xray[29214]: Triggering firewall4 restart...
[!] Section xray option 'reload' is not supported by fw4
[!] Section xray specifies unreachable path '/var/etc/xray.include', ignoring section
transparent-proxy-ipset[29471]: default gateway available at 172.xx.xx.xx
```

Could you give me some advice on how to resolve this issue?

**Comment by yichya** [comment]
Did you install this shared package at the same time?

<img width="328" alt="image" src="https://github.com/yichya/luci-app-xray/assets/3683052/06d9ed56-c9d3-4968-9851-e61796565ca3">

**Comment by kilofox** [comment]
Yes, the shared package has been installed. The fw4 package depends on it.

**Comment by yichya** [comment]
Please check if this file exists and its content is same as following:

```
root@OpenWrt:/usr/share/rpcd/acl.d# cat luci-app-xray.json
{
    "luci-app-xray": {
        "description": "Grant access to xray configurations",
        "read": {
            "uci": [
                "xray_fw4"
            ]
        },
        "write": {
            "uci": [
                "xray_fw4"
            ]
        }
    }
}
```

**Comment by yichya** [comment]
That is weird. Could you find the actual failed ubus request with Chrome DevTools?

* Press F12 when you see the error
* Refresh page
* Find the failed ubus request (use search box) and right click it -> Copy -> Copy as cURL (bash)

![image](https://github.com/yichya/luci-app-xray/assets/3683052/c6adbd26-f8e7-409e-a6dd-563138eaed81)

**Comment by kilofox** [comment]
Uh oh! The page /cgi-bin/luci/admin/services/xray_fw4 is normal now. It works. I didn't do any operation at all.
The settings of the old version are preserved.
The "Enable Transparent Proxy" option is checked. Maybe this is the reason.

**Comment by kilofox** [comment]
![fc7b0a6e86de947c63a0f9a13e6093ba](https://github.com/yichya/luci-app-xray/assets/1018625/e6453005-544b-4b0f-9a63-22cf920152be)
I found some HTML errors.

**Comment by yichya** [comment]
> I found some HTML errors.

That's a problem for LuCI, not this project and that field does not need any autofilling
