### ISSUE TITLE
any way to put xray in temp ?

### ISSUE THREAD

**Issue by firefoxOnFire** [yichya/luci-app-xray#303]
I have device with less storage. But I have enough temp space to install xray. 
Can I install this luci app to main storage and xray to temp ?? 
Or any workaround to make this work ??

**Comment by yichya** [comment]
Personally I would not recommend doing that because Xray itself needs a significant amount of memory especially with Geodata files. You could try building a firmware with Xray included instead.

**Comment by yichya** [comment]
If you insist, put xray binary under `/tmp` and change this field (write `/tmp/xray` in 'custom' and press Enter to confirm) should be enough

<img width="487" alt="image" src="https://github.com/yichya/luci-app-xray/assets/3683052/0668631d-2376-45e0-930e-e30c7e887ece">

**Comment by yichya** [comment]
> Problem is when i try to install ipk from release, it starts to download xray by itself. Which is causing problem. Thanks.

Try disconnecting from the Internet and installing with `--force-depends` to let opkg ignore that. Other dependencies like kmod-nft-tproxy still need to be installed.

Or if your device has USB port I'd suggest trying [extroot](https://openwrt.org/docs/guide-user/additional-software/extroot_configuration)

**Comment by hawshemi** [comment]
@firefoxOnFire I had this problem with my router.

You have to build `OpenWRT` with `xray-core` and `luci-app-xray` included. but note that `xray` itself uses a lot of RAM. I tested with 128Mb RAM with `tproxy` and direct routing for IR IPs and domains(+ad blocking). Just 2 clients could connect and use the router without bottlenecking the RAM and CPU.

**Comment by hawshemi** [comment]
I use the 'tproxy' in the `luci app xray` itself. I have GLinet AR750S.
