### ISSUE TITLE
域名路由策略设置为AsIs还是会把域名进行DNS解析为IP，请问如何解决

### ISSUE THREAD

**Issue by medunea** [yichya/luci-app-xray#309]
把域名路由策略设置为AsIs，可是我通过服务端日志进行查看，客户端还是会把域名解析为IP后转发给服务端。

我服务端同时也做了域名出口分流，用于通过不同的服务端进行解锁奈飞、ChatGPT等。

请问如何能不让客户端把域名进行解析为IP？

**Comment by medunea** [comment]
这是OpenWrt客户端日志中的一条，把chat.openai.com域名解析成了ip，客户端把ip转发到了服务端，导致服务端没办法识别到这条请求：

Fri Jun 30 04:13:50 2023 daemon.info xray[5473]: 2023/06/29 20:13:50 [Info] app/dns: UDP:8.8.4.4:53 got answer: chat.openai.com. TypeA -> [104.18.3.161 104.18.2.161] 157.154002ms

**Comment by medunea** [comment]
服务端我使用的是v2ray-core的docker，之前一直在使用clashX、v2rayNG进行使用，是可以进行正常的域名路由的。

v2ray-core的路由（routing）配置：

`{"domainStrategy":"AsIs","balancers":[{"tag":"raw_ip_balancer","selector":["laikayun"]},{"tag":"netfilx_balancer","selector":["netfilx_hk"]}],"rules":[{"type":"field","outboundTag":"direct","ip":["geoip:private"]},{"type":"field","outboundTag":"block","protocol":["bittorrent"]},{"type":"field","domain":["domain:openai.com","domain:intercom.io","domain:sentry.io","openai","geosite:openai"],"balancerTag":"raw_ip_balancer"},{"type":"field","domain":["geosite:netflix"],"balancerTag":"netfilx_balancer"}]}`

**Comment by yichya** [comment]
sniffing 开了没

**Comment by medunea** [comment]
> sniffing 开了没

是开启的，代理是一切正常的，只是服务端收到的请求是被解析成ip的，而不是域名

**Comment by yichya** [comment]
> 是开启的，代理是一切正常的，只是服务端收到的请求是被解析成ip的，而不是域名

那 Sniffing 下面那个 Route Only 开了嘛

**Comment by xiechangan123** [comment]
域名路由策略建议开启  IPOnDemand  你会感谢我的，之前也被dns折腾的要死。。。
