### ISSUE TITLE
怎么设置成白名单模式？

### ISSUE THREAD

**Issue by alfadb** [yichya/luci-app-xray#312]
请问怎么设置成白名单模式？
也就是说只有指定域名和IP走代理，其它全部直连。

**Comment by yichya** [comment]
默认情况下就是这样的。。

**Comment by alfadb** [comment]
我开了日志看，默认是走代理，一天跑掉20G流量……

**Comment by hqvv** [comment]
把你的 域名和 ip填在 Forwarded domain rules 和 Forwarded IP 就好了吧
他们分别在 dns setting 和 透明代理 页面

**Comment by alfadb** [comment]
> 

看这个生成的routing，如果没有匹配到域名或者IP，就会走tcp_outbound，这个指向的是代理

**Comment by yichya** [comment]
> 看这个生成的routing，如果没有匹配到域名或者IP，就会走tcp_outbound，这个指向的是代理 如果默认不走代理，那应该是direct才对

呃。你说的这种一般都被称为黑名单。。。这种模式很容易翻车，现在一般没啥人用了，所以没做支持。需要的话可以在 Bypassed 里面写个 0.0.0.0 然后把需要转发的 IP 段放到 Forwarded 里面

**Comment by alfadb** [comment]
> > 看这个生成的routing，如果没有匹配到域名或者IP，就会走tcp_outbound，这个指向的是代理 如果默认不走代理，那应该是direct才对
> 
> 呃。你说的这种一般都被称为黑名单。。。这种模式很容易翻车，现在一般没啥人用了，所以没做支持。需要的话可以在 Bypassed 里面写个 0.0.0.0/0 然后把需要转发的 IP 段放到 Forwarded 里面

那域名咋搞？比如我只允许google的域名走代理，其它全部直连

**Comment by yichya** [comment]
> 那域名咋搞？比如我只允许google的域名走代理，其它全部直连

域名可以试一下开 sniffing 然后 Forwarded 正常写，在 Bypassed 里面写一个 `.` 看看，不确定行

**Comment by alfadb** [comment]
> > 那域名咋搞？比如我只允许google的域名走代理，其它全部直连
> 
> 域名可以试一下开 sniffing 然后 Forwarded 正常写，在 Bypassed 里面写一个 `.` 看看，不确定行

不行，bypass的rule在forward之前，bypass通配了就到不了forward的rule

**Comment by yichya** [comment]
可以搭配新版的 FakeDNS 使用这个功能了。
