### ISSUE TITLE
HTTPS server - multiple users?

### ISSUE THREAD

**Issue by bogorad** [yichya/luci-app-xray#324]
I'm trying to set up a server with VLESS/Reality.

Is there a way to have multiple clients in "HTTPS Server" => "UserId / Password" field? AFAIU, it translates to settings => clients => id, which is an array in xray. I tried space-separated and comma-separated, but both result in one client. 

![image](https://github.com/yichya/luci-app-xray/assets/2777398/75d1b509-e616-4e7b-b262-e39847b1e495)

**Comment by yichya** [comment]
Currently not supported. Will be included in the next release.

**Comment by yichya** [comment]
This feature is added in v3.0.0
