### ISSUE TITLE
How to setup: Bypass All except list of domains

### ISSUE THREAD

**Issue by MrYadro** [yichya/luci-app-xray#326]
I want to setup my xray proxy routing this way: all traffic is direct but list of domains from dlc.dat I compiled myself is going through proxy.

<img width="1179" alt="image" src="https://github.com/yichya/luci-app-xray/assets/1587606/0e40e86c-c5fa-4a10-a2e8-9fc1b70e5c53">

Seems like it should work like that but it doesn't. I even tried to switch Default Ports Policy to Bypass in Transparent Proxy Rules tab. I tried to clear out all of domains in Bypassed domain rules thinking none = every but list in forward.

So I did more digging around from what I found here: https://xtls.github.io/document/level-1/routing-lv1-part2.html#_6-%E9%9C%B8%E4%B8%9A%E5%88%9D%E5%AE%9A-%E8%B7%AF%E7%94%B1%E8%A7%84%E5%88%99%E6%95%B4%E4%BD%93%E5%9B%9E%E9%A1%BE it should be achieved by removing all Bypassed domain rules:

[1-block] (None) --> [2-direct] (None) --> [3-proxy] (List of domains) --> [4-first-outbound] (Other domains)

First outbound is Direct but for some reason other domains still goes through proxy.

Thank you!

**Comment by KovAlex** [comment]
У вас получилось найти решение? тоже бьюсь над решением.

**Comment by yichya** [comment]
v3.0.0 Added FakeDNS feature. Disable Transparent proxy in core settings and add domains you want to proxy in FakeDNS tab.

**Comment by MrYadro** [comment]
So I updated to v3 did what you told me to do.

<img width="967" alt="image" src="https://github.com/yichya/luci-app-xray/assets/1587606/ad11dd5f-2edb-45b9-8905-572daa43b4bc">

And traffic still bypasses proxy.

<img width="1035" alt="image" src="https://github.com/yichya/luci-app-xray/assets/1587606/70a9be9e-dd30-4626-a3c9-ecf91090310a">

Did I make some mistakes or I did not understand something? Maybe I need to pass proxy ports anywhere in OpenWrt?

**Comment by yichya** [comment]
try `nslookup notifiarr.com` and check if it is correctly resolved to FakeDNS pool addresses (198.18.x.x)

**Comment by MrYadro** [comment]
LMAO, so what I did I enabled FakeDNS, enabled Transparent Proxy for the same lists, put Xray DNS Server Port into my adguard resolver and everything works now. Is it a right solution - maybe not, but it works, and I'm happy! Thank you!

**Comment by KovAlex** [comment]
You can show in the screenshots how it is configured?

**Comment by MrYadro** [comment]
@KovAlex please dm me on telegram t.me/mryadro and I will help you ASAP
