### ISSUE TITLE
使用FW3的opennwrt 如何编译

### ISSUE THREAD

**Issue by lcuwx2016** [yichya/luci-app-xray#328]

**Comment by yukeiyang** [comment]
fw4 是这样：
`$ make package/luci-app-xray/fw4/compile V=99`

fw3 替换下路径。

**Comment by yichya** [comment]
fw3 已经打算整个扬了，建议升级一下 OpenWrt，如果一定要用 fw3 的话其实跟 fw4 没啥区别，选中 OpenWrt 自己的 firewall3 就能看见 luci-app-xray-fw3
