### ISSUE TITLE
[Feature Request] 希望能支持多个LAN接口

### ISSUE THREAD

**Issue by iusearch** [yichya/luci-app-xray#334]
由于特殊原因，家里分出了单独的一个网段，单独的接口做IoT设备的接入，想问问有没有办法让多个接口都走代理。

**Comment by yichya** [comment]
https://github.com/yichya/luci-app-xray/tree/ipv6 这个分支已经支持了，不过改动很大，目前还没有完全稳定下来，过段时间才会 merge master，当然你现在也可以自己编译试试看

<img width="765" alt="image" src="https://github.com/yichya/luci-app-xray/assets/3683052/1afa37ef-135c-441e-b877-0e627bc482a7">
