### ISSUE TITLE
Major update v3.0.0 feedback

### ISSUE THREAD

**Issue by yichya** [yichya/luci-app-xray#336]
Version 3.0.0 comes with some major changes like IPv6 support, FakeDNS support and a thorough refactor of ucode scripts.

It is still not considered stable and may be very problematic so

* please try for new features and report any issues here before release
* if you still need old version please checkout [tag v2.1.2](https://github.com/yichya/luci-app-xray/tree/v2.1.2).

**Comment by sdandroid** [comment]
```
gen_config.uc     178   inboundTag: [...tproxy_tcp_inbound_tags, ...extra_inbound_global_tcp],
```
`tproxy_tcp_inbound_tags`  not found

**Comment by yichya** [comment]
> `tproxy_tcp_inbound_tags` not found

Fixed in #338

**Comment by xiechangan123** [comment]
Enable Sniffing 默认未选中，容易造成dns相关故障，排查费事
DNS Settings 快速dns 安全dns 默认DNS 默认填写成 XXXX:53，这是错的吧

**Comment by yichya** [comment]
> Enable Sniffing 默认未选中，容易造成dns相关故障，排查费事

luci-app-xray 正常的用法就不太推荐开 sniffing，尤其是后面支持了 FakeDNS 之后更没什么一定要用 sniffing 的需求了。


> DNS Settings 快速dns 安全dns 默认DNS 默认填写成 XXXX:53，这是错的吧

写不写端口都支持的。

**Comment by yichya** [comment]
#347 involves a breaking change about LAN interfaces. Please reconfigure the network interfaces used for transparent proxy here:

![image](https://github.com/yichya/luci-app-xray/assets/3683052/bef6175d-2ec4-40fb-ab20-77251dc6f72b)

**Comment by xiechangan123** [comment]
Devices to enable IPV6 tproxy   里面IPV6改为IPv6

**Comment by yichya** [comment]
> Devices to enable IPV6 tproxy 里面IPV6改为IPv6

https://github.com/yichya/luci-app-xray/commit/219ec0646ef5d879421a2f9a77c4f9f738b86c85 改版本号的时候一起改
