### ISSUE TITLE
2.12这个release支持docker container下的openwrt上运行吗？

### ISSUE THREAD

**Issue by 3xpert** [yichya/luci-app-xray#344]
在docker下跑[openwrt/rootfs:x86_64-openwrt-23.05](https://hub.docker.com/layers/openwrt/rootfs/x86_64-openwrt-23.05/images/sha256-4150c5a5f10454c29adb5161ee22dffa68c92b188b69a8b8c03d3548012e7e56?context=explore)，安装2.12 release, 无法代理流量，日志里无错误信息，看似一切运行正常。

**Comment by yichya** [comment]
那应该是不支持的。。。
