### ISSUE TITLE
突然发现默认所有设备都可以翻墙

### ISSUE THREAD

**Issue by hutozh** [yichya/luci-app-xray#345]
之前一直以为只有添加进lan列表里的可以翻，重装了软件才发现都可以翻。能不能改成只有添加了才能翻呢？不想让陌生人翻墙。

**Comment by tsanie** [comment]
黑名单模式，UI 上我也没发现比较方便的方式来达到这种效果，大致是需要 3.0 的版本，core 设置里 tcp/udp v4/v6 都禁用，然后在 preview 设置里添加 extra inbounds，然后在 lan hosts access control 中设置特定 mac 设备走 extra inbounds。

稍稍繁琐了一点，我是直接改的 nftable rules。

给 tp_spec_lan_re 链最后的 goto tp_spec_lan_dd 那行增加 ether saddr 的条件。
把 tp_spec_wan_fw 链中的 tproxy 判断去掉。

**Comment by yichya** [comment]
3.1.0 之前加一个吧。



> 不想让陌生人翻墙。

（有一说一就不应该把陌生人放进网络里来

**Comment by hutozh** [comment]
> （有一说一就不应该把陌生人放进网络里来

也不是真正的陌生人。就是家里来的客人还有其它不相关的网络设备直接直连，省的浪费资源。而且翻墙设备多了产生的流量也多。
之前用luci-app-shadowsocks有设置默认代理是直连还是代理，还可以排除特定端口，防止BT之类走代理。你这个我以为一样，一直都是设置LAN Hosts Access Control用的。

**Comment by yichya** [comment]
加了这个功能。没啥问题的话应该下周二就发 3.1.0 的 release 了。

**Comment by hutozh** [comment]
好的，我自己尝试编译，总是报错，还是等成品吧。

yichya QC ***@***.***> 于 2023年10月20日周五 16:07写道：
