### ISSUE TITLE
安装的时候一直卡在Configuring luci-app-xray

### ISSUE THREAD

**Issue by CatSamaDD** [yichya/luci-app-xray#35]
![image](https://user-images.githubusercontent.com/34727840/108357165-08649580-7228-11eb-9841-aa22bd790911.png)
一直卡在这，没下文了

**Comment by yichya** [comment]
啊这，尴尬，大概是上一个 commit 搞了一个死循环，我回头想想咋办

**Comment by yichya** [comment]
https://github.com/yichya/luci-app-xray/issues/46#issuecomment-842448599 应该处理了这个问题
