### ISSUE TITLE
小白求教：官网Openwrt安装后没有在luci菜单中显示

### ISSUE THREAD

**Issue by ganganray** [yichya/luci-app-xray#352]
Openwrt使用的是官网固件：[generic-ext4-combined.img.gz](https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-23.05.0-x86-64-generic-ext4-combined.img.gz)
Openwrt安装在N100软路由中的PVE上
直接在Openwrt中opkg install安装了luci-app-xray_3.1.0-1_all.ipk和luci-app-xray-status_3.1.0-1_x86_64.ipk这两个ipk文件。重启后luci菜单中还是找不到相关页面。另外，确认1.8.4版本的xray core已经安装好了。
请教大佬以上安装步骤哪里疏忽了？

**Comment by yichya** [comment]
贴一下安装过程的日志。

**Comment by ganganray** [comment]
经您提醒，我卸载重新安装后在luci菜单中出现了。怀疑是国内连Openwrt官方安装源有问题，部分没装好。这次把`/etc/opkg/distfeeds.conf`中的`downloads.openwrt.org`换成`mirrors.aliyun.com/openwrt`再用opkg安装就好了。抱歉打扰了。
