### ISSUE TITLE
目標模式不含有「%」。 停止。

### ISSUE THREAD

**Issue by w931018h** [yichya/luci-app-xray#36]
./scripts/feeds update -a的时候报错：
Create index file './feeds/xray.index'
/home/a/openwrt/feeds/xray.tmp/info/.files-packageinfo.mk:1: *** 目標模式不含有「%」。 停止。

**Comment by yichya** [comment]
直接 clone 到 package/extra 下面。package 下面没有 extra 的话就 mkdir 一个
