### ISSUE TITLE
Version 3.2.0 Feedback

### ISSUE THREAD

**Issue by yichya** [yichya/luci-app-xray#366]
Version 3.2.0 includes the following changes:

* Custom Configurations Hook (a replacement of the quite useless "Custom Configurations")
* Moving some features from preview to main luci application and hide preview by default
* Refactor of frontend files (to move some details out of `core.js` file)
* Some minor bugfixes

This version might not get released (no `.ipk` in Releases to download) because it may not be stable enough. Please report any issue encountered.

**Comment by yichya** [comment]
> OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256

This version is supported. If you build OpenWrt from source, make sure to select `fw4` as the firewall implementation.

**Comment by hutozh** [comment]
哪里下载3.2。自己编译的还是3.1.1。

**Comment by yichya** [comment]
> 哪里下载3.2。自己编译的还是3.1.1。

忘了改 Makefile 了 = = 先这样用着

**Comment by hutozh** [comment]
> 忘了改 Makefile 了 = = 先这样用着

外网访问和时间同步，还是不行。

**Comment by yichya** [comment]
> 外网访问和时间同步，还是不行。

时间同步还是按 #357 做，目前还没想好怎么针对 ntpd 做额外处理。外网访问。。。什么时候我有了环境再修吧。。。

**Comment by LitCcc** [comment]
![image](https://github.com/yichya/luci-app-xray/assets/36120072/73e77aeb-a719-497e-b621-28051a84d484)
打开浏览器第一次访问[exhent](https://exhentai.org/) 的时候会出现连接已重置，其他网站没有这个问题

**Comment by yichya** [comment]
> 打开浏览器第一次访问[exhent](https://exhentai.org/) 的时候会出现连接已重置，其他网站没有这个问题

试一下 FakeDNS

**Comment by yichya** [comment]
> i found that i can not edit,delete,add field GeoIP Direct Code List (IPv4) and GeoIP Direct Code List (IPv6) hopefully you can fix it.

Follow the directions there:

<img width="571" alt="image" src="https://github.com/yichya/luci-app-xray/assets/3683052/22b5f71e-4476-475b-ae0a-413adc3481d5">
