### ISSUE TITLE
安装的时候提示错误

### ISSUE THREAD

**Issue by w931018h** [yichya/luci-app-xray#37]
root@OpenWrt:/tmp# opkg install luci-app-xray_1.0.3-1_aarch64_cortex-a53.ipk
Installing luci-app-xray (1.0.3-1) to root...
Collected errors:
 * check_data_file_clashes: Package luci-app-xray wants to install file /etc/init.d/xray
        But that file is already provided by package  * xray-core
 * opkg_install_cmd: Cannot install package luci-app-xray.
另外我还装了passwall
软件是否无法同时与其他软件并存

**Comment by w931018h** [comment]
把xray-core卸载后又提示缺少xray-core依赖
再把xray-core装上去又说
check_data_file_clashes: Package luci-app-xray wants to install file /etc/init.d/xray
But that file is already provided by package * xray-core
直接把luci-app-xray.ipk里的/etc/init.d/xray删除后可以安装成功，但是网页端看不到，
如果直接把xraycore里的/etc/init.d/xray删掉用luci-app-xray.ipk的替代，我又怕passwall无法使用
所以这个软件可以与passwall并存吗？

**Comment by w931018h** [comment]
什么都没干 隔了一段时间 他在菜单里出来了 问题算是解决了

**Comment by yichya** [comment]
之前 xray-core 没有带自己的 init，所以当时还不冲突，这个之后我可能考虑一下把 init 脚本改个名字。
菜单看不见这个很奇怪……目前大概知道是 luci-indexcache 和 luci-modulecache 清不干净的原因，但咋处理还没想好
passwall 共存的话没试过，但是删掉 xray-code 自己的 init 肯定是不会影响 passwall 的

**Comment by w931018h** [comment]
现在菜单可以看见了（我把luci-app-xray的/etc/init.d/xray删除，并安装。用的xraycore的 init文件，等了很久自己冒出来的），但是启动程序后还是连不了外网（相当于没起作用）

**Comment by yichya** [comment]
如果你用 xray-core 自带的 init 文件的话那肯定是没用的。。。那个 init 文件不会配置 iptables 透明代理也不会改 dnsmasq 的配置，除了把 xray 拉起来之外啥也没做
