### ISSUE TITLE
I was confued on how to setting  up routing

### ISSUE THREAD

**Issue by davidw0374** [yichya/luci-app-xray#372]
I'm newbie on luci-app-xray, i studied it these 2 days ,I learned 3.2.1 ,luckily understood its logic. 
but for 3.3.1,  I was confued totally on how to set up xray routing,i open menu **Outbound Routing**, the interface is weird . where i put  on item "domain" such as "geosite:geolocation-!cn" ? and where i lay down "outboundtag" such as "my-vmess-tunnel"?
 Thanks for your passion on network  f r e e d o m.
![2024-01-10_17-47-20](https://github.com/yichya/luci-app-xray/assets/25239174/15f00812-f254-4bb4-99c2-d406bb7ac402)

**Comment by yichya** [comment]
> where i put on item "domain" such as "geosite:geolocation-!cn" ? and where i lay down "outboundtag" such as "my-vmess-tunnel"? 

Use FakeDNS.

**Comment by davidw0374** [comment]
Thank for your advice ,the routing Job done , and link is up, youtubes are charming, long live xray!

but still  a annoyed problem : it's important to troubleshooting by watching access.log and error.log ,but i can not setup the location of these files via luci interface , so should i create them  manually in config.json  ?

**Comment by yichya** [comment]
> it's important to troubleshooting by watching access.log and error.log ,but i can not setup the location of these files via luci interface , so should i create them manually in config.json ?

Just see OpenWrt System Log. 

![image](https://github.com/yichya/luci-app-xray/assets/3683052/2719857a-ebc1-4931-896f-1f000b88d39c)

If you really need to redirect logs add the following Custom Configurations Hook:

```js
return function(config) {
    config["log"]["error"] = "/tmp/xray.log";
    return config;
};
```

**Comment by davidw0374** [comment]
yes, the Custom Configurations Hook code works. thanks.
