### ISSUE TITLE
仅使用FakeDNS分流会存在缺陷

### ISSUE THREAD

**Issue by river1** [yichya/luci-app-xray#384]
某些应用（如Netflix）已经在应用内部设置了DNS（8.8.8.8），不通过xray的内置DNS查询，FakeDNS的分流会失效。
想了想，增加DNS服务器的反向代理，把DNS查询请求再转入Xray内置DNS是不是可以解决这个问题？

**Comment by river1** [comment]
增加一个Dokodemo door，连接到DNS出站，然后把53端口的流量全部转入应该也能做到

**Comment by yichya** [comment]
> 增加一个Dokodemo door，连接到DNS出站，然后把53端口的流量全部转入应该也能做到

#385 增加了 DNS 劫持
