### ISSUE TITLE
Passthrough DNS queries via local dnsmasq

### ISSUE THREAD

**Issue by DenMaxRus** [yichya/luci-app-xray#394]
Greetings! Using v3.4.0, is it possible to passthrough all (or some) DNS requests directly using local dnsmasq DNS servers via UI? I'm using multiple DNS servers and for now don't need XRAY to handle DNS traffic.

**Comment by yichya** [comment]
Unfortunately no. You need to manually edit `/etc/init.d/xray_core` to remove dnsmasq related things.
