### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by Yofo-me** [yichya/luci-app-xray#4]
编译时报错,提示`bash proxychains: command not found`
必须安装 `proxychains-ng`吗？我记得`proxychains-ng`是个代理软件啊，我本地电脑已经科学了的（用`Qv2ray`）
本地已经安装了`libproxychains-{dev,3,4}`这三个包

本地编译环境：
```Json
Ubuntu 20.04 LTS
Python 3.8
...
```

**Comment by yichya** [comment]
这个有一些尴尬，因为我编译用的环境不太好架全局梯子所以就这样写了。可以把 makefile 里面的 `proxychains` 全删掉，后续我这边可以判断一下有没有这个命令

**Comment by yichya** [comment]
加了一个配置可以控制这个行为，默认关，如果有已经配置好的 `proxychains` 可以打开，会自动使用
