### ISSUE TITLE
SDK has changed from xz to zst. Script tar unzip is not workable.

### ISSUE THREAD

**Issue by upsangel** [yichya/luci-app-xray#404]
Action build error:

`/home/runner/cache/sdk/openwrt-sdk-x86-64_gcc-13.2.0_musl.Linux-x86_64.tar.zst: Zstandard compressed data (v0.8+), Dictionary ID: None
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

Checked that Openwrt source SDK package has changed from xz to zst since 23.05.3 dated 22 Mar 2024.

**Comment by yichya** [comment]
#406
