### ISSUE TITLE
Xray startup failure with configuration deserialization error

### ISSUE THREAD

**Issue by ANsfesf** [yichya/luci-app-xray#407]
Hello, I have installed the latest version on Openwrt snapshot, getting theese error message logged:

daemon.info xray[3941]: Failed to start: main: failed to load config files: [/var/etc/xray/config.json] > infra/conf/serial: failed to decode config: /var/etc/xray/config.json > infra/conf/serial: failed to read config file at line 1 char 4227 > json: cannot unmarshal string into Go struct field REALITYConfig.outbounds.streamSettings.realitySettings.show of type bool

The value in config is the following: **"realitySettings": { "show": "1"**,

**Comment by yichya** [comment]
Thanks for your pull request #412 . I'm really busy these days to get into this.
