### ISSUE TITLE
手机连接WiFi叹号

### ISSUE THREAD

**Issue by hutozh** [yichya/luci-app-xray#409]
手机可以正常访问google，但是WiFi连接显示叹号。刚刷的linageos 20，WiFi叹号的情况下会走流量，需要手动关掉流量，才使用WiFi。

**Comment by yichya** [comment]
这种建议直接改手机上的那个网络检测地址

```bash
adb shell settings put global captive_portal_https_url https://connect.rom.miui.com/generate_204
adb shell settings put global captive_portal_http_url http://connect.rom.miui.com/generate_204
```

**Comment by hutozh** [comment]
> 这种建议直接改手机上的那个网络检测地址
> 
> ```shell
> adb shell settings put global captive_portal_https_url https://connect.rom.miui.com/generate_204
> adb shell settings put global captive_portal_http_url http://connect.rom.miui.com/generate_204
> ```

想偷懒不连电脑，现在已经改好了。

另外催更一下外网无法访问内网的问题吧！
