### ISSUE TITLE
请问这个luci怎么在openwrt的sdk里面编译？

### ISSUE THREAD

**Issue by 725216** [yichya/luci-app-xray#410]
openwrt-xray已经编译出来了，但是luci-app-xray 在里面不能显示？

 Symbol: DEFAULT_luci-app-xray [=DEFAULT_luci-app-xray]                  │  
  │ Type  : unknown                                                         │  
  │                                                                         │  
  │                                                                         │  
  │ Symbol: PACKAGE_luci-app-xray [=n]                                      │  
  │ Type  : tristate                                                        │  
  │ Prompt: luci-app-xray...................................... LuCI Suppor │  
  │   Defined at tmp/.config-package.in:1002                                │  
  │   Depends on: PACKAGE_firewall4 && (aarch64 || arm || i386 || i686 || m │  
  │   Location:                                                             │  
  │ (1) -> Extra packages                                                   │  
  │   Selects: PACKAGE_dnsmasq [=y] && PACKAGE_libpthread [=y] && PAC

**Comment by yichya** [comment]
没试过在 SDK 里面跑，看着贴出来的是缺 `firewall4`

如果没有额外的要求，建议直接用 GitHub Actions
