### ISSUE TITLE
Forward only certain domains/zones

### ISSUE THREAD

**Issue by TonyKatkov89** [yichya/luci-app-xray#415]
Hi there!
The app works great and allows to access the blocked sites. However it may make sense to bypass it for everything  what is not blocked in my country. I understand, adding them to "Forwarded domain rules" and setting "Routing Domain Strategy" to "IPOnDemand" should do the trick, but, by some reason it is still possible to access other blocked websites, besides the ones added to "Forwarded domain rules". Am I doing something wrong or such functionality is not available?
![img1](https://github.com/yichya/luci-app-xray/assets/121773672/cdbfdcb4-c1a1-48f9-822e-5333a52e6329)
![img2](https://github.com/yichya/luci-app-xray/assets/121773672/6e59766f-5136-42fa-94f1-d0a8e319699f)

**Comment by yichya** [comment]
If you want some "allow list only" mode, disable global servers and use FakeDNS only.

**Comment by TonyKatkov89** [comment]
Works like charm! Thank you a lot!

**Comment by KweezyCode** [comment]
> If you want some "allow list only" mode, disable global servers and use FakeDNS only.

what do you mean by "disable global servers"? where could i find it? and why have i to use fakedns? i don't understand how to configure it

**Comment by TonyKatkov89** [comment]
> > If you want some "allow list only" mode, disable global servers and use FakeDNS only.
> 
> what do you mean by "disable global servers"? where could i find it? and why have i to use fakedns? i don't understand how to configure it

You should leave empty TCP Server (IPv4), UDP Server (IPv4), TCP Server (IPv6) and UDP Server (IPv6) on the Global Settings Tab, since these parameters are global. Yes, you need to set up the parameters on the Fake DNS tab instead and use big blue Edit button to add domains you want to pass through your proxy.
