### ISSUE TITLE
xray服务开启后，子路由（192.168.6.0/24）开放的22端口无法被上级总路由（192.168.1.0/24）转发的公网请求访问

### ISSUE THREAD

**Issue by wxg4net** [yichya/luci-app-xray#416]
Package: luci-app-xray
Version: 3.4.1-1
如题。不开xray则一切正常。
开与不开xray，总路由（192.168.1.0/24）上面都是可以访问子路由22端口的
不清楚是什么nft规则影响的

**Comment by hqvv** [comment]
使用 bypass模式呢？ 只劫持 80 443 
<img width="397" alt="image" src="https://github.com/user-attachments/assets/8f863d42-5cf1-46cf-80a8-d56688549049">
