### ISSUE TITLE
礼问一个技术问题，关于如何将luci界面拆分到不同的 js 文件中

### ISSUE THREAD

**Issue by VergilGao** [yichya/luci-app-xray#417]
我最近正在写一个 openwrt 插件
https://github.com/VergilGao/openwrt-sblite/blob/dev/luci-app-sblite/root/www/luci-static/resources/view/sblite/main.js

最近发现界面越写代码行数越多，放在同一个文件里已经很难 debug 了，我想能不能把 js 文件拆分开，但是最后没有成功
我看到大佬的库做到了这一点：
https://github.com/yichya/luci-app-xray/blob/ff491ceb4e40fe6014a98a1262a2ad8ecc662937/core/root/www/luci-static/resources/view/xray/core.js#L8
但是我仿照大佬这个结构去写发现我拆分出来的 js 文件(fuctions.js)并没有生效， F12 查看后发现源代码只有 main.js 即主界面， fuctions.js 并没有下载，因为我目前没有编译，只是通过 scp 将界面代码上传到路由器，我是不是缺少了什么必要的步骤才导致了这个问题？
希望大佬能分享一下相关的心得，感谢！

**Comment by yichya** [comment]
没有什么额外步骤啊。。。就这样写

**Comment by VergilGao** [comment]
> 没有什么额外步骤啊。。。就这样写

那真是奇怪
我直接scp上传对应的js文件到对应的目录来测试，是需要我编译成ipk再安装才有效果吗？

**Comment by yichya** [comment]
要不你现在写成啥样你推个 branch 上来看看
