### ISSUE TITLE
LAN Hosts Access Control config file?

### ISSUE THREAD

**Issue by johnnyitd** [yichya/luci-app-xray#424]
Hello, thank you for your outstanding work. 
I would like to quickly enable/disable VPN on certain computers from terminal. Can you please tell where this file is located and what should you restart after editing?

**Comment by yichya** [comment]
See `/etc/config/xray_core` and edit `config lan_hosts`. Run `/etc/init.d/xray_core restart` afterwards.

**Comment by johnnyitd** [comment]
Thank you
