### ISSUE TITLE
[Xray is stopped]

### ISSUE THREAD

**Issue by RickScam** [yichya/luci-app-xray#426]
[Xray is stopped] Asset files check: geoip.dat 15.02 MB; geosite.dat 2.15 MB. Report issues or request for features [here](https://github.com/yichya/luci-app-xray).

**Comment by RickScam** [comment]
Completed
"在这里 https://github.com/Loyalsoldier/v2ray-rules-dat/releases/ 下载 geoip.dat 和 geosite.dat 放到 /usr/share/xray 下面。
不过你遇到的这个问题按说我之前是处理过的，如果没有这俩文件应该不至于起不来，大概是又写出 bug 了"

The response from LUCI-APP-XRAY "[Xray is stopped] Asset files check: geoip.dat 3.88 MB; geosite.dat 6.86 MB. Report issues or request for features."

**Comment by RickScam** [comment]
```
root@OpenWrt:~# /etc/init.d/xray_core status
active with no instances

```

**Comment by yichya** [comment]
Run `/etc/init.d/xray restart` and look for possible errors.

**Comment by RickScam** [comment]
```

xray[3917]: Resetting dnsmasq and firewall configurations...
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such process
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such process
xray[3917]: Flushing firewall4 rules...
xray[3917]: Triggering firewall4 restart...
Automatically including '/usr/share/nftables.d/table-pre/xray_core.nft'

```

**Comment by yichya** [comment]
Paste your `/etc/config/xray_core` here (and please remove private information like server addresses)

**Comment by RickScam** [comment]
`config general
	option transparent_proxy_enable '1'
	option xray_bin '/usr/bin/xray'
	option general_balancer_strategy 'random'
	option routing_domain_strategy 'AsIs'
	option transparent_default_port_policy 'bypassed'
	option loglevel 'warning'
	list tcp_balancer_v4 'cfg024a8f'
	option fast_dns '77.88.8.8'
	option secure_dns '9.9.9.9'
	list forwarded_domain_rules 'domain:themoviedb.org'
	option default_dns '77.88.8.8'
	list wan_fw_tcp_ports '80'
	list wan_fw_tcp_ports '443'
	list wan_fw_tcp_ports '853'
	list wan_fw_udp_ports '53'
	list wan_fw_udp_ports '443'

config servers
	option alias 'Testing'
	option server '??????????'
	option server_port '443'
	option username 'router'
	option password '??????????'
	option domain_strategy 'UseIP'
	option domain_resolve_dns_method 'tcp'
	option protocol 'vless'
	option vless_encryption 'none'
	option vless_tls 'reality'
	option vless_flow_reality 'xtls-rprx-vision'
	option vless_reality_fingerprint 'ios'
	option vless_reality_server_name 'yahoo.com'
	option vless_reality_public_key '?????????'
	option vless_reality_short_id '????????'
	option transport 'tcp'
	option tcp_guise 'none'
	option dialer_proxy 'disabled'

config fakedns
	list fake_dns_domain_names 'geosite:openai'
	list fake_dns_forward_server_tcp 'cfg024a8f'
	list fake_dns_forward_server_udp 'cfg024a8f'
	option fake_dns_balancer_strategy 'random'`

**Comment by RickScam** [comment]
``root@OpenWrt:~# /etc/init.d/xray_core  reload
xray[5657]: Resetting dnsmasq and firewall configurations...
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such process
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such process
xray[5657]: Flushing firewall4 rules...
xray[5657]: Triggering firewall4 restart...
Automatically including '/usr/share/nftables.d/table-pre/xray_core.nft'
``

**Comment by yichya** [comment]
Run `/usr/bin/xray version` and paste result here

**Comment by RickScam** [comment]
```
root@OpenWrt:~# /usr/bin/xray version
-ash: /usr/bin/xray: not found
root@OpenWrt:~#
```
Thanks for helping me find the bug. Apparently my router doesn't have enough memory to install all the packages. I will think about how to solve this...
Is it possible to install xray on temporary memory and create a script so that it is installed again on reboot...

**Comment by RickScam** [comment]
I built an openwrt build with all the necessary packages and deleted the unnecessary ones. My 8 MB of memory was enough and everything worked
