### ISSUE TITLE
No ipk files are generated and published to releases from Git Actions

### ISSUE THREAD

**Issue by guiguan** [yichya/luci-app-xray#437]
example: https://github.com/guiguan/luci-app-xray/releases/tag/3.5.0

tried tagging with v prefix, e.g. v3.5.0. Also didn't work

**Comment by yichya** [comment]
try #438

**Comment by guiguan** [comment]
now got: https://github.com/guiguan/luci-app-xray/actions/runs/12028239297/job/33530940081

**Comment by yichya** [comment]
Changed SDK name. Try it once again

**Comment by guiguan** [comment]
Thanks for the prompt replies. This works
