### ISSUE TITLE
路由无法访问

### ISSUE THREAD

**Issue by winds365** [yichya/luci-app-xray#46]
编译好，上传固件，路由器http://192.168.0.250无法访问
可以进ssh

**Comment by y9858** [comment]
一样的问题

**Comment by zzhhzt** [comment]
一样的问题，路由访问不了，我看ALC设置允许访问后，json里面的路由段ip地址格式似乎不对？

   `"routing": {
     "rules": [
       {
         "type": "field",
         "outboundTag": "direct",
         "ip": [
          "10.10.10.0\/8"
           "172.16.0.0\/12",
           "192.168.0.0\/16"
         ]
       }
     ],`

**Comment by zcracker** [comment]
直接把openwrt-xray和app-xray编译进21.02RC1的固件刷机后正常获取ip，但是无法访问luci

**Comment by yichya** [comment]
神奇。访问不了的表现是什么样的，贴个 chrome 的错误截图之类？如果有编译好的固件也可以发一下

**Comment by winds365** [comment]
> 神奇。访问不了的表现是什么样的，贴个 chrome 的错误截图之类？如果有编译好的固件也可以发一下

`无法访问此网站192.168.0.250 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED`
固件https://github.com/winds365/op/suites/2673910501/artifacts/58937130

**Comment by winds365** [comment]
内核5.10
service –status -all 卡在xray之前不显示
大多数服务stop状态，包括uhttpd
手动启动uhttpd服务，系统-启动项 刷新不出来，提示XHR request timed out

**Comment by yichya** [comment]
更新了一个参数控制 init 脚本启动时候的行为，如果起不来的话可以试试把这一项关掉，然后应该能有机会改配置文件
![image](https://user-images.githubusercontent.com/3683052/118520811-f59d2680-b76c-11eb-921a-e415e50a9a3d.png)

**Comment by yichya** [comment]
#77
