### ISSUE TITLE
请问该插件支持IPv6和全局代理吗？

### ISSUE THREAD

**Issue by WROIATE** [yichya/luci-app-xray#48]

**Comment by yichya** [comment]
ipv6 透明代理目前还不支持（主要是因为暂时没找到比较靠谱的 ipv6 geoip 以及需求不大），有计划做。
全局的话只要把 Transparent Proxy Rules 里面的 geoip code 设置成 unspecified 就行了。

**Comment by WROIATE** [comment]
> ipv6 透明代理目前还不支持（主要是因为暂时没找到比较靠谱的 ipv6 geoip 以及需求不大），有计划做。
> 全局的话只要把 Transparent Proxy Rules 里面的 geoip code 设置成 unspecified 就行了。

 好的，谢谢解答。关于IPv6代理目前我只知道passwall之前有beta版，使用的是[chnroute6](https://ispip.clang.cn/all_cn_ipv6.txt)，希望能给你在未来开发上带来一些帮助: )
