### ISSUE TITLE
编译好后，安装完，在网页端无法显示

### ISSUE THREAD

**Issue by jlzsss** [yichya/luci-app-xray#5]
安装以后，在网页端找不到xray的配置界面？

**Comment by yichya** [comment]
你的 openwrt 的版本是？

**Comment by jlzsss** [comment]
19.07

**Comment by yichya** [comment]
手头暂时没条件测，我这边是长期用最新的 master 的，这个包也是完全用的最新版的 luci 的 api，有可能是不兼容旧版的

**Comment by yichya** [comment]
这个应该是默认的配置文件没有正确带进 ipk 里面，配置加载不起来就会看不见 luci 界面，写了一个默认配置应该能解决问题
