### ISSUE TITLE
无法访问网络问题

### ISSUE THREAD

**Issue by wazzx** [yichya/luci-app-xray#53]
OP19.07.7 官方SDK 编译好luci和xray，从今年2月份起一直就是访问不了网络。我也不想吐槽了。大哥测试一下或者写一个教程，这样搞我们真的很难。

**Comment by yichya** [comment]
确实社畜比较忙，不过有问题的话可以贴一点日志之类的。

**Comment by wazzx** [comment]
![Snipaste_2021-06-27_18-15-12](https://user-images.githubusercontent.com/60512548/123551884-4eb59c80-d7a6-11eb-8218-eebe868cb2a7.png)

**Comment by wazzx** [comment]
编译的时候选择的是上面的 
`安装luci-app-xray
Installing luci-app-xray (1.0.9-2) to root...
Installing kmod-nfnetlink (4.14.221-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt7621/kmods/4.14.221-1-2e88863ccdd594fb8e842df3c25842ee/kmod-nfnetlink_4.14.221-1_mipsel_24kc.ipk
Installing kmod-ipt-ipset (4.14.221-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt7621/kmods/4.14.221-1-2e88863ccdd594fb8e842df3c25842ee/kmod-ipt-ipset_4.14.221-1_mipsel_24kc.ipk
Installing libmnl0 (1.0.4-2) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/packages/mipsel_24kc/base/libmnl0_1.0.4-2_mipsel_24kc.ipk
Installing libipset13 (7.3-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/packages/mipsel_24kc/base/libipset13_7.3-1_mipsel_24kc.ipk
Installing ipset (7.3-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/packages/mipsel_24kc/base/ipset_7.3-1_mipsel_24kc.ipk
Installing kmod-ipt-tproxy (4.14.221-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt7621/kmods/4.14.221-1-2e88863ccdd594fb8e842df3c25842ee/kmod-ipt-tproxy_4.14.221-1_mipsel_24kc.ipk
Installing iptables-mod-tproxy (1.8.3-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt7621/packages/iptables-mod-tproxy_1.8.3-1_mipsel_24kc.ipk
Installing ca-bundle (20200601-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.7/packages/mipsel_24kc/base/ca-bundle_20200601-1_all.ipk
Configuring kmod-nfnetlink.
Configuring kmod-ipt-tproxy.
Configuring libmnl0.
Configuring kmod-ipt-ipset.
Configuring libipset13.
Configuring ipset.
Configuring iptables-mod-tproxy.
Configuring ca-bundle.
Configuring luci-app-xray.

Errors
rm: can't remove '/var/etc/xray/*': No such file or directory
transparent-proxy-ipset[3675]: (Re)generationg Xray configuration files...
transparent-proxy-ipset[3803]: flush_ipset_rules (ignore any errors from RTNETLINK)
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such process
ip: RTNETLINK answers: No such process
transparent-proxy-ipset[3803]: ipset_init (ignore any errors from RTNETLINK)
transparent-proxy-ipset[3803]: gen_lan_host_ipset_entry
transparent-proxy-ipset[3803]: default gateway check 192.168.2.1
ipset v7.3: Unknown argument: `192.168.2.159'
Try `ipset help' for more information.
`

**Comment by wazzx** [comment]
不断出现的系统错误
Sun Jun 27 15:29:21 2021 daemon.notice procd: /etc/rc.d/S30xray: rm: can't remove '/var/etc/xray/*': No such file or directory
Sun Jun 27 15:29:21 2021 user.warn transparent-proxy-ipset[1135]: (Re)generationg Xray configuration files...
Sun Jun 27 15:29:21 2021 daemon.notice procd: /etc/rc.d/S30xray: transparent-proxy-ipset[1135]: (Re)generationg Xray configuration files...
Sun Jun 27 15:29:21 2021 daemon.notice procd: /etc/init.d/network: 'radio0' is disabled
Sun Jun 27 15:29:21 2021 daemon.notice procd: /etc/init.d/network: 'radio1' is disabled
Sun Jun 27 15:29:21 2021 daemon.notice procd: /etc/init.d/network: 'radio0' is disabled
Sun Jun 27 15:29:21 2021 daemon.notice procd: /etc/init.d/network: 'radio1' is disabled
Sun Jun 27 15:29:21 2021 daemon.info dnsmasq[1042]: exiting on receipt of SIGTERM

Sun Jun 27 15:29:26 2021 user.info transparent-proxy-ipset[1640]: flush_ipset_rules (ignore any errors from RTNETLINK)
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: transparent-proxy-ipset[1640]: flush_ipset_rules (ignore any errors from RTNETLINK)
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: ip: RTNETLINK answers: No such file or directory
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: ip: RTNETLINK answers: No such file or directory
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: ip: RTNETLINK answers: No such process
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: ip: RTNETLINK answers: No such process
Sun Jun 27 15:29:26 2021 user.info transparent-proxy-ipset[1640]: ipset_init (ignore any errors from RTNETLINK)
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: transparent-proxy-ipset[1640]: ipset_init (ignore any errors from RTNETLINK)
Sun Jun 27 15:29:26 2021 user.info transparent-proxy-ipset[1640]: gen_lan_host_ipset_entry
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: transparent-proxy-ipset[1640]: gen_lan_host_ipset_entry
Sun Jun 27 15:29:26 2021 user.info transparent-proxy-ipset[1640]: default gateway check 192.168.2.1
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: transparent-proxy-ipset[1640]: default gateway check 192.168.2.1
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: ipset v7.3: Unknown argument: `192.168.2.159'
Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: Try `ipset help' for more information.
Sun Jun 27 15:29:27 2021 kern.info kernel: [   24.611402] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down

Sun Jun 27 15:42:35 2021 daemon.info procd: Instance xray::instance1 s in a crash loop 11 crashes, 0 seconds since last crash
Sun Jun 27 15:43:20 2021 daemon.info dnsmasq[3203]: exiting on receipt of SIGTERM
Sun Jun 27 15:43:21 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Jun 27 15:43:21 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Jun 27 15:43:24 2021 daemon.info dnsmasq[3626]: started, version 2.80 cachesize 150
Sun Jun 27 15:43:24 2021 daemon.info dnsmasq[3626]: DNS service limited to local subnets
Sun Jun 27 15:43:24 2021 daemon.info dnsmasq[3626]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack no-ipset no-auth no-nettlehash no-DNSSEC no-ID loop-detect inotify dumpfile
Sun Jun 27 15:43:24 2021 daemon.info dnsmasq-dhcp[3626]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h

**Comment by yichya** [comment]
> Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: ipset v7.3: Unknown argument: `192.168.2.159`

可以贴一下 `ip addr` 命令的结果嘛。

**Comment by wazzx** [comment]
> > Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: ipset v7.3: Unknown argument: `192.168.2.159`
> 
> 
> 
> 可以贴一下 `ip addr` 命令的结果嘛。

192.168.2.1是我上级的路由器IP。这个192.168.2.159可能是分配的IP，我现在把那个路由器拿出来了。我重新再联通网络试一下吧

**Comment by wazzx** [comment]
root@OpenWrt:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN                                                                                                  qlen 1000
    link/ether 3a:56:e0:41:dd:aa brd ff:ff:ff:ff:ff:ff
    inet6 fe80::3856:e0ff:fe41:ddaa/64 scope link
       valid_lft forever preferred_lft forever
5: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qle                                                                                                 n 1000
    link/ether d4:ee:07:62:1f:e0 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 fdb9:cc25:1ee4:4::1/62 scope global dynamic
       valid_lft 42856sec preferred_lft 42856sec
    inet6 fd2b:2c94:abe::1/60 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::d6ee:7ff:fe62:1fe0/64 scope link
       valid_lft forever preferred_lft forever
6: eth0.1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master                                                                                                  br-lan state UP qlen 1000
    link/ether d4:ee:07:62:1f:e0 brd ff:ff:ff:ff:ff:ff
7: eth0.2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state U                                                                                                 P qlen 1000
    link/ether d4:ee:07:62:1f:e1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.159/24 brd 192.168.2.255 scope global eth0.2
       valid_lft forever preferred_lft forever
    inet6 fdb9:cc25:1ee4:0:d6ee:7ff:fe62:1fe1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fdb9:cc25:1ee4::921/128 scope global dynamic
       valid_lft 42856sec preferred_lft 42856sec
    inet6 fe80::d6ee:7ff:fe62:1fe1/64 scope link
       valid_lft forever preferred_lft forever
8: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan                                                                                                  state UP qlen 1000
    link/ether d4:ee:07:62:1f:e0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::d6ee:7ff:fe62:1fe0/64 scope link
       valid_lft forever preferred_lft forever
9: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan                                                                                                  state UP qlen 1000
    link/ether d0:ee:07:62:1f:e0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::d2ee:7ff:fe62:1fe0/64 scope link
       valid_lft forever preferred_lft forever

**Comment by wazzx** [comment]
> > Sun Jun 27 15:29:26 2021 daemon.notice procd: /etc/rc.d/S30xray: ipset v7.3: Unknown argument: `192.168.2.159`
> 
> 可以贴一下 `ip addr` 命令的结果嘛。

root@OpenWrt:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN qlen 1000
link/ether 3a:56:e0:41:dd:aa brd ff:ff:ff:ff:ff:ff
inet6 fe80::3856:e0ff:fe41:ddaa/64 scope link
valid_lft forever preferred_lft forever
5: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qle n 1000
link/ether d4:ee:07:62:1f:e0 brd ff:ff:ff:ff:ff:ff
inet 192.168.1.1/24 brd 192.168.1.255 scope global br-lan
valid_lft forever preferred_lft forever
inet6 fdb9:cc25:1ee4:4::1/62 scope global dynamic
valid_lft 42856sec preferred_lft 42856sec
inet6 fd2b:2c94:abe::1/60 scope global
valid_lft forever preferred_lft forever
inet6 fe80::d6ee:7ff:fe62:1fe0/64 scope link
valid_lft forever preferred_lft forever
6: eth0.1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP qlen 1000
link/ether d4:ee:07:62:1f:e0 brd ff:ff:ff:ff:ff:ff
7: eth0.2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state U P qlen 1000
link/ether d4:ee:07:62:1f:e1 brd ff:ff:ff:ff:ff:ff
inet 192.168.2.159/24 brd 192.168.2.255 scope global eth0.2
valid_lft forever preferred_lft forever
inet6 fdb9:cc25:1ee4:0:d6ee:7ff:fe62:1fe1/64 scope global
valid_lft forever preferred_lft forever
inet6 fdb9:cc25:1ee4::921/128 scope global dynamic
valid_lft 42856sec preferred_lft 42856sec
inet6 fe80::d6ee:7ff:fe62:1fe1/64 scope link
valid_lft forever preferred_lft forever
8: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP qlen 1000
link/ether d4:ee:07:62:1f:e0 brd ff:ff:ff:ff:ff:ff
inet6 fe80::d6ee:7ff:fe62:1fe0/64 scope link
valid_lft forever preferred_lft forever
9: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP qlen 1000
link/ether d0:ee:07:62:1f:e0 brd ff:ff:ff:ff:ff:ff
inet6 fe80::d2ee:7ff:fe62:1fe0/64 scope link
valid_lft forever preferred_lft forever

**Comment by wazzx** [comment]
hi老哥有空看一下不

**Comment by yichya** [comment]
![image](https://user-images.githubusercontent.com/3683052/133928334-bf0e6650-72fe-493f-be58-2bba219af372.png)

你用的 OpenWrt 版本是不是太老了？ipset 两年多前的版本了，这个脚本好像不兼容

**Comment by yichya** [comment]
上面这个已经合了，可以再试试看
