### ISSUE TITLE
gRPC server hostname用域名，连通不了

### ISSUE THREAD

**Issue by 3xpert** [yichya/luci-app-xray#56]
用IP地址可以，就是没法用CDN了
Thu Jul  1 17:29:42 2021 daemon.info xray[26515]: Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16 linux/amd64)
Thu Jul  1 17:29:42 2021 daemon.info xray[26515]: A unified platform for anti-censorship.
Thu Jul  1 17:29:42 2021 daemon.err xray[26515]: 2021/07/01 09:29:42 Using confdir from arg: /var/etc/xray
Thu Jul  1 17:29:42 2021 daemon.info xray[26515]: 2021/07/01 09:29:42 [Info] infra/conf/serial: Reading config: /var/etc/xray/config.json
Thu Jul  1 17:29:43 2021 daemon.info xray[26515]: 2021/07/01 09:29:43 [Warning] core: Xray 1.4.2 started
Thu Jul  1 17:29:48 2021 daemon.info xray[26515]: 2021/07/01 09:29:48 [Warning] [2881973896] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
Thu Jul  1 17:29:48 2021 daemon.info xray[26515]: 2021/07/01 09:29:48 [Warning] [2821008468] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
Thu Jul  1 17:30:30 2021 daemon.info xray[26515]: 2021/07/01 09:30:30 [Warning] [763116330] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:30 2021 daemon.info xray[26515]: 2021/07/01 09:30:30 [Warning] [3728363101] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:30 2021 daemon.info xray[26515]: 2021/07/01 09:30:30 [Warning] [1818778841] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:30 2021 daemon.info xray[26515]: 2021/07/01 09:30:30 [Warning] [366616993] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:30 2021 daemon.info xray[26515]: 2021/07/01 09:30:30 [Warning] [3355821010] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:30 2021 daemon.info xray[26515]: 2021/07/01 09:30:30 [Warning] [3509810396] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:30 2021 daemon.info xray[26515]: 2021/07/01 09:30:30 [Warning] [4180591674] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:31 2021 daemon.info xray[26515]: 2021/07/01 09:30:31 [Warning] [2369408987] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:31 2021 daemon.info xray[26515]: 2021/07/01 09:30:31 [Warning] [918285807] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:31 2021 daemon.info xray[26515]: 2021/07/01 09:30:31 [Warning] [192476369] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:31 2021 daemon.info xray[26515]: 2021/07/01 09:30:31 [Warning] [912033422] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:31 2021 daemon.info xray[26515]: 2021/07/01 09:30:31 [Warning] [3892498450] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:31 2021 daemon.info xray[26515]: 2021/07/01 09:30:31 [Warning] [3354535149] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:31 2021 daemon.info xray[26515]: 2021/07/01 09:30:31 [Warning] [3553588940] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:32 2021 daemon.info xray[26515]: 2021/07/01 09:30:32 [Warning] [392634192] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:32 2021 daemon.info xray[26515]: 2021/07/01 09:30:32 [Warning] [1305324350] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:32 2021 daemon.info xray[26515]: 2021/07/01 09:30:32 [Warning] [2601932659] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:32 2021 daemon.info xray[26515]: 2021/07/01 09:30:32 [Warning] [2230652889] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed
Thu Jul  1 17:30:32 2021 daemon.info xray[26515]: 2021/07/01 09:30:32 [Warning] [3486877939] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"] > common/retry: all retry attempts failed

**Comment by yichya** [comment]
看着是 io timeout 啊，这个更像是你的 cdn 问题

**Comment by 3xpert** [comment]
android上的v2rayNG用都没问题啊。
cdn会是什么问题呢？cloudflare的cdn，ssl-完全，gRCP-开，还有哪里没设的吗？

**Comment by yichya** [comment]
懂了。这个分支 #58 试一试

**Comment by 3xpert** [comment]
还是不行，问题还在
Sat Jul  3 22:53:20 2021 daemon.info xray[30541]: 2021/07/03 14:53:20 [Warning] core: Xray 1.4.2 started
Sat Jul  3 22:53:26 2021 daemon.info xray[30541]: 2021/07/03 14:53:26 [Warning] [3916820963] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
Sat Jul  3 22:53:26 2021 daemon.info xray[30541]: 2021/07/03 14:53:26 [Warning] [2971636556] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
Sat Jul  3 22:53:28 2021 daemon.info xray[30541]: 2021/07/03 14:53:28 [Warning] [1744265994] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: i/o timeout" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed

**Comment by yichya** [comment]
刚刚稍微又改了一下。
以及如果不过 cdn 但还是用域名连接会不会有问题呢

**Comment by 3xpert** [comment]
不过CDN，结果一样的。
应该是切到你指的分支了吧？
[root@yvm luci-app-xray]# git branch
* dnsmasq_upstream
  master

**Comment by yichya** [comment]
看一下 /tmp/dnsmasq.d/xray.conf 里面有没有跟你的 hostname 相关的配置？

**Comment by 3xpert** [comment]
有的
server=/mydomain.tk/114.114.114.114
server=/mydomain.tk/114.114.114.114
server=/#/127.0.0.1#5353

**Comment by yichya** [comment]
那很奇怪。。。
你要不顺便试试之前有问题的 xtls 用域名连接的那种方式看看是不是还有问题，我再想想哪里搞错了

**Comment by 3xpert** [comment]
Sat Jul  3 23:20:51 2021 daemon.info xray[2779]: 2021/07/03 15:20:51 [Warning] core: Xray 1.4.2 started
Sat Jul  3 23:20:57 2021 daemon.info xray[2779]: 2021/07/03 15:20:57 [Warning] [1832126434] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
Sat Jul  3 23:20:57 2021 daemon.info xray[2779]: 2021/07/03 15:20:57 [Warning] [598769193] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed

**Comment by yichya** [comment]
你的域名直接用 114.114.114.114 会不会解析不出来。。。
你把这个配置改成 119.29.29.29 或者 223.5.5.5 / 223.6.6.6 试试看

![image](https://user-images.githubusercontent.com/3683052/124359107-0d196b80-dc56-11eb-8d31-44c11aeea19e.png)

**Comment by 3xpert** [comment]
可以了 :)

**Comment by 3xpert** [comment]
@yichya 谢谢！
