### ISSUE TITLE
请教：system log说明了什么问题？

### ISSUE THREAD

**Issue by 3xpert** [yichya/luci-app-xray#62]
Fri Jul 23 22:07:10 2021 daemon.info xray[16292]: 2021/07/23 14:07:10 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:10 2021 daemon.info xray[16292]: 2021/07/23 14:07:10 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:11 2021 daemon.info xray[16292]: 2021/07/23 14:07:11 [Warning] [3841621821] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: lookup mydomain.com on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files dial tcp: operation was canceled] > common/retry: all retry attempts failed
Fri Jul 23 22:07:11 2021 daemon.info xray[16292]: 2021/07/23 14:07:11 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:11 2021 daemon.info xray[16292]: 2021/07/23 14:07:11 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:12 2021 daemon.info xray[16292]: 2021/07/23 14:07:12 [Warning] proxy/dns: failed to dial outbound connection > listen udp 0.0.0.0:0: socket: too many open files
Fri Jul 23 22:07:12 2021 daemon.info xray[16292]: 2021/07/23 14:07:12 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:12 2021 daemon.info xray[16292]: 2021/07/23 14:07:12 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:12 2021 daemon.info xray[16292]: 2021/07/23 14:07:12 [Warning] [3577707651] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: lookup mydomain.com on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files dial tcp: operation was canceled] > common/retry: all retry attempts failed
Fri Jul 23 22:07:13 2021 daemon.info xray[16292]: 2021/07/23 14:07:13 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:13 2021 daemon.info xray[16292]: 2021/07/23 14:07:13 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:13 2021 daemon.info xray[16292]: 2021/07/23 14:07:13 [Warning] [4064023648] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: lookup mydomain.com on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files] > common/retry: all retry attempts failed
Fri Jul 23 22:07:14 2021 daemon.info xray[16292]: 2021/07/23 14:07:14 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:14 2021 daemon.info xray[16292]: 2021/07/23 14:07:14 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:15 2021 daemon.info xray[16292]: 2021/07/23 14:07:15 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:15 2021 daemon.info xray[16292]: 2021/07/23 14:07:15 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:16 2021 daemon.info xray[16292]: 2021/07/23 14:07:16 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:16 2021 daemon.info xray[16292]: 2021/07/23 14:07:16 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:17 2021 daemon.info xray[16292]: 2021/07/23 14:07:17 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:17 2021 daemon.info xray[16292]: 2021/07/23 14:07:17 [Warning] [3847464710] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: lookup mydomain.com on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files] > common/retry: all retry attempts failed
Fri Jul 23 22:07:17 2021 daemon.info xray[16292]: 2021/07/23 14:07:17 [Warning] [177433344] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: lookup mydomain.com on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files] > common/retry: all retry attempts failed
Fri Jul 23 22:07:17 2021 daemon.info xray[16292]: 2021/07/23 14:07:17 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files
Fri Jul 23 22:07:18 2021 daemon.info xray[16292]: 2021/07/23 14:07:18 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1080: accept4: too many open files

**Comment by yichya** [comment]
这我也偶尔会遇到，重启 xray 就行了，但实际原因感觉就未解之谜。。。

**Comment by 3xpert** [comment]
谢谢！
