### ISSUE TITLE
编译出的IPK在19.07上运行，需要luci-compat提供lua支持

### ISSUE THREAD

**Issue by 7th-heaven** [yichya/luci-app-xray#64]
按照教程自行编译后，在19.07上跑。
安装一切正常，但是打开xray页面一直提示错误。
后来经过大神指点，需要安装luci-compat包来提供lua支持。
希望后面和我一样的小白能够顺利用上。

**Comment by yichya** [comment]
按说是没这回事的。

不知道 tg 群里那个图是不是你发的。。。看着完全不像我这个插件
![telegram-cloud-document-5-6086626501392859925](https://user-images.githubusercontent.com/3683052/129554352-af879d90-280c-4f25-bf9d-7992c1097c5c.jpg)

**Comment by 7th-heaven** [comment]
> 按说是没这回事的，这个仓库完全不依赖 luci-compat。
> 
> 不知道 tg 群里那个图是不是你发的。。。但这个看着完全不是这个仓库的样子
> 
> > ![telegram-cloud-document-5-6086626501392859925](https://user-images.githubusercontent.com/3683052/129554352-af879d90-280c-4f25-bf9d-7992c1097c5c.jpg)
> 

我确实在发issue的那天在某个tg群发过求助。当时还有另一位参与讨论这说，可能是下面截图中的lua残留导致的。具体不是很懂。不过安装后确实可以打开页面了。![Screenshot_2021-08-17-03-31-32-218_com.github.android.jpg](https://user-images.githubusercontent.com/35399635/129619593-1104ae4d-cbb0-4a42-850d-0d7fe936d94e.jpg)

**Comment by 7th-heaven** [comment]
我天亮再检查一下看那个编译源代码来自于哪里。

**Comment by 7th-heaven** [comment]
第一次自己编译，没啥概念，检查了之前用的命令，发现确实搞错了。不是这个源，抱歉造成困扰。
