### ISSUE TITLE
 RTNETLINK issue

### ISSUE THREAD

**Issue by yukeiyang** [yichya/luci-app-xray#66]
1. 安装 luci-app-xray 过程中会出现  RTNETLINK 错误提示。

ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such process
ip: RTNETLINK answers: No such process

2. 配置好 Xray Servers 后，luci-app-xray 运作正常，可科学上网。 
> (Server Hostname 设置为 server ip 才能正常使用)

3. 但运行 service xray restart  命令，可复现安装过程中的 RTNETLINK  的 issue。输出如下：

root@OpenWrt:~# service xray restart
xray[6467]: Resetting dnsmasq and firewall configurations...
transparent-proxy-ipset[6586]: flush_ipset_rules (ignore any errors from RTNETLINK)
ip: RTNETLINK answers: No such process
xray[6467]: (Re)generationg Xray configuration files...
xray[6467]: Setting dnsmasq and firewall for transparent proxy...
xray[6467]: # Generated dnsmasq configurations by luci-app-xray server=/203.135.249.213/114.114.114.114 server=/203.135.249.213/114.114.114.114 server=/#/127.0.0.1#5353
transparent-proxy-ipset[6746]: flush_ipset_rules (ignore any errors from RTNETLINK)
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such file or directory
ip: RTNETLINK answers: No such process
ip: RTNETLINK answers: No such process
transparent-proxy-ipset[6746]: ipset_init (ignore any errors from RTNETLINK)
ip: RTNETLINK answers: File exists
transparent-proxy-ipset[6746]: gen_lan_host_ipset_entry
transparent-proxy-ipset[6746]: default gateway check 192.168.1.1

虽然使用正常，仍然对此 issue 不放心。请问如何修复？

**Comment by yichya** [comment]
`transparent-proxy-ipset[6746]: flush_ipset_rules (ignore any errors from RTNETLINK)`

这里日志上已经提过，可以忽略 RTNETLINK 的错误。具体是在初始化 ipset 的时候会先清空已有的 ipset，如果是第一次启动的话这个删除就会报类似错误，是正常的
