### ISSUE TITLE
https server 这个 tab 的场景用途是什么？

### ISSUE THREAD

**Issue by yukeiyang** [yichya/luci-app-xray#67]
我完整配置了 xray, 已正常成功运作。但有一个 tab 设置页 - https server - 没明白主要用在什么场景下。
可否指点一二？ 感谢。

**Comment by yukeiyang** [comment]
该 Tab 页描述文字说，用于 inbound 且同时用于反向代理， 没太明白具体场景。

**Comment by yichya** [comment]
作为一个 Xray 的服务端（inbound）的同时，也可以做为 https 服务器反向代理 http 请求。
