### ISSUE TITLE
遇到 #52 中同样问题，Server Hostname 填入域名会陷入死循环，填入 ip 则正常

### ISSUE THREAD

**Issue by yukeiyang** [yichya/luci-app-xray#68]
#52 
@yichya  引述你的话如下：

> 看了几个类似 case，目前看通过域名连接到服务端的方式可能还是有些不稳定（解析的时候可能出现死循环）。
> 非常离谱的是我个人就没遇到过这种问题。。。
> 可以试试不通过域名改为通过 ip 连接上去，域名解析死循环的问题我再想想有没有一劳永逸的办法解决掉。

我遇到同样的问题。想问下，

1. 使用 ip 会不会有性能上的损失？
2. 抑或会不会有被 Wall 更易特征侦测的可能？

感谢。

**Comment by yukeiyang** [comment]
**奇怪的是，**
使用 v2ray | Vmess TLS Websocket 服务端节点时，Server Hostname 填入域名则可正常使用。
使用 xray | Vless xtls direct 服务端节点时，Server Hostname 填入域名则不能正常使用，只能填入 ip.

**背景信息**
这两个节点，我都使用的是 xray | v2ray 一键脚本  |   https://v2raytech.com/xray-one-click-script/

`$ bash <(curl -sL https://s.hijk.art/xray.sh)`

**Comment by yukeiyang** [comment]
issue 的原因已找到，是一键脚本的问题。我换用 https://github.com/wulabing/Xray_onekey 的一键脚本后，一切正常。

**Comment by yichya** [comment]
> 1. 使用 ip 会不会有性能上的损失？

性能大概会更好一点

> 2. 抑或会不会有被 Wall 更易特征侦测的可能？

如果正确配置了 SNI 就可以认为没区别，insecure 的话就不确定了
