### ISSUE TITLE
DNS 使用 dns over https 时，哪里可以设置 hosts 以避免出现  resolve itself 的循环问题

### ISSUE THREAD

**Issue by yukeiyang** [yichya/luci-app-xray#72]
**1. 出现以下 issue，可能需要设置 hosts，哪里可以设置呢？**
`[Error] app/dns: DOH//dns.dns-over-https.top tries to resolve itself! Use IP or set "hosts" instead.`

**2. 以下 warning 是否是由 ipv6 引起，我尝试将 ipv6 关闭后，仍然有此提示，请问可以怎么消除？**
`Thu Sep  9 08:14:12 2021 daemon.info xray[5253]: 2021/09/09 00:14:12 [Warning] proxy/dns: failed to dial outbound connection > address https://dns.dns-over-https.top/dns-query:53: too many colons in address`

**Comment by yukeiyang** [comment]
反复测试后，发现这两个 issues 皆因启用 doh (dns over https) 所导致，DNS 填入 ip 地址时，这两个 issues 就会消失。但 dns 使用 IP 会被探测并封锁，使用 doh 似乎已成为刚需。

**Comment by yukeiyang** [comment]
反复测试后，发现 3 个 issues:
1. Fast DNS 填入 doh (dns over https) 后，网络不能联通，无法上网。
2. 使用譬如 https://dns.dns-over-https.top/dns-query   等 doh  地址，会有  [Error] app/dns: DOH//dns.dns-over-https.top tries to resolve itself! Use IP or set "hosts" instead. 问题。
3. 使用 doh，会出现如下 warning:  [Warning] proxy/dns: failed to dial outbound connection > address https://dns.dns-over-https.top/dns-query:53: too many colons in address

**Comment by yukeiyang** [comment]
实测近年来使用 ip dns 方式，因为明文发送的原因，The Wall 已能应对。故近年来严重封堵网络环境中会高度依赖 DoH。

Fast DNS | Secure DNS | Default DNS 三者皆使用 dns over https 地址，能有效正常科学上网, 但需能定义 hosts 以解决 DoH 域名的自身解析问题。

当然使用 https://8.8.8.8/dns-query 等等的 ip ssl 会无 resolve itself 的问题，但 8.8.8.8 此类 ip 往往被封堵了。

大家一般采用自配 DoH server 来解决这个问题，但 SSL 证书一般都针对 domain 发放，针对 ip 地址的 ssl 证书是极其难于获取的。

也就是说，现在最佳的方式是，所有 Fast DNS | Secure DNS | Default DNS  查询都交给 DoH 处理，但需要 xray 能自行设置 hosts 以解决 resolve itself 的问题。

**Comment by yichya** [comment]
虽然我觉得你的用法并不是最佳的（之前有提过，比较推荐的做法是 Fast DNS 写一个 114.114.114.114 这种国内的，Secure 和 Default 写 8.8.8.8 这种海外的，然后海外 DNS 请求实际都会被 Xray 转发出去，也就不存在明文发送被 GFW 抢答的问题）。。。

如果只是想改 Hosts 的话，自己改一下 dnsmasq 的配置

![image](https://user-images.githubusercontent.com/3683052/132972079-6a342b3f-bf7e-4252-a819-c15e58247782.png)

但对这个 luci 来说其实也是有必要做的，方法大概会是启动的时候顺便改一下 dnsmasq 的配置，最近太忙了，后面搞搞看

**Comment by yukeiyang** [comment]
@yichya 感谢回复。

1. openwrt 侧修改 dnsmaq hostname 的确是一个办法。
2. 测试了两个月，出问题的是 Fast DNS。
3. 重度科学上网环境下，114.114.114.114 会稳定运行一段时间，然后这个 DNS 就会废了。
4. 猜测是被针对了，腾讯的 119.29.29.29 也有这个问题。
5. 然后就需要换国内 Public DNS IP，但国内提供这个公共 DNS 服务的大概就 10 家左右，总有用完的时候。

我的最终解决方案是，自配 DNS Server 来替换 114.114.114.114。
目前自配 DNS 采用 Adguard Home 搭建，截止今天运作正常。看看未来何如。

**Comment by yukeiyang** [comment]
不过， Fast DNS 现在目测填入 DoH 地址，就会无法连接 internet, 所以我另外自配的这台 DNS Server 没开启 DoH，而是采用 UDP IP 模式。

**Comment by yukeiyang** [comment]
不知 Fast DNS 现在不能使用 DoH 是不是一个 bug.

**Comment by yukeiyang** [comment]
回报，openwrt 修改 dnsmaq hostnames 的方法经测试，仍然不能解决 [Error] app/dns: DOH//dns.dns-over-https.top tries to resolve itself! Use IP or set "hosts" instead. 问题。

**Comment by yichya** [comment]
> 3. 重度科学上网环境下，114.114.114.114 会稳定运行一段时间，然后这个 DNS 就废了。

你说的「废了」是指什么现象？

**Comment by yichya** [comment]
> 不过， Fast DNS 现在目测填入 DoH 地址，就无法连接 internet。
> 所以我另外自配的这台 DNS Server 没开启 DoH，而是采用 UDP IP 模式。

之前直接合了的那个 #69 还是有些问题的，因为 Fast DNS 和 Default DNS 因为涉及到 Xray 之外的配置（比如 Fast DNS 会拿去给 dnsmasq 用），目前就是没有办法填 DoH 的，只能写 IP，这个暂时改回去了。

**Comment by yukeiyang** [comment]
也就是说，使用 114.114.114.114 较长一段时间后，Fast DNS 使用这个 IP 会被 block, 而无法上网。119.29.29.29 也有这个问题，不过程度没这么严重。

**Comment by yukeiyang** [comment]
我猜测有部分漏网的 GFW 封堵列表中的 domains 总会有持续向 114.114.114.114 请求解析的情形，累计到一定次数后，墙内的 DNS 譬如 114.114.114.114 抑或腾讯 DNS 阿里 DNS 会屏蔽其它请求。

**Comment by yukeiyang** [comment]
目测现在唯一稳定的方法是，自配一个 IP 类的 DNS Server，供 Fast DNS 使用。

**Comment by yukeiyang** [comment]
不过真心说，你开发的这个 luci-app-xray 真的很赞。

1. xray 真的很快，比我之前使用 luci-app-clash 快太多了，当然这不是 luci-app-clash 的锅，是 xray 之 vless xtls 的确快很多。
2. 你的这个 luci-app-xray 的确比之前 clash 诸多 app 要简洁优雅许多。
3. 当然稳定性也是  luci-app-xray 非常大的优点。

**Comment by yukeiyang** [comment]
深圳移动宽带，500M带宽，我采用软路由，目前可以跑到 580M的带宽。

关键是，luci-app-xray 加持的科学上网，连接 Youtube 可以达到 220M 的平均带宽。

Apple TV 上播放 4K 视频那叫一个流畅。

**Comment by yichya** [comment]
> 也就是说，使用 114.114.114.114 较长一段时间后，Fast DNS 使用这个 IP 会被 block, 而无法上网。119.29.29.29 也有这个问题，不过程度没这么严重。

具体一点呢，这个 block 是说解析完全没结果，还是被污染了？

**Comment by yichya** [comment]
> 我猜测有部分漏网的 GFW 封堵列表中的 domains, 总会有持续向 114.114.114.114 请求解析的情形，累计到一定次数后，墙内的 DNS 譬如 114.114.114.114 抑或腾讯 DNS 阿里 DNS 会屏蔽其它请求。

实话说你说的这个事情我从来没遇到过。。。我就平平无奇联通用户，宽带或者 4g 都没见过这种情况

**Comment by yukeiyang** [comment]
家里的 notebook 使用 windows, 没安装 dnslookup 调试工具，没进一步测试到底是 block 还是被污染了。

高概率预估是DNS 服务商污染了，因为换个其它 DNS 就好了。

**Comment by yichya** [comment]
> 家里的 notebook 使用 windows, 没安装 dnslookup 调试工具，没进一步测试到底是 block 还是被污染了。
> 
> 高概率预估是DNS 服务商污染了，因为换个其它 DNS 就好了。

最好还是能确认一下，因为这个现象完全是预期外的，明确一点比较好彻底解决

**Comment by yichya** [comment]
我好像知道了。。。你看一下你的 dnsmasq 的版本是不是 2.86，这个版本似乎有点行为上的变化，我这边今天突然发现这里开始不对了

![image](https://user-images.githubusercontent.com/3683052/133916811-081b8186-5494-419f-940d-9d2aa035586b.png)

**Comment by yukeiyang** [comment]
我的 dnsmasq 版本是 2.85
![image](https://user-images.githubusercontent.com/6512594/133917071-51015149-eb47-49df-80c4-07c47a4fd8f5.jpeg)

**Comment by yichya** [comment]
辛苦帮看一下这两个地方

1. 这个页面最下面的两个选项 `Strict Order` 和 `All Servers`

![image](https://user-images.githubusercontent.com/3683052/133917116-d752cf4d-35d9-408e-a96d-40f1bb1f9a0e.png)

2. dnsmasq 启动的时候的日志，127.0.0.1#5353 出现的位置

![image](https://user-images.githubusercontent.com/3683052/133917162-88841435-0566-4f8f-b1de-cdf12e0532ec.png)

**Comment by yukeiyang** [comment]
Okay, I will now

**Comment by yukeiyang** [comment]
我的默认设置如图。![image](https://user-images.githubusercontent.com/6512594/133917272-dd0b0b4d-1eec-44e5-9504-d16eb4f82a48.jpeg)

**Comment by yukeiyang** [comment]
![image](https://user-images.githubusercontent.com/6512594/133917408-dab70f45-55d3-4fc5-8d07-ec1d670cc586.jpeg)

**Comment by yichya** [comment]
![image](https://user-images.githubusercontent.com/3683052/133917498-a24be4ca-f23b-4ac4-afa5-2b9eb7adff01.png)

这个果然变了。。。又要头疼了

你可以试试钩上上面的 Strict Order，然后 Fast DNS 还是正常写 114.114.114.114，Default DNS 还是写比如 8.8.8.8 或者 4.2.2.1 这种海外的，然后跑几天看看还有没有那种被 block 的情况

**Comment by yukeiyang** [comment]
Okay, I will try now.

**Comment by yukeiyang** [comment]
勾选 Strict Order, 然后 114.114.114.114 填 Fast DNS， 网络不通。

**Comment by yukeiyang** [comment]
114.114.114.114 应该是 block 了。

**Comment by yukeiyang** [comment]
119.29.29.29 部分残了，我倒是可以填 119.28.28.28 测试几天看看。

**Comment by yichya** [comment]
> 勾选 Strict Order, 然后 114.114.114.114 填 Fast DNS， 网络不通。

这个不通的表现是啥？

**Comment by yukeiyang** [comment]
我看看能不能安装下 dnslookup 组件到 Windows, 然后查下。

**Comment by yukeiyang** [comment]
C:\Windows\system32>dnslookup cloudbreakthrough.tk 114.114.114.114
dnslookup v1.4.9
2021/09/19 14:31:45 Cannot make the DNS request: read udp 192.168.100.172:65280->114.114.114.114:53: i/o timeout

**Comment by yukeiyang** [comment]
1.1.1.1 则正常。如下：

C:\Windows\system32>dnslookup cloudbreakthrough.tk 1.1.1.1
dnslookup v1.4.9
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 19598
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;cloudbreakthrough.tk.  IN       A

;; ANSWER SECTION:
cloudbreakthrough.tk.   300     IN      A       103.135.250.136

**Comment by yukeiyang** [comment]
测试是在 Fast DNS 填写其它 dns ip 非 114.114.114.114 时进行的。

**Comment by yukeiyang** [comment]
显然 114.114.114.114 端 block 了我的查询。

**Comment by yichya** [comment]
> C:\Windows\system32>dnslookup cloudbreakthrough.tk 114.114.114.114
> dnslookup v1.4.9
> 2021/09/19 14:31:45 Cannot make the DNS request: read udp 192.168.100.172:65280->114.114.114.114:53: i/o timeout

啊这。。。。。。。。。。。。。

这样，你看一下这个文件，直接用你的宽带运营商给的 DNS 或者上级路由发下来的 DNS 填进 Fast DNS 试试看

![image](https://user-images.githubusercontent.com/3683052/133918061-24bd6751-10e5-49e7-9408-acb27bbe41c0.png)

**Comment by yukeiyang** [comment]
Okay

**Comment by yukeiyang** [comment]
root@OpenWrt:/tmp/resolv.conf.d# cat resolv.conf.auto
# Interface wan
nameserver 192.168.1.1
# Interface wan6
nameserver fe80::1%eth0

**Comment by yichya** [comment]
那就在 Fast DNS 上写 192.168.1.1

**Comment by yukeiyang** [comment]
填写 192.168.1.1 可正常上网及出墙。 但 dnslookup 使用 114.114.114.114 仍然不通。

```
C:\Windows\system32>dnslookup cloudbreakthrough.tk 114.114.114.114
dnslookup v1.4.9
2021/09/19 14:45:32 Cannot make the DNS request: read udp 192.168.100.172:61961->114.114.114.114:53: i/o timeout

```
```
C:\Windows\system32>dnslookup cloudbreakthrough.tk 192.168.1.1
dnslookup v1.4.9
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 62124
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;cloudbreakthrough.tk.  IN       A

;; ANSWER SECTION:
cloudbreakthrough.tk.   519     IN      A       103.135.250.136
```

**Comment by yichya** [comment]
> 填写 192.168.1.1 可正常上网及出墙。 但 dnslookup 使用 114.114.114.114 仍然不通。

那可能真的是你的网络环境比较神奇。。。

你可以就用着 192.168.1.1，这个其实是最推荐的，因为最快（没有自动做的原因是搞起来很麻烦）

**Comment by yukeiyang** [comment]
需要勾选  Strict Order ？

**Comment by yichya** [comment]
> 需要勾选 Strict Order ？

2.85 不知道需不需要勾，2.86 不勾大概是有问题了。你可以都试试看

**Comment by yukeiyang** [comment]
@yichya 我重新编译后的 ipk 文件，请问在已安装过 luci-app-xray 的机器上reinstall 的标准做法是怎样的？

**Comment by yichya** [comment]
> @yichya 我重新编译后的 ipk 文件，请问在已安装过 luci-app-xray 的机器上reinstall 的标准做法是怎样的？

我一般都是直接重新整个编译一遍 openwrt 的。这个正常就该怎么装就怎么装就是了。。。应该没啥特别的

**Comment by yukeiyang** [comment]
@yichya I see, Thank you.

我想可能的方法:

opkg remove luci-app-xray 
然后
opkg install luci-app-xray

**Comment by yukeiyang** [comment]
具体原因不明。可能国内 DNS - 包括 114.114.114.114 以及腾讯-阿里等，都按照指示，使用了特殊机制来侦测重度科学上网用户，并进行封堵。

**Comment by yukeiyang** [comment]
不过自建 DNS Server 的确用起来非常流畅。

**Comment by yukeiyang** [comment]
经测试， FastDNS 填入我自建的 dns server， 在访问 Google Documents 服务时， 我自建的这台 dns server 收到了 10 条查询请求。

显然，114.114.114.114 等等的上游 DNS 服务商是根据这个纪录来锁定并侦测请求的。

**Comment by yukeiyang** [comment]
> 都设置DNS分流了，114 dns 怎么可能收到对谷歌服务的query呢？'

每次访问 google 时，我自配的 dns server 会收到对以下域名的解析请求：

fonts.gstatic.com
ssl.gstatic.com
www.gstatic.com

显然这是来自对 Google 站点的解析。

**Comment by yukeiyang** [comment]
> 啥叫废了？啥叫重度？

废了的意思就是，114.114.114.114 在 Fast DNS 的功能已经无法正常使用，换其它公共 DNS 又可恢复正常。问题在于，换过的公共 DNS 用了半个月左右以后，也就无法使用了。

重度就是，我的工作及生活严重依赖 Google Workspace | Business Apps & Collaboration Tools 系列服务，一天 24 小时都会连接 Google 服务。

**Comment by yukeiyang** [comment]
> 所谓“侦测”带来了什么后果？

后果就是，填入的公共 DNS 不能再正常解析域名。

**Comment by yukeiyang** [comment]
Anyway, 自配的 DNS Server 用作 Fast DNS 似乎能绕过公共 DNS 的这一 issue.

**Comment by yukeiyang** [comment]
@ttimasdf 

> DoH也没啥特别的优点，就是用了 TCP 查询延迟很大，没有解决你实际问题。如果非要用的话，两种方法。

说的有道理。

DoH 解决的，的确不是公共 DNS 的拒绝解析的这一 issue.

我真正想要的是，使用 DoH 能够加密裸奔的 dns 解析请求。

**Comment by yukeiyang** [comment]
又及，关于"重度"，我的情况是，除了工作重度依赖 Google Workspace 几十个产品以外，生活中的需求可能更多。我家中的 Apple TV  安装的 Netflix, Youtube， Infuse 流媒体，都时时刻刻在使用 Fast DNS 解析服务，和 Google 的情况一样，有很多域名譬如 gstatic.com 等等会被分配到 Fast DNS 来解析，而不是交由 Secure DNS 来解析。

**Comment by yukeiyang** [comment]
@ttimasdf 

> DoH也没啥特别的优点，就是用了 TCP 查询延迟很大

又及，自配 DoH 抑或其它公共 DoH 服务，我几个月的使用表明，延迟并不是一个问题，我自配的 DoH server 基本可以做到 5ms 以内。

**Comment by ttimasdf** [comment]
> 后果就是，填入的公共 DNS 不能再正常解析域名。

这个我也遇到过，具体的症状是 `dig baidu.com @114.114.114.114` 返回的状态码里有一个 `status: SERVFAIL`。看不出是啥原因，下回遇到问题了可以试试咱们是不是一个症状。

不过等一阵子以后再试就正常了。

我感觉可能就是个简单的rate limit。之前遇到这问题的时候用的是联通的4G网络（手机插USB开热点），现在换了光纤以后暂时还没遇到。

**Comment by yichya** [comment]
> @ttimasdf
> 
> Anyway, 归结起来一句话： Google.com, Facebook.com, Twitter.com, 以及 Netflix.com 等等的直接访问的域名的确不会分配给 Fast DNS, 但访问这些服务时所依赖的许多服务譬如 gstatic.com 等，还是会被分配到 Fast DNS，而不是 Secure DNS.
> 
> 当公共 DNS 收到足够多的针对这些网站的依赖服务的解析(譬如gstatic.com)，就能侦测并判定你是一个科学上网用户，并拒绝服务。

有个问题需要协助确认下。比如你在 Fast DNS 上写 223.5.5.5，等到 223.5.5.5 所有的请求全都超时，就像你说的这样拒绝服务了之后，你再用这个 IP 做 DoH（`https://223.5.5.5/dns-query`）看下能不能正常使用？

**Comment by yukeiyang** [comment]
问题在于：

1. 当前环境下，除了 114.114.114.114 以外，其它公共 DNS 是可以正常使用的。
2. 223.5.5.5, 目前可正常使用。
3. 必须要连续使用 223.5.5.5 或 119.29.29.29 等公共 DNS 半个月以上，才会出现被拒绝服务的 issue.

So, 目前测试 https://223.5.5.5/dns-query 似乎并不能给出你测试所需的答案。

**Comment by yukeiyang** [comment]
总之，截止目前的最佳实践是，

1. 使用自配的 dns server, 或者
2. 使用小型第三方 dns supplier 

互联网巨头 & 电信 & 联通 & 移动用作 Fast DNS 看来不可行，本质上他们都是一家。

**Comment by yukeiyang** [comment]
OpenWRT 平台上，我使用过 shadowsocks-libev, passwall, openclash,  luci-app-clash, 也包括其它一些。

结论就是，

截止目前，luci-app-xray  应该是最优雅的。

**Comment by LitCcc** [comment]
> 
> 
> > 忘了说， Fast DNS 无法填入 [223.5.5.5/dns-query](https://223.5.5.5/dns-query)
> 
> 这个功能接下来会着手做。在此之前可以先用官方的 [https-dns-proxy](https://github.com/openwrt/luci/tree/master/applications/luci-app-https-dns-proxy?rgh-link-date=2021-10-12T13%3A58%3A09Z) 试一试

想问一下本项目如何与 https-dns-proxy 配合使用呢？Fast Dns不支持填入`127.0.0.1:port`或者`127.0.0.1#port`这样的格式

**Comment by ttimasdf** [comment]
> > > 忘了说， Fast DNS 无法填入 [223.5.5.5/dns-query](https://223.5.5.5/dns-query)
> > 
> > 
> > 这个功能接下来会着手做。在此之前可以先用官方的 [https-dns-proxy](https://github.com/openwrt/luci/tree/master/applications/luci-app-https-dns-proxy?rgh-link-date=2021-10-12T13%3A58%3A09Z) 试一试
> 
> 想问一下本项目如何与 https-dns-proxy 配合使用呢？Fast Dns不支持填入`127.0.0.1:port`或者`127.0.0.1#port`这样的格式

之前我提过PR，现在revert掉了，可以编译[我的fork](https://github.com/ttimasdf/luci-app-xray/tree/all-pr) 里的 `all-pr` 分支。这里包含的更改可以填 https dns。

**Comment by ttimasdf** [comment]
参考： https://github.com/yichya/luci-app-xray/pull/89#issuecomment-945142020

其实我上面这条 comment 已经是 xray + DoH 的最佳实践了。再加别的东西进来……真就没必要 😅 而且 v2ray 的复杂度就摆在这，只能通过多写点文档通过配置示例给用户普及典型场景，瞎配置很容易把自己整断网，这不是开发者在脚本里多加几个 switch case 就能解决的问题。

xray 自己有一个[官方的配置例程repo](https://github.com/XTLS/Xray-examples)，我觉得这个已经足够好了。

本项目通过图形化的方式提高了**修改配置文件的效率**，

# 但绝不意味着一个 GUI 就能降低 xray 的使用门槛！

luci-app-v2ray 把 core 的 routing、inbound、outbound 的配置都暴露给了用户，说实在的，配置自由度比本项目还要高，我觉得每一个用户都得明白，无论是用 v2ray 还是 xray 还是 ss，如果连工具的基本功能都不了解，文档都没读过，

# 就别上来就用 GUI 工具然后配置不明白找 GUI 项目的麻烦！

**Comment by LitCcc** [comment]
> 
> 
> > > > 忘了说， Fast DNS 无法填入 [223.5.5.5/dns-query](https://223.5.5.5/dns-query)
> > > 
> > > 
> > > 这个功能接下来会着手做。在此之前可以先用官方的 [https-dns-proxy](https://github.com/openwrt/luci/tree/master/applications/luci-app-https-dns-proxy?rgh-link-date=2021-11-19T08%3A26%3A03Z) 试一试
> > 
> > 
> > 想问一下本项目如何与 https-dns-proxy 配合使用呢？Fast Dns不支持填入`127.0.0.1:port`或者`127.0.0.1#port`这样的格式
> 
> 之前我提过PR，现在revert掉了，可以编译[我的fork](https://github.com/ttimasdf/luci-app-xray/tree/all-pr?rgh-link-date=2021-11-19T08%3A26%3A03Z) 里的 `all-pr` 分支。这里包含的更改可以填 https dns。

谢谢，我编译下试试

**Comment by yichya** [comment]
> 想问一下本项目如何与 https-dns-proxy 配合使用呢？Fast Dns不支持填入`127.0.0.1:port`或者`127.0.0.1#port`这样的格式

好问题。。。先把这个安排一下

**Comment by yichya** [comment]
> 好问题。。。先把这个安排一下

#129

**Comment by LitCcc** [comment]
感谢🙇‍，最近发现了一个非常好用的项目 https://github.com/IrineSistiana/mosdns ，和xray搭配应该能解决ipv4/ipv6分流的问题

**Comment by yichya** [comment]
> 感谢🙇‍，最近发现了一个非常好用的项目 https://github.com/IrineSistiana/mosdns ，和xray搭配应该能解决ipv4/ipv6分流的问题

有点东西。。。这个可能会搞定我想要的很多功能

**Comment by yukeiyang** [comment]
@yicha 再次回报：

fonts.gstatic.com
ssl.gstatic.com
www.gstatic.com

这三个域名过去是被 bypass 到境内的，这导致 114.114.114.114 等一众 dns supplier 能够通过学习感知你是否在科学上网，重度用户会被 dns supplier 封堵, 而导致无法通过 Fast DNS 来解析而翻墙失败。这包括腾讯 & 阿里等等的国内的几乎所有的 DNS 服务商。 

最新版的 github.com/v2fly/domain-list-community 已经修正了这一隐患，gstatic 已经被 forward 到 xray server, 这一故障已经消失。

我测试了近两个月，Fast DNS 使用 192.168.1.1, 没有再遇到故障。

**Comment by ttimasdf** [comment]
> 这三个域名过去是被 bypass 到境内的，这导致 114.114.114.114 等一众 dns supplier 能够通过学习感知用户是否在科学上网，重度用户会被 dns supplier 封堵, 而导致无法通过 Fast DNS 来解析而翻墙失败。

 @yukeiyang 这个能详细解释一下么？我一直以为是我的 subnet DNS 查询量太大被 rate limit 了，，

**Comment by yukeiyang** [comment]
@ttimasdf 

1. v2ray,xray, 及 luci-app-xray 默认使用的 geodata 源是 https://github.com/v2fly/domain-list-community

2. 该 geodata 源过去长期把 Google 的以下三个域名解析到了当时国内存活的 Google 旗下站点，如果你过去采用自己所配的 dns server 作为 FAST DNS, 你将会发现这一点。

fonts.gstatic.com
ssl.gstatic.com
www.gstatic.com

3. 如果你是一个重度Google 用户，无时不刻在使用 Google 服务，那么就会在 FAST DNS 中你所选择填写的譬如 114.114.114.114 服务商处留下海量对以上三个 Google 旗下域名的解析请求记录，服务商通过机器学习就能判定你在科学上网。

4. 腾讯，阿里，114.114.114.114, 中国移动，电信等等，我猜应该都部署了政府要求的机器学习组件，这也是为什么每个以上提到 dns supplier 都会在你使用其作为 FAST DNS 一段时间之后封堵你的解析请求。

5. 不过 https://github.com/v2fly/domain-list-community 在几个月之前修补了这一漏洞，以上三个域名已经被添加，目前访问 Google 系服务时会解析到境外 Google 服务器。

6. 所以，现在已经不需要自配 dns server 用作 FAST DNS. 我过去所配用作 FAST DNS 的 dns server 机器已经销毁，不再使用。

最佳实践仍推荐在 iOS, Android, Windows, Apple TV, Linux 等等客户端使用自配 dns over https 服务器来解析 dns，这样最稳定。而不是单纯依靠 luci-app-xray 中填写的 8.8.8.8, 1.1.1.1 来解析。这是我使用自配 dns over https 几年的经验。
